= Verificador de taxa de eventos SVM (guia de dimensionamento de agentes)
:allow-uri-read: 


r--- barra lateral: link permanente da barra lateral: concept_cs_event_rate_checker.html resumo: Use o verificador de taxa de eventos SVM para medir as taxas de eventos NFS/SMB e determinar o dimensionamento ideal do agente antes de implantar os coletores de dados do Workload Security. palavras-chave: evento, verificador, taxa, dimensionamento, segurança na nuvem ---



= Verificador de taxa de eventos SVM (guia de dimensionamento de agentes)

[role="lead"]
O Event Rate Checker é usado para verificar a taxa de eventos combinada NFS/SMB no SVM antes de instalar um coletor de dados ONTAP SVM, para ver quantos SVMs uma máquina Agent será capaz de monitorar.  Use o Event Rate Checker como um guia de dimensionamento para ajudar a planejar seu ambiente de segurança.

Um agente pode suportar até 50 coletores de dados.



== Requisitos:

* IP de cluster
* Nome de usuário e senha do administrador do cluster



NOTE: Ao executar este script, nenhum coletor de dados ONTAP SVM deve estar em execução para o SVM para o qual a taxa de eventos está sendo determinada.

Passos:

. Instale o Agente seguindo as instruções do CloudSecure.
. Depois que o agente estiver instalado, execute o script _server_data_rate_checker.sh_ como um usuário sudo:
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. Este script requer que o _sshpass_ esteja instalado na máquina Linux.  Existem duas maneiras de instalá-lo:
+
.. Execute o seguinte comando:
+
 linux_prompt> yum install sshpass
.. Se isso não funcionar, baixe o _sshpass_ para a máquina Linux da web e execute o seguinte comando:
+
 linux_prompt> rpm -i sshpass


. Forneça os valores corretos quando solicitado.  Veja um exemplo abaixo.
. O script levará aproximadamente 5 minutos para ser executado.
. Após a conclusão da execução, o script imprimirá a taxa de eventos do SVM.  Você pode verificar a taxa de eventos por SVM na saída do console:
+
 “Svm svm_rate is generating 100 events/sec”.


Cada coletor de dados Ontap SVM pode ser associado a um único SVM, o que significa que cada coletor de dados poderá receber o número de eventos que um único SVM gera.

Tenha em mente o seguinte:

A) Use esta tabela como um guia geral de dimensionamento.  Você pode aumentar o número de núcleos e/ou memória para aumentar o número de coletores de dados suportados, até um máximo de 50 coletores de dados:

|===


| Configuração da máquina do agente | Número de coletores de dados SVM | Taxa máxima de eventos que a máquina do agente pode manipular 


| 4 núcleos, 16 GB | 10 coletores de dados | 20 mil eventos/seg 


| 4 núcleos, 32 GB | 20 coletores de dados | 20 mil eventos/seg 
|===
B) Para calcular o total de eventos, some os Eventos gerados para todos os SVMs daquele agente.

C) Se o script não for executado durante os horários de pico ou se o tráfego de pico for difícil de prever, mantenha um buffer de taxa de eventos de 30%.

B + C deve ser menor que A, caso contrário a máquina do agente não conseguirá monitorar.

Em outras palavras, o número de coletores de dados que podem ser adicionados a uma única máquina agente deve obedecer à fórmula abaixo:

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
Veja olink:concept_cs_agent_requirements.html["Requisitos do agente"] página para pré-requisitos e requisitos adicionais.



== Exemplo

Digamos que temos três SVMS gerando taxas de eventos de 100, 200 e 300 eventos por segundo, respectivamente.

Aplicamos a fórmula:

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
A saída do console está disponível na máquina do agente no arquivo __fpolicy_stat_<Nome do SVM>.log__ no diretório de trabalho atual.

O script pode dar resultados errôneos nos seguintes casos:

* Credenciais, IP ou nome SVM incorretos foram fornecidos.
* Uma fpolicy já existente com o mesmo nome, número de sequência, etc. dará erro.
* O script é interrompido abruptamente durante a execução.


Um exemplo de execução de script é mostrado abaixo:

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== Solução de problemas

|===


| Pergunta | Responder 


| Se eu executar esse script em um SVM que já está configurado para Workload Security, ele usará apenas a configuração fpolicy existente no SVM ou configurará uma temporária e executará o processo? | O Event Rate Checker pode ser executado corretamente mesmo para um SVM já configurado para Workload Security.  Não deve haver impacto. 


| Posso aumentar o número de SVMs nas quais o script pode ser executado? | Sim. Basta editar o script e alterar o número máximo de SVMs de 5 para qualquer número desejado. 


| Se eu aumentar o número de SVMs, o tempo de execução do script aumentará? | Não. O script será executado por no máximo 5 minutos, mesmo que o número de SVMs seja aumentado. 


| Posso aumentar o número de SVMs nas quais o script pode ser executado? | Sim. Você precisa editar o script e alterar o número máximo de SVMs de 5 para qualquer número desejado. 


| Se eu aumentar o número de SVMs, o tempo de execução do script aumentará? | Não. O script será executado por no máximo 5 minutos, mesmo que o número de SVMs seja aumentado. 


| O que acontece se eu executar o Event Rate Checker com um agente existente? | Executar o Event Rate Checker em um agente já existente pode causar um aumento na latência no SVM.  Esse aumento será temporário por natureza enquanto o Verificador de taxas de eventos estiver em execução. 
|===