---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: Opções de exibição de dados do Telegraf 
---
= Transformando Métricas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Data Infrastructure Insights fornece diferentes opções de *transformação* para determinadas métricas em widgets (especificamente, aquelas métricas chamadas "Personalizadas" ou Métricas de Integração, como do Kubernetes, ONTAP Advanced Data, plugins Telegraf, etc.), permitindo que você exiba os dados de diversas maneiras.  Ao adicionar métricas transformáveis ​​a um widget, você verá um menu suspenso com as seguintes opções de transformação:

Nenhum: os dados são exibidos como estão, sem manipulação.

Taxa: Valor atual dividido pelo intervalo de tempo desde a observação anterior.

Cumulativo: Acumulação da soma dos valores anteriores e do valor atual.

Delta: A diferença entre o valor da observação anterior e o valor atual.

Taxa delta: valor delta dividido pelo intervalo de tempo desde a observação anterior.

Taxa cumulativa: valor cumulativo dividido pelo intervalo de tempo desde a observação anterior.

Observe que a transformação de métricas não altera os dados subjacentes em si, mas apenas a maneira como os dados são exibidos.
