---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: A seção Dados do usuário de uma página de ativo permite que você atribua anotações ou aplicativos ao ativo atual. 
keywords: asset page, user data, applications, annotations 
---
= Seção de Dados do Usuário
:hardbreaks:
:allow-uri-read: 


[role="lead"]
A seção Dados do usuário de uma página de ativos exibe e permite que você altere quaisquer dados definidos pelo usuário, como aplicativos e anotações.



== Usando a seção Dados do Usuário para atribuir ou modificar aplicativos

Você pode atribuir aplicativos em execução no seu locatário a determinados ativos (host, máquinas virtuais, volumes, volumes internos, qtrees e hipervisores).  A seção Dados do usuário permite adicionar, alterar ou remover os aplicativos atribuídos a um ativo.  Para todos esses tipos de ativos, exceto volumes, você pode atribuir mais de um aplicativo.

.Passos
. Localize uma página de ativos executando qualquer um dos seguintes procedimentos:
+
.. Consulte uma lista de ativos e selecione um da lista.
.. Em um painel, localize o nome de um ativo e clique nele.
.. Faça uma pesquisa e escolha um ativo nos resultados.
+
A página de ativos é exibida.  A seção Dados do usuário da página mostra os aplicativos ou anotações atribuídos no momento.





Para alterar o aplicativo atribuído ou atribuir um ou mais aplicativos, abra a lista *Aplicativo* e selecione o(s) aplicativo(s) que deseja atribuir ao ativo.  Você pode digitar para procurar um aplicativo ou selecionar um da lista.

Para remover um aplicativo, abra a lista de aplicativos e desmarque o aplicativo.



== Usando a seção Dados do Usuário para atribuir ou modificar anotações

Ao personalizar o Data Infrastructure Insights para rastrear dados para suas necessidades corporativas, você pode definir notas especializadas chamadas anotações e atribuí-las aos seus ativos.  A seção Dados do usuário de uma página de ativo exibe anotações atribuídas a um ativo e também permite que você altere as anotações atribuídas a esse ativo.

.Passos
. Para adicionar uma anotação ao ativo, na seção Dados do usuário da página do ativo, clique em *+Anotação*.
. Selecione uma anotação da lista.
. Clique em Valor e faça um dos seguintes, dependendo do tipo de anotação selecionado:
+
.. Se o tipo de anotação for lista, data ou booleano, selecione um valor da lista.
.. Se o tipo de anotação for texto, digite um valor.


. Clique em Salvar.


A anotação é atribuída ao ativo.  Mais tarde, você pode filtrar ativos por anotação usando uma consulta.

Se você quiser alterar o valor da anotação depois de atribuí-la, abra a lista de anotações e insira um valor diferente.

Se a anotação for do tipo lista para a qual a opção _Adicionar novos valores em tempo real_ estiver selecionada, você poderá digitar para adicionar um novo valor além de selecionar um valor existente.
