---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: Técnicas de pesquisa avançada podem ajudar você a localizar os ativos que está procurando. 
keywords: asset page, objects, search, advanced, alerts 
---
= Dicas e sugestões para pesquisar ativos e alertas
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Várias técnicas de pesquisa podem ser usadas para procurar dados ou objetos no seu ambiente monitorado.

* *Pesquisa curinga*
+
Você pode realizar uma pesquisa com vários caracteres curinga usando o caractere *.  Por exemplo, _applic*n_ retornaria _application_.

* *Frases usadas na pesquisa*
+
Uma frase é um grupo de palavras entre aspas duplas; por exemplo, "VNX LUN 5".  Você pode usar aspas duplas para pesquisar documentos que contenham espaços em seus nomes ou atributos.

* *Operadores booleanos*
+
Usando os operadores booleanos OR, AND e NOT, você pode combinar vários termos para formar uma consulta mais complexa.

+
OU

+
O operador OR é o operador de conjunção padrão.

+
Se não houver operador booleano entre dois termos, o operador OR será usado.

+
O operador OR vincula dois termos e encontra um documento correspondente se qualquer um dos termos existir em um documento.

+
Por exemplo, _storage OR netapp_ pesquisa documentos que contêm _storage_ ou _netapp_.

+
Pontuações altas são dadas aos documentos que correspondem à maioria dos termos.

+
E

+
Você pode usar o operador AND para encontrar documentos nos quais ambos os termos de pesquisa existem em um único documento.  Por exemplo, _storage AND netapp_ pesquisa documentos que contêm _storage_ e _netapp_.

+
Você pode usar o símbolo *&&* em vez da palavra AND.

+
NÃO

+
Quando você usa o operador NOT, todos os documentos que contêm o termo depois de NOT são excluídos dos resultados da pesquisa.  Por exemplo, _storage NOT netapp_ pesquisa documentos que contêm apenas _storage_ e não _netapp_.

+
Você pode usar o símbolo *!* em vez da palavra NOT.



A pesquisa não diferencia maiúsculas de minúsculas.



== Pesquisar usando termos indexados

Pesquisas que correspondem a mais termos indexados resultam em pontuações mais altas.

A sequência de pesquisa é dividida em termos de pesquisa separados por espaço.  Por exemplo, a sequência de pesquisa "storage aurora netapp" é dividida em três palavras-chave: "storage", "aurora" e "netapp".  A pesquisa é realizada usando todos os três termos.  Os documentos que corresponderem à maioria desses termos terão a pontuação mais alta.  Quanto mais informações você fornecer, melhores serão os resultados da pesquisa.  Por exemplo, você pode procurar um armazenamento pelo nome e modelo.

A interface do usuário exibe os resultados da pesquisa em todas as categorias, com os três principais resultados por categoria.  Se você não encontrou o objeto que esperava, pode incluir mais termos na sequência de pesquisa para melhorar os resultados da pesquisa.

A tabela a seguir fornece uma lista de termos indexados que podem ser adicionados à sequência de pesquisa.

|===
| Categoria | Termos indexados 


| Armazenar | modelo de fornecedor de nome de "armazenamento" 


| Pool de armazenamento | nome do "storagepool" nome do armazenamento endereços IP do armazenamento número de série do armazenamento fornecedor do armazenamento nomes do modelo de armazenamento para todos os volumes internos associados nomes para todos os discos associados 


| Volume interno | nome "internalvolume" nome do armazenamento endereços IP do armazenamento número de série do armazenamento fornecedor de armazenamento modelo de armazenamento nome do pool de armazenamento nomes de todos os compartilhamentos associados nomes de todos os aplicativos associados 


| Volume | rótulo de nome de "volume" nomes de todos os volumes internos nome do pool de armazenamento nome do armazenamento endereços IP do armazenamento número de série do armazenamento fornecedor do armazenamento modelo de armazenamento 


| Nó de armazenamento | nome "storagenode" nome do armazenamento endereços IP do armazenamento número de série do armazenamento fornecedor de armazenamento modelo de armazenamento 


| Hospedar | nome do "host" endereços IP nomes de todos os aplicativos associados 


| Armazenamento de dados | nome do "datastore" centro virtual nomes de IP de todos os volumes nomes de todos os volumes internos 


| Máquinas Virtuais | nome "virtualmachine" nome DNS endereços IP nome do host endereços IP do host nomes de todos os datastores nomes de todos os aplicativos associados 


| Interruptores (regular e VPL) | endereço IP do "switch" nome wwn número de série modelo ID de domínio nome do fabric wwn do fabric 


| Aplicativo | "aplicativo" nome inquilino linha de negócios unidade de negócios projeto 


| Fita | "fita" endereço IP nome número de série fornecedor 


| Porta | nome wwn "porta" 


| Tecido | nome wwn "tecido" 


| Máquina Virtual de Armazenamento (SVM) | UUID do nome "storagevirtualmachine" 
|===