---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: Proteja seus dados com a detecção de ameaças internas do Storage Workload Security, visibilidade centralizada em ambientes híbridos e aprendizado de máquina avançado para detecção de anomalias e conformidade. 
---
= Sobre a segurança da carga de trabalho de armazenamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Data Infrastructure Insights Storage Workload Security (anteriormente Cloud Secure) protege os dados da sua organização com detecção avançada de ameaças internas e inteligência acionável. Obtenha visibilidade e controle centralizados sobre todo o acesso a dados corporativos em ambientes de nuvem híbrida, garantindo o cumprimento das metas de segurança e conformidade por meio de monitoramento em tempo real e recursos de resposta automatizada.



[[visibility]]
== Visibilidade

Obtenha visibilidade e controle centralizados do acesso do usuário aos seus dados corporativos críticos armazenados no local ou na nuvem.

Substitua ferramentas e processos manuais que não fornecem visibilidade precisa e oportuna do acesso e controle de dados.  O Workload Security opera exclusivamente em sistemas de armazenamento na nuvem e no local para fornecer alertas em tempo real sobre comportamento malicioso de usuários.



[[protection]]
== Proteção

Proteja os dados organizacionais contra uso indevido por usuários mal-intencionados ou comprometidos por meio de aprendizado de máquina avançado e detecção de anomalias.

Alerta você sobre qualquer acesso anormal a dados por meio de aprendizado de máquina avançado e detecção de anomalias no comportamento do usuário.



[[compliance]]
== Conformidade

Garanta a conformidade corporativa auditando o acesso dos dados do usuário aos seus dados corporativos críticos armazenados no local ou na nuvem.
