---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: Visão geral 
---
= Sobre a segurança da carga de trabalho de armazenamento
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights Storage Workload Security (antigo Cloud Secure) ajuda a proteger seus dados com inteligência acionável sobre ameaças internas.  Ele fornece visibilidade e controle centralizados de todo o acesso a dados corporativos em ambientes de nuvem híbrida para garantir que as metas de segurança e conformidade sejam atendidas.



== Visibilidade

Obtenha visibilidade e controle centralizados do acesso do usuário aos seus dados corporativos críticos armazenados no local ou na nuvem.

Substitua ferramentas e processos manuais que não fornecem visibilidade precisa e oportuna do acesso e controle de dados.  O Workload Security opera exclusivamente em sistemas de armazenamento na nuvem e no local para fornecer alertas em tempo real sobre comportamento malicioso de usuários.



== Proteção

Proteja os dados organizacionais contra uso indevido por usuários mal-intencionados ou comprometidos por meio de aprendizado de máquina avançado e detecção de anomalias.

Alerta você sobre qualquer acesso anormal a dados por meio de aprendizado de máquina avançado e detecção de anomalias no comportamento do usuário.



== Conformidade

Garanta a conformidade corporativa auditando o acesso dos dados do usuário aos seus dados corporativos críticos armazenados no local ou na nuvem.
