---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: Adicionar endereços de e-mail para notificações de alertas de segurança de carga de trabalho. 
keywords: email, notifications, alerts, warnings, attacks 
---
= Configurando notificações por e-mail para alertas, avisos e integridade do agente/coletor de fonte de dados
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Para configurar os destinatários dos alertas de segurança da carga de trabalho, clique em *Admin > Notificações* e insira um endereço de e-mail nas seções apropriadas para cada destinatário.



== Alertas e avisos de ataques potenciais

Para enviar notificações de alerta de _Ataque Potencial_, insira os endereços de e-mail dos destinatários na seção _Enviar Alertas de Ataque Potencial_.  Notificações por e-mail são enviadas para a lista de destinatários do alerta para cada ação no alerta.

Para enviar notificações de _Aviso_, insira os endereços de e-mail dos destinatários na seção _Enviar alertas de aviso_.



== Monitoramento de integridade do agente e do coletor de dados

Você pode monitorar a integridade dos Agentes e Fontes de Dados por meio de notificações.

Para receber notificações caso um Agente ou coletor de Fonte de Dados não esteja funcionando, insira os endereços de e-mail dos destinatários na seção _Alertas de integridade da coleta de dados_.

Tenha em mente o seguinte:

* Os alertas de saúde serão enviados somente após o agente/coletor parar de reportar por pelo menos uma hora.
* Apenas uma notificação por e-mail é enviada aos destinatários pretendidos em um determinado período de 24 horas, mesmo que o Agente ou o Coletor de Dados esteja desconectado por um período mais longo.
* Em caso de falha de um Agente, um alerta será enviado (não um por coletor).  O e-mail incluirá uma lista de todos os SVMs afetados.
* A falha na coleta do Active Directory é relatada como um aviso; ela não afeta a detecção de Ransomware.
* A lista de configuração de Introdução agora inclui uma nova fase _Configurar notificações por e-mail_.




== Recebendo notificações de atualização do agente e do coletor de dados

* Insira o(s) ID(s) de e-mail em “Alertas de saúde de coleta de dados”.
* A caixa de seleção “Habilitar notificações de atualização” fica habilitada.
* As notificações por e-mail de atualização do Agente e do Coletor de Dados são enviadas para os IDs de e-mail um dia antes da atualização planejada.




== Solução de problemas

|===
| *Problema:* | *Experimente isto:* 


| Os IDs de e-mail estão presentes nos “Alertas de saúde do coletor de dados”, mas não estou recebendo notificações. | Os e-mails de notificação são enviados do domínio do NetApp Data Infrastructure Insights , ou seja, de _accounts@service.cloudinsights.netapp.com_.  Algumas empresas bloqueiam e-mails recebidos se eles forem de um domínio externo.  Certifique-se de que as notificações externas dos domínios do NetApp Data Infrastructure Insights estejam na lista de permissões. 
|===