---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= Configuração e dispositivos suportados
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esta FAQ responde a perguntas comuns sobre a configuração do Data Infrastructure Insights e dispositivos compatíveis.



== O Data Infrastructure Insights faz alterações no meu ambiente?

O Data Infrastructure Insights é uma ferramenta somente leitura que reúne informações sobre o seu ambiente. O Data Infrastructure Insights nunca faz alterações em seus ativos ou configurações.



== Que acesso em nível de permissão o Data Infrastructure Insights precisa para meus dispositivos?

Na maioria dos casos em que o dispositivo o suporta, um acesso somente leitura é tudo o que é necessário. Existem algumas soluções que não permitem acesso somente leitura e, portanto, exigiriam as permissões elevadas apropriadas.



== Com que frequência o Data Infrastructure Insights coleta informações?

O Data Infrastructure Insights geralmente coleta dados de desempenho a cada 5 minutos e descoberta de construções lógicas e físicas a cada ½ hora O Data Infrastructure Insights define os intervalos de polling padrão de acordo com as práticas recomendadas sugeridas e a escalabilidade, mas permite que o usuário controle total sobre esses intervalos.



== Qual é o impactos do Data Infrastructure Insights no meu ambiente?

As comunicações IP sem agentes, fora da banda e passivas do Data Infrastructure Insights ajudam a minimizar a configuração, a manutenção e o impactos no ecossistema do data center. A equipe de desenvolvimento de desempenho do Data Infrastructure Insights toma ótimas medidas para minimizar qualquer impactos no desempenho do data center nas atividades de monitoramento do próprio desempenho. O impactos é considerado insignificante em ambientes operacionais normais e pode ser relaxado ou apertado em plataformas de tecnologia altamente utilizadas ou com baixo desempenho. Consulte o Guia de instalação do Data Infrastructure Insights para obter mais informações.



== Como posso listar todos os hosts/VM no Data Infrastructure Insights?

O elogio de widgets e possibilidades de listagem de consultas do Data Infrastructure Insights pode ser usado para fornecer listagens de estilo de inventário para ativos do Data Center. Listagens de máquinas virtuais até os fusos e inúmeras construções entre eles podem ser disponibilizadas para consultas, widgets, painéis e relatórios de data warehouse, e são acessíveis através da API RESTful.



== O Data Infrastructure Insights oferece o mesmo tipo de suporte para hosts não hipervisores relacionados (ou seja, servidores físicos)?

Os hipervisores, como VMware, fornecem informações detalhadas sobre os hosts ESXI e suas máquinas virtuais (VMs). Para servidores físicos, o Data Infrastructure Insights coleta métricas até o HBA do host. O Data Infrastructure Insights emprega um método exclusivo no qual descobre servidores físicos usando uma tecnologia com patente pendente. Depois que o storage e/ou switches forem descobertos, os nomes de host para servidores físicos estarão contidos nas informações de alias da malha. O Data Infrastructure Insights seleciona esses nomes de host, corresponde a eles no DNS e leva os hosts automaticamente ao Data Infrastructure Insights. Esta técnica minimiza muito a necessidade de atualizações manuais de entrada e manutenção do inventário de ferramentas.



== Os Data Infrastructure Insights fornecem a mesma profundidade métrica (paridade) do dispositivo em ambientes heterogêneos?

Existem vários graus de padronização, semelhança e nomenclatura em plataformas de 3rd partes e tecnologias de fornecedores. O Data Infrastructure Insights tenta normalizar as informações de capacidade e performance em uma estrutura consistente. Algumas métricas de capacidade e desempenho são fornecidas nativamente a partir dos contadores do dispositivo, como IOPs, latência e capacidade bruta. Quando não são fornecidos contadores, o Data Infrastructure Insights pode tentar resumir os valores (por exemplo, somando as IOPs ou capacidades dos volumes subjacentes) e, nos casos em que nenhum deles está disponível, o Data Infrastructure Insights tentará derivar os valores métricos através de vários algoritmos computacionais. O Data Infrastructure Insights fornece um recurso genérico de integração SNMP para incorporar métricas adicionais não coletadas atualmente pelo Data Infrastructure Insights.



== O Data Infrastructure Insights oferece suporte a switches Fibre Channel?

Sim, além de coletar dados de seus ativos de armazenamento, o Data Infrastructure Insights também adquire dados de inventário e desempenho de switches Cisco, Brocade e QLogic em seu ambiente.



== As visualizações de topologia de toda a infraestrutura estão disponíveis? O Data Infrastructure Insights mostra "visibilidade completa"?

Sim, o Data Infrastructure Insights descobre e mapeia dinamicamente as construções lógicas e físicas, fornecendo uma visualização interativa de topologia de ponta a ponta de computação, malhas, Virtualizers e armazenamento de back-end. Os ícones de topologia permitem uma navegação de inicialização rápida para os recursos afetados e ajudam na identificação de cargas de trabalho e violações em ambientes de storage compartilhado.
