---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= Configuração e dispositivos suportados
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Estas perguntas frequentes respondem a perguntas comuns sobre a configuração do Data Infrastructure Insights e os dispositivos suportados.



== O Data Infrastructure Insights faz alterações no meu ambiente?

Não. O Data Infrastructure Insights é uma ferramenta somente leitura que coleta informações sobre seu ambiente.  O Data Infrastructure Insights nunca faz alterações em seus ativos ou configurações.



== Qual nível de permissão de acesso o Data Infrastructure Insights precisa para meus dispositivos?

Na maioria dos casos em que o dispositivo oferece suporte, tudo o que é necessário é um acesso somente leitura.  Existem algumas soluções que não permitem acesso somente leitura e, portanto, exigiriam permissões elevadas apropriadas.



== Com que frequência o Data Infrastructure Insights coleta informações?

O Data Infrastructure Insights normalmente coleta dados de desempenho a cada 5 minutos e descobre construções lógicas e físicas a cada ½ hora.  O Data Infrastructure Insights define os intervalos de pesquisa padrão de acordo com as melhores práticas sugeridas e escalabilidade, mas permite ao usuário controle total sobre esses intervalos.



== Qual é o impacto do Data Infrastructure Insights no meu ambiente?

As comunicações IP passivas, fora de banda e sem agente do Data Infrastructure Insights ajudam a minimizar a configuração, a manutenção e o impacto no ecossistema do data center.  A equipe de desenvolvimento de desempenho da Data Infrastructure Insights toma grandes medidas para minimizar qualquer impacto no desempenho do data center nas atividades de monitoramento do próprio desempenho.  O impacto é considerado insignificante em ambientes operacionais normais e pode ser relaxado ou reduzido em plataformas tecnológicas altamente utilizadas ou de baixo desempenho.  Consulte o Guia de instalação do Data Infrastructure Insights para obter mais informações.



== Como posso listar todos os hosts/VMs no Data Infrastructure Insights?

O complemento de widgets e possibilidades de listagem de consultas do Data Infrastructure Insights pode ser usado para fornecer listagens de estilo de inventário para ativos do Data Center.  Listagens de máquinas virtuais, até os spindles e inúmeras construções intermediárias, podem ser disponibilizadas para consultas, widgets, painéis e relatórios de data warehouse, e são acessíveis por meio da API RESTful.



== O Data Infrastructure Insights fornece o mesmo tipo de suporte para hosts não hipervisores relacionados (ou seja, servidores físicos)?

Hipervisores como o VMware fornecem informações detalhadas sobre os hosts ESXI e suas máquinas virtuais (VMs).  Para servidores físicos, o Data Infrastructure Insights coleta métricas até o HBA do host.  O Data Infrastructure Insights emprega um método exclusivo no qual descobre servidores físicos usando uma tecnologia com patente pendente.  Depois que o armazenamento e/ou os switches são descobertos, os nomes de host dos servidores físicos são contidos nas informações de alias da malha.  O Data Infrastructure Insights seleciona esses nomes de host, os compara no DNS e os traz automaticamente para o Data Infrastructure Insights.  Essa técnica minimiza muito a necessidade de atualizações de entrada manual e manutenção de inventário de ferramentas.



== O Data Infrastructure Insights fornece a mesma profundidade de métrica de dispositivo (paridade) em ambientes heterogêneos?

Há vários graus de padronização, uniformidade e nomenclatura entre plataformas de terceiros e tecnologias de fornecedores.  O Data Infrastructure Insights tenta normalizar informações de capacidade e desempenho em uma estrutura consistente.  Algumas métricas de capacidade e desempenho são fornecidas nativamente pelos contadores do dispositivo, como IOPs, latência e capacidade bruta.  Quando os contadores não são fornecidos, o Data Infrastructure Insights pode tentar resumir os valores (por exemplo, totalizando os IOPs ou capacidades dos volumes subjacentes) e, nos casos em que nenhum dos dois estiver disponível, o Data Infrastructure Insights tentará derivar os valores métricos por meio de vários algoritmos computacionais.  O Data Infrastructure Insights fornece um recurso genérico de integração SNMP para incorporar métricas adicionais que atualmente não são coletadas pelo Data Infrastructure Insights .



== O Data Infrastructure Insights oferece suporte a switches Fibre Channel?

Sim, além de coletar dados de seus ativos de armazenamento, o Data Infrastructure Insights também adquire dados de inventário e desempenho de switches Cisco, Brocade e QLogic em seu locatário.



== As visualizações de topologia de toda a infraestrutura estão disponíveis?  O Data Infrastructure Insights mostra “visibilidade de ponta a ponta”?

Sim, o Data Infrastructure Insights descobre e mapeia dinamicamente as construções lógicas e físicas, fornecendo uma visão interativa da topologia de ponta a ponta de computação, malhas, virtualizadores e armazenamento de back-end.  Os ícones de topologia permitem uma navegação rápida para recursos impactados e auxiliam na identificação de cargas de trabalho e violações em ambientes de armazenamento compartilhado.
