---
sidebar: sidebar 
permalink: forensic_user_overview.html 
keywords: Forensic, user, user, activity 
summary: detalhes do usuário forense 
---
= Visão geral do usuário forense
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informações para cada usuário são fornecidas na Visão Geral do Usuário.  Use essas visualizações para entender as características do usuário, entidades associadas e atividades recentes.



== Perfil do usuário

As informações do perfil do usuário incluem informações de contato e localização do usuário.  O perfil fornece as seguintes informações:

* Nome do usuário
* Endereço de e-mail do usuário
* Gerenciador de usuários
* Contato telefônico do usuário
* Localização do usuário




== Comportamento do usuário

As informações de comportamento do usuário identificam atividades e operações recentes realizadas pelo usuário.  Essas informações incluem:

* Atividade recente
+
** Último local de acesso
** Gráfico de atividade
** Alertas




* Operações dos últimos sete dias
+
** Número de operações






== Intervalo de atualização

A lista de usuários é atualizada a cada 12 horas.



== Política de retenção

Se não for atualizada novamente, a lista de usuários será mantida por 13 meses.  Após 13 meses, os dados serão excluídos.  Se o seu ambiente de segurança de carga de trabalho for excluído, todos os dados associados ao ambiente serão excluídos.
