---
sidebar: sidebar 
permalink: forensic_alert_detail.html 
keywords: alert, Critical, Warning, Low, alert detail Synopsis, Time range, Start time, End time, user 
summary: detalhes do alerta 
---
= Detalhes do alerta
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Clicar na sinopse de um alerta abre a página que fornece informações detalhadas sobre o usuário e o alerta que ele gerou.



== A página Detalhes do alerta exibe o usuário

Detalhes do alerta fornece informações para o alerta selecionado na página Alertas.

* A gravidade do alerta
* O usuário que gerou o alerta e o tipo de alerta:
+
** Acesso anormal pelo usuário
** Acesso anormal por comunidade
** Acesso anormal por usuário na comunidade
** O usuário se juntou a muitas comunidades


* Data e hora em que o alerta foi detectado
* A ação tomada
+
** Em quarentena
** Outro
** Outro


* O status do alerta
+
** Novo
** Em andamento
** Demitido
** Resolvido


* Alteração na taxa de atividade do usuário
+
** Atividades típicas por hora
** Atividades por hora quando o alerta foi acionado.
** Porcentagem de alteração de taxa que causou o alerta.


* Um gráfico mostrando a taxa média histórica de atividade e a taxa de atividade que resultou no alerta.




=== Usuário relacionado

* Nome de usuário e título
* Departamento
* E-mail com um link para o endereço de e-mail
* Gerente
* Telefone
* Localização




=== Atividade

Mostra a atividade do usuário nos últimos 7 dias e o último local de onde o usuário acessou.

* Atividades:
+
** Ler
** Outro
** Criar


* Número total de alertas nos últimos sete dias.
* Número total de atividades nos últimos 7 dias.


Clique em *Ver detalhes da atividade* para acessar olink:forensic_activity_history["Histórico de atividades"] do usuário que está sendo examinado.
