---
sidebar: sidebar 
permalink: index.html 
summary: Bem-vindo ao portal de documentação do Data Infrastructure Insights. 
keywords:  
---
= Documentação do Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O NetApp Data Infrastructure Insights (anteriormente Cloud Insights) é uma ferramenta de monitoramento de infraestrutura de nuvem que oferece visibilidade de toda a sua infraestrutura. Com o Data Infrastructure Insights, você pode monitorar, solucionar problemas e otimizar todos os seus recursos, incluindo suas nuvens públicas e seus data centers privados.



== O que o Data Infrastructure Insights pode fazer por mim?

O Data Infrastructure Insights fornece monitoramento multicloud híbrido, proporcionando observabilidade completa de infraestrutura e cargas de trabalho.

* Coletores de dados para infraestrutura e cargas de trabalho heterogêneas, incluindo Kubernetes
* Coletor Telegraf aberto e APIs abertas para fácil integração
* Alertas e notificações abrangentes
* Aprendizado de máquina para insights inteligentes
* Otimizar a utilização de recursos
* Painéis integrados ou personalizáveis com filtros avançados para minimizar o ruído de exibição e responder a perguntas
* Descubra a saúde das suas operações de armazenamento ONTAP 
* Proteja seu ativo de negócios mais valioso – os dados – contra adulteração de arquivos ou ataque de destruição de dados


'''


== Começando

* Como eu façolink:task_cloud_insights_onboarding_1.html["*comece*"] com o Data Infrastructure Insights?
* Estou inscrito.  Agora o que eu faço?link:task_getting_started_with_cloud_insights.html["Aquisição de dados"] link:concept_user_roles.html["Configurando usuários"]
* Incrível!  O que vem a seguir?link:task_defining_annotations.html["Preparando Ativos: Anotando"] link:concept_querying_assets.html["Encontrando os ativos que você deseja: consultando"] link:concept_dashboards_overview.html["Veja os dados que você deseja: painéis"] link:task_create_monitor.html["Monitoramento e Alertas"] link:task_cs_getting_started.html["Protegendo Dados"]
* Isso é ótimo!  Estou pronto paralink:concept_subscribing_to_cloud_insights.html["*inscrever-se*"] .

