---
sidebar: sidebar 
permalink: index.html 
summary: Bem-vindo ao portal de documentação do Data Infrastructure Insights. 
keywords:  
---
= Documentação do Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O NetApp Data Infrastructure Insights (anteriormente conhecido como Cloud Insights) é uma ferramenta de monitoramento de infraestrutura de nuvem que oferece visibilidade de toda a sua infraestrutura. Com o Data Infrastructure Insights, você pode monitorar, solucionar problemas e otimizar todos os recursos, incluindo suas nuvens públicas e seus data centers privados.



== O que o Data Infrastructure Insights pode fazer por mim?

O Data Infrastructure Insights oferece monitoramento de multicloud híbrida, com uma observabilidade de toda a stack de infraestrutura e workloads.

* Coletores de dados para infraestrutura e workloads heterogêneos, incluindo Kubernetes
* Open Telegraf Collector e APIs abertas para fácil integração
* Alertas e notificações abrangentes
* Aprendizado de máquina para insights inteligentes
* Otimizar a utilização de recursos
* Painéis integrados ou personalizáveis com filtros avançados para minimizar o ruído de exibição para responder a perguntas
* Descubra a integridade das operações de storage da ONTAP 
* Proteja seu ativo comercial mais valioso: Os dados, contra ransomware ou ataque de destruição de dados


'''


== Como começar

* Como faço link:task_cloud_insights_onboarding_1.html["*comece já*"]com o Data Infrastructure Insights?
* Estou inscrito. Agora, o que eu faço? link:task_getting_started_with_cloud_insights.html["A adquirir dados"] link:concept_user_roles.html["Configurando usuários"]
* Incrível! O que se segue? link:task_defining_annotations.html["Preparar ativos: Anotar"] link:concept_querying_assets.html["Encontrando os ativos que você quer: Consultando"] link:concept_dashboards_overview.html["Ver os dados que você deseja: Painéis"] link:task_create_monitor.html["Monitoramento e alertas"] link:task_cs_getting_started.html["Proteção de dados"]
* Isso é ótimo! Estou pronto para link:concept_subscribing_to_cloud_insights.html["*subscribe*"].

