---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: Os insights oferecem uma visão do uso de recursos e tendências. 
---
= Percepções
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Os insights permitem que você analise coisas como o uso de recursos e como ele afeta outros recursos, ou análises de tempo total.

Há uma série de Insights disponíveis.  Navegue até *Painéis > Insights* para começar a se aprofundar. Você pode visualizar Insights ativos (Insights que estão ocorrendo no momento) na guia principal ou Insights inativos na guia _Insights inativos_.  Insights inativos são aqueles que estavam ativos anteriormente, mas não estão mais ocorrendo.



== Tipos de Insight



=== Recursos compartilhados sob estresse

Cargas de trabalho de alto impacto podem reduzir o desempenho de outras cargas de trabalho em um recurso compartilhado.  Isso coloca o recurso compartilhado sob estresse.  O Data Infrastructure Insights fornece ferramentas para ajudar você a investigar a saturação de recursos e o impacto no seu locatário.link:insights_shared_resources_under_stress.html["Saber mais"]



=== Espaços para namespaces do Kubernetes ficando sem espaço

O Kubernetes Namespaces Running Out of Space Insight fornece uma visão das cargas de trabalho em seus namespaces do Kubernetes que correm o risco de ficar sem espaço, com uma estimativa do número de dias restantes antes que cada espaço fique cheio.link:insights_k8s_namespaces_running_out_of_space.html["Saber mais"]



=== Recuperar armazenamento refrigerado ONTAP

O _Reclaim ONTAP Cold Storage_ Insight fornece dados sobre capacidade de refrigeração, potencial economia de custos/energia e itens de ação recomendados para volumes em sistemas ONTAP .link:insights_reclaim_ontap_cold_storage.html["Saber mais"]


NOTE: Este é um recurso de _prévia_ e pode mudar ao longo do tempo conforme melhorias são feitas. link:/concept_preview_features.html["Saber mais"] sobre os recursos de visualização do Data Infrastructure Insights .
