---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: O Data Infrastructure Insights oferece suporte à Telegraf como seu agente para coleta de dados de integração no Kubernetes. 
---
= Antes de instalar ou atualizar o NetApp Kubernetes Monitoring Operator
:hardbreaks:
:allow-uri-read: 
:nofooter: 


[role="lead"]
Leia estas informações antes de instalar ou atualizar olink:task_config_telegraf_agent_k8s.html["Operador de monitoramento do Kubernetes"] .

|===
| Componente | Exigência 


| Versão do Kubernetes | Kubernetes v1.20 e superior. 


| Distribuições Kubernetes | AWS Elastic Kubernetes Service (EKS) Azure Kubernetes Service (AKS) Google Kubernetes Engine (GKE) Red Hat OpenShift Rancher Kubernetes Engine (RKE) VMware Tanzu 


| Sistema operacional Linux | O Data Infrastructure Insights não oferece suporte a nós executados com arquitetura Arm64.  Monitoramento de rede: deve estar executando o kernel Linux versão 4.18.0 ou superior.  O Photon OS não é suportado. 


| Etiquetas | O Data Infrastructure Insights oferece suporte ao monitoramento de nós do Kubernetes que executam Linux, especificando um seletor de nós do Kubernetes que procura os seguintes rótulos do Kubernetes nessas plataformas: Kubernetes v1.20 e superior: Kubernetes.io/os = linux Rancher + cattle.io como plataforma de orquestração/Kubernetes: cattle.io/os = linux 


| Comandos | Os comandos curl e kubectl devem estar disponíveis; para melhores resultados, adicione esses comandos ao PATH. 


| Conectividade | O kubectl cli está configurado para se comunicar com o cluster K8s de destino e ter conectividade com a Internet para seu ambiente do Data Infrastructure Insights .  Se você estiver atrás de um proxy durante a instalação, siga as instruções nolink:task_config_telegraf_agent_k8s.html#configuring-proxy-support["Configurando o suporte a proxy"] seção da instalação do Operador.  Para auditoria e relatórios de dados precisos, sincronize o horário na máquina do agente usando o Network Time Protocol (NTP) ou o Simple Network Time Protocol (SNTP). 


| Outro | Se você estiver executando o OpenShift 4.6 ou superior, você deve seguir olink:task_config_telegraf_agent_k8s.html#openshift-instructions["Instruções do OpenShift"] além de garantir que esses pré-requisitos sejam atendidos. 


| Token de API | Se você estiver reimplantando o Operador (ou seja, atualizando-o ou substituindo-o), não há necessidade de criar um novo token de API; você pode reutilizar o token anterior. 
|===


== Coisas importantes a serem observadas antes de começar

Se você estiver correndo com um<<configuring-proxy-support,procuração>> , tem um<<using-a-custom-or-private-docker-repository,repositório personalizado>> , ou estão usando<<openshift-instructions,OpenShift>> , leia atentamente as seções a seguir.

Leia também sobre<<permissões,Permissões>> .



=== Configurando o suporte a proxy

Há dois lugares onde você pode usar um proxy no seu locatário para instalar o NetApp Kubernetes Monitoring Operator.  Esses podem ser os mesmos sistemas proxy ou sistemas separados:

* Proxy necessário durante a execução do snippet de código de instalação (usando "curl") para conectar o sistema onde o snippet é executado ao seu ambiente do Data Infrastructure Insights
* Proxy necessário para o cluster Kubernetes de destino se comunicar com seu ambiente do Data Infrastructure Insights


Se você usar um proxy para um ou ambos, para instalar o NetApp Kubernetes Operating Monitor, primeiro você deve garantir que seu proxy esteja configurado para permitir uma boa comunicação com seu ambiente do Data Infrastructure Insights .  Por exemplo, a partir dos servidores/VMs dos quais você deseja instalar o Operator, você precisa conseguir acessar o Data Infrastructure Insights e conseguir baixar binários do Data Infrastructure Insights.

Para o proxy usado para instalar o NetApp Kubernetes Operating Monitor, antes de instalar o Operator, defina as variáveis ​​de ambiente _http_proxy/https_proxy_.  Para alguns ambientes de proxy, talvez você também precise definir a variável de ambiente _no_proxy_.

Para definir a(s) variável(is), execute as seguintes etapas no seu sistema *antes* de instalar o NetApp Kubernetes Monitoring Operator:

. Defina as variáveis de ambiente _https_proxy_ e/ou _http_proxy_ para o usuário atual:
+
.. Se o proxy que está sendo configurado não tiver autenticação (nome de usuário/senha), execute o seguinte comando:
+
 export https_proxy=<proxy_server>:<proxy_port>
.. Se o proxy que está sendo configurado tiver autenticação (nome de usuário/senha), execute este comando:
+
 export http_proxy=<proxy_username>:<proxy_password>@<proxy_server>:<proxy_port>




Para que o proxy usado no seu cluster Kubernetes se comunique com seu ambiente do Data Infrastructure Insights , instale o NetApp Kubernetes Monitoring Operator depois de ler todas estas instruções.

Configure a seção proxy do AgentConfiguration em operator-config.yaml antes de implantar o NetApp Kubernetes Monitoring Operator.

[listing]
----
agent:
  ...
  proxy:
    server: <server for proxy>
    port: <port for proxy>
    username: <username for proxy>
    password: <password for proxy>

    # In the noproxy section, enter a comma-separated list of
    # IP addresses and/or resolvable hostnames that should bypass
    # the proxy
    noproxy: <comma separated list>

    isTelegrafProxyEnabled: true
    isFluentbitProxyEnabled: <true or false> # true if Events Log enabled
    isCollectorsProxyEnabled: <true or false> # true if Network Performance and Map enabled
    isAuProxyEnabled: <true or false> # true if AU enabled
  ...
...
----


=== Usando um repositório docker personalizado ou privado

Por padrão, o NetApp Kubernetes Monitoring Operator extrairá imagens de contêiner do repositório do Data Infrastructure Insights .  Se você tiver um cluster Kubernetes usado como destino para monitoramento e esse cluster estiver configurado para extrair apenas imagens de contêiner de um repositório Docker personalizado ou privado ou de um registro de contêiner, você deverá configurar o acesso aos contêineres necessários para o NetApp Kubernetes Monitoring Operator.

Execute o “Image Pull Snippet” do bloco de instalação do NetApp Monitoring Operator.  Este comando fará login no repositório do Data Infrastructure Insights , extrairá todas as dependências de imagem do operador e sairá do repositório do Data Infrastructure Insights .  Quando solicitado, digite a senha temporária do repositório fornecida.  Este comando baixa todas as imagens usadas pelo operador, inclusive para recursos opcionais.  Veja abaixo para quais recursos essas imagens são usadas.

Funcionalidade do Operador Principal e Monitoramento do Kubernetes

* monitoramento netapp
* kube-rbac-proxy
* métricas de estado do kube
* telégrafo
* distroless-usuário-root


Registro de eventos

* fluente-bit
* exportador de eventos do kubernetes


Desempenho e Mapa da Rede

* observador ci-net


Envie a imagem do Docker do operador para seu repositório Docker privado/local/empresarial de acordo com suas políticas corporativas.  Certifique-se de que as tags de imagem e os caminhos de diretório para essas imagens no seu repositório sejam consistentes com aqueles no repositório do Data Infrastructure Insights .

Edite a implantação do operador de monitoramento em operator-deployment.yaml e modifique todas as referências de imagem para usar seu repositório privado do Docker.

....
image: <docker repo of the enterprise/corp docker repo>/kube-rbac-proxy:<kube-rbac-proxy version>
image: <docker repo of the enterprise/corp docker repo>/netapp-monitoring:<version>
....
Edite o AgentConfiguration em operator-config.yaml para refletir o novo local do repositório do Docker.  Crie um novo imagePullSecret para seu repositório privado. Para mais detalhes, consulte _https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/_

[listing]
----
agent:
  ...
  # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
  # Please see documentation for link:task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository[using a custom or private docker repository].
  dockerRepo: your.docker.repo/long/path/to/test
  # Optional: A docker image pull secret that maybe needed for your private docker registry
  dockerImagePullSecret: docker-secret-name
----


=== Instruções do OpenShift

Se você estiver executando o OpenShift 4.6 ou superior, deverá editar o AgentConfiguration em _operator-config.yaml_ para habilitar a configuração _runPrivileged_:

....
# Set runPrivileged to true SELinux is enabled on your kubernetes nodes
runPrivileged: true
....
O Openshift pode implementar um nível adicional de segurança que pode bloquear o acesso a alguns componentes do Kubernetes.



=== Permissões

Se o cluster que você está monitorando contiver Recursos Personalizados que não tenham um ClusterRole quelink:https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles["agregados para visualizar"] , você precisará conceder manualmente ao operador acesso a esses recursos para monitorá-los com Logs de Eventos.

. Edite _operator-additional-permissions.yaml_ antes de instalar ou, após a instalação, edite o recurso _ClusterRole/<namespace>-additional-permissions_
. Crie uma nova regra para os apiGroups e recursos desejados com os verbos ["obter", "observar", "listar"].  Veja \ https://kubernetes.io/docs/reference/access-authn-authz/rbac/
. Aplique suas alterações ao cluster

