---
sidebar: sidebar 
permalink: reporting_querying_database.html 
summary: Use as APIs do Data Infrastructure Insights para consultar o banco de dados de relatórios diretamente. 
keywords: reporting, cognos, data warehouse, dwh, API 
---
= Acesse o banco de dados de relatórios via API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A poderosa API do Data Infrastructure Insights permite que os usuários consultem o banco de dados de relatórios do Data Infrastructure Insights diretamente, sem passar pelo ambiente de relatórios do Cognos.


NOTE: Esta documentação se refere ao recurso de relatórios do Data Infrastructure Insights , que está disponível no Data Infrastructure Insights Premium Edition.



== Odata

A API de relatórios do Data Infrastructure Insights segue olink:https://www.odata.org/["OData v4"] (Open Data Protocol) padrão para consulta ao banco de dados de relatórios.  Para mais informações ou para saber mais, confiralink:https://www.odata.org/getting-started/basic-tutorial/["este tutorial"] no OData.

Todas as solicitações começarão com a URL _\https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata_



== Gerando uma APIKey

Leia mais sobrelink:API_Overview.html["APIs de Data Infrastructure Insights"] .

Para gerar uma chave de API, faça o seguinte:

* Efetue login no seu ambiente do Data Infrastructure Insights e selecione *Admin > Acesso à API*.
* Clique em “+ Token de acesso à API”.
* Insira um nome e uma descrição.
* Para o tipo, escolha _Data Warehouse_.
* Defina as permissões como Leitura/Gravação.
* Defina uma data de expiração desejada.
* Clique em “Salvar”, então *copie a chave e salve-a* em algum lugar seguro.  Você não poderá acessar a chave completa mais tarde.


As chaves de API são boas para<<synchronous-or-asynchronous,_Sincronizado_ ou _Assíncrono_>> .



== Consulta direta de tabelas

Com a chave de API em vigor, agora é possível fazer consultas diretas ao banco de dados de relatórios.  URLs longas podem ser simplificadas para \https://.../odata/ para fins de exibição, em vez do completo \https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata/

Tente consultas simples como

* \https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_custom
* \https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory
* \https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/storage
* \https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/disk
* \https://.../odata/dwh_custom/consultas_personalizadas




== Exemplos de API REST

A URL para todas as chamadas é _\https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata_.

* GET /{schema}/** - Recupera dados do banco de dados de relatórios.


Formato: _\https://< URL do Data Infrastructure Insights >/rest/v1/dwh-management/odata/<nome_do_esquema>/<consulta>_

Exemplo:

 https://<domain>/rest/v1/dwh-management/odata/dwh_inventory/fabric?$count=true&$orderby=name
Resultado:

....
{
   "@odata.context": "$metadata#fabric",
   "@odata.count": 2,
   "value": [
       {
           "id": 851,
           "identifier": "10:00:50:EB:1A:40:3B:44",
           "wwn": "10:00:50:EB:1A:40:3B:44",
           "name": "10:00:50:EB:1A:40:3B:44",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941716"
       },
       {
           "id": 852,
           "identifier": "10:00:50:EB:1A:40:44:0C",
           "wwn": "10:00:50:EB:1A:40:44:0C",
           "name": "10:00:50:EB:1A:40:44:0C",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941836"
        }
    ]
}
....


== Dicas úteis

Tenha em mente o seguinte ao trabalhar com consultas da API de relatórios.

* A carga útil da consulta deve ser uma string JSON válida
* A carga útil da consulta deve estar contida em uma única linha
* Aspas duplas devem ser escapadas, ou seja, \"
* As guias são suportadas como \t
* Evite comentários
* Nomes de tabela em minúsculas são suportados


Adicionalmente:

* 2 Cabeçalhos são necessários:
+
** Nome “X-CloudInsights-ApiKey”
** Valor do Atributo “<apikey>”




Sua chave de API será específica para seu ambiente do Data Infrastructure Insights .



== Síncrono ou assíncrono?

Por padrão, um comando de API operará no modo _síncrono_, o que significa que você envia a solicitação e a resposta é retornada imediatamente.  No entanto, às vezes, uma consulta pode levar muito tempo para ser executada, o que pode levar ao tempo limite da solicitação.  Para contornar isso, você pode executar uma solicitação _de forma assíncrona_.  No modo assíncrono, a solicitação retornará uma URL por meio da qual a execução poderá ser monitorada.  A URL retornará o resultado quando estiver pronta.

Para executar uma consulta no modo assíncrono, adicione o cabeçalho `*Prefer: respond-async*` ao pedido.  Após a execução bem-sucedida, a resposta conterá os seguintes cabeçalhos:

....
Status Code: 202 (which means ACCEPTED)
preference-applied: respond-async
location: https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>
....
Consultar a URL do local retornará os mesmos cabeçalhos se a resposta ainda não estiver pronta ou retornará com o status 200 se a resposta estiver pronta.  O conteúdo da resposta será do tipo texto e conterá o status http da consulta original e alguns metadados, seguidos pelos resultados da consulta original.

....
HTTP/1.1 200 OK
 OData-Version: 4.0
 Content-Type: application/json;odata.metadata=minimal
 oDataResponseSizeCounted: true

 { <JSON_RESPONSE> }
....
Para ver uma lista de todas as consultas assíncronas e quais delas estão prontas, use o seguinte comando:

 GET https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncList
A resposta tem o seguinte formato:

....
{
   "queries" : [
       {
           "Query": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/heavy_left_join3?$count=true",
           "Location": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>",
           "Finished": false
       }
   ]
}
....