---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Relatórios predefinidos e personalizados dos seus dados com o Data Infrastructure Insights. 
keywords: reporting, cognos, data warehouse, dwh 
---
= Visão geral dos relatórios de Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O relatório do Data Infrastructure Insights é uma ferramenta de inteligência empresarial que permite visualizar relatórios predefinidos ou criar relatórios personalizados.


NOTE: O recurso de relatórios está disponível no Data Infrastructure Insightslink:concept_subscribing_to_cloud_insights.html["Edição Premium"] .  A disponibilidade do recurso de relatórios está sujeita a um requisito de área mínima. link:https://www.netapp.com/forms/cloud-insights-contact-us/["Entre em contato com seu representante de vendas da NetApp"] para mais informações.

Com os relatórios do Data Infrastructure Insights, você pode executar as seguintes tarefas:

* Execute um relatório predefinido
* Criar um relatório personalizado
* Personalize o formato e o método de entrega de um relatório
* Agende relatórios para execução automática
* Relatórios por e-mail
* Use cores para representar limites em dados


O Data Infrastructure Insights Reporting pode gerar relatórios personalizados para áreas como chargeback, análise de consumo e previsão, além de ajudar a responder perguntas como as seguintes:

* Que estoque eu tenho?
* Onde está meu inventário?
* Quem está usando nossos ativos?
* Qual é o estorno para armazenamento alocado para uma unidade de negócios?
* Quanto tempo até eu precisar adquirir capacidade de armazenamento adicional?
* As unidades de negócios estão alinhadas aos níveis de armazenamento adequados?
* Como a alocação de armazenamento muda ao longo de um mês, trimestre ou ano?




== Acessando relatórios de Data Infrastructure Insights

Você pode acessar o Relatório do Data Infrastructure Insights clicando no link *Relatórios* no menu.

Você será levado para a interface de relatórios.  O Data Infrastructure Insights usa o IBM Cognos Analytics para seu mecanismo de relatórios.



== O que é ETL?

Ao trabalhar com relatórios, você ouvirá os termos "Data Warehouse" e "ETL".  ETL significa "Extrair, Transformar e Carregar".  O processo ETL recupera dados coletados no Data Infrastructure Insights e os transforma em um formato para uso em Relatórios.  "Data Warehouse" refere-se aos dados coletados disponíveis para Relatórios.

O processo ETL inclui estes processos individuais:

* *Extrair*: Obtém dados do Data Infrastructure Insights.
* *Transformar*: aplica regras ou funções de lógica de negócios aos dados conforme eles são extraídos do Data Infrastructure Insights.
* *Carregar*: salva os dados transformados no data warehouse para uso em relatórios.

