---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 'Usando ferramentas de criação de relatórios para criar relatórios personalizados ("ad-hoc")' 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= Criação de relatórios personalizados
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Você pode usar as ferramentas de criação de relatórios para criar relatórios personalizados.  Depois de criar relatórios, você pode salvá-los e executá-los regularmente.  Os resultados dos relatórios podem ser enviados automaticamente por e-mail para você e outras pessoas.


NOTE: O recurso de relatórios está disponível no Data Infrastructure Insightslink:concept_subscribing_to_cloud_insights.html["Edição Premium"] .

Os exemplos nesta seção mostram o seguinte processo, que pode ser usado para qualquer um dos modelos de dados do Data Infrastructure Insights Reporting:

* Identificar uma questão a ser respondida com um relatório
* Determinar os dados necessários para apoiar os resultados
* Selecionando elementos de dados para o relatório


Antes de criar seu relatório personalizado, você precisa concluir algumas tarefas pré-requisitos.  Se você não preenchê-los, os relatórios poderão ficar imprecisos ou incompletos.

Por exemplo, se você não concluir o processo de identificação do dispositivo, seus relatórios de capacidade não serão precisos.  Ou, se você não terminar de definir anotações (como níveis, unidades de negócios e data centers), seus relatórios personalizados podem não reportar dados com precisão em seu domínio ou podem mostrar "N/D" para alguns pontos de dados.

Antes de criar seus relatórios, conclua as seguintes tarefas:

* Configurar tudolink:task_configure_data_collectors.html["coletores de dados"] apropriadamente.
* Insira anotações (como camadas, data centers e unidades de negócios) em dispositivos e recursos no seu locatário.  É benéfico ter anotações estáveis ​​antes de gerar relatórios, porque o Data Infrastructure Insights Reporting coleta informações históricas.




== Processo de Criação de Relatórios

O processo de criação de relatórios personalizados (também chamados de "ad hoc") envolve várias tarefas:

* Planeje os resultados do seu relatório.
* Identifique dados para apoiar seus resultados.
* Selecione o modelo de dados (por exemplo, modelo de dados de estorno, modelo de dados de inventário e assim por diante) que contém os dados.
* Selecione elementos de dados para o relatório.
* Opcionalmente, formate, classifique e filtre os resultados do relatório.




=== Planejando os resultados do seu relatório personalizado

Antes de abrir as ferramentas de criação de relatórios, talvez você queira planejar os resultados desejados do relatório.  Com ferramentas de criação de relatórios, você pode criar relatórios facilmente e pode não precisar de muito planejamento; no entanto, é uma boa ideia obter uma ideia do solicitante do relatório sobre os requisitos do relatório.

* Identifique a pergunta exata que você quer responder. Por exemplo:
+
** Quanta capacidade ainda me resta?
** Quais são os custos de estorno por unidade de negócios?
** Qual é a capacidade por nível para garantir que as unidades de negócios estejam alinhadas no nível adequado de armazenamento?
** Como posso prever as necessidades de energia e refrigeração?  (Adicione metadados personalizados adicionando anotações aos recursos.)


* Identifique os elementos de dados necessários para dar suporte à resposta.
* Identifique as relações entre os dados que você deseja ver na resposta.  Não inclua relações ilógicas em sua pergunta, por exemplo, “Quero ver as portas relacionadas à capacidade”.
* Identifique quaisquer cálculos necessários nos dados.
* Determine quais tipos de filtragem são necessários para limitar os resultados.
* Determine se você precisa usar dados atuais ou históricos.
* Determine se você precisa definir privilégios de acesso em relatórios para limitar os dados a públicos específicos.
* Identifique como o relatório será distribuído.  Por exemplo, ele deve ser enviado por e-mail em um cronograma definido ou incluído na área de pasta de conteúdo da equipe?
* Determine quem manterá o relatório.  Isso pode afetar a complexidade do design.
* Crie um modelo do relatório.




=== Dicas para criar relatórios

Várias dicas podem ser úteis ao criar relatórios.

* Determine se você precisa usar dados atuais ou históricos.
+
A maioria dos relatórios precisa apenas relatar os dados mais recentes disponíveis no Data Infrastructure Insights.

* O Data Infrastructure Insights Reporting fornece informações históricas sobre capacidade e desempenho, mas não sobre inventário.
* Todos veem todos os dados; no entanto, talvez seja necessário limitar os dados a públicos específicos.
+
Para segmentar as informações para diferentes usuários, você pode criar relatórios e definir permissões de acesso para eles.





== Modelos de dados de relatórios

O Data Infrastructure Insights inclui vários modelos de dados dos quais você pode selecionar relatórios predefinidos ou criar seu próprio relatório personalizado.

Cada modelo de dados contém um data mart simples e um data mart avançado:

* O data mart simples fornece acesso rápido aos elementos de dados mais comumente usados e inclui apenas o último instantâneo dos dados do Data Warehouse; não inclui dados históricos.
* O data mart avançado fornece todos os valores e detalhes disponíveis no data mart simples e inclui acesso a valores de dados históricos.




=== Modelos de dados de capacidade

Permite que você responda a perguntas sobre capacidade de armazenamento, utilização do sistema de arquivos, capacidade de volume interno, capacidade de porta, capacidade de qtree e capacidade de máquina virtual (VM).  O modelo de dados de capacidade é um contêiner para vários modelos de dados de capacidade.  Você pode criar relatórios respondendo a vários tipos de perguntas usando este modelo de dados:



==== Modelo de dados de capacidade de armazenamento e pool de armazenamento

Permite que você responda a perguntas sobre o planejamento de recursos de capacidade de armazenamento, incluindo armazenamento e pools de armazenamento, e inclui dados de pools de armazenamento físicos e virtuais.  Este modelo de dados simples pode ajudar você a responder perguntas relacionadas à capacidade no local e ao uso da capacidade de pools de armazenamento por nível e data center ao longo do tempo.  Se você é novo em relatórios de capacidade, deve começar com este modelo de dados porque é um modelo de dados mais simples e direcionado.  Você pode responder perguntas semelhantes às seguintes usando este modelo de dados:

* Qual é a data prevista para atingir o limite de capacidade de 80% do meu armazenamento físico?
* Qual é a capacidade de armazenamento físico em um array para uma determinada camada?
* Qual é a minha capacidade de armazenamento por fabricante e família, bem como por data center?
* Qual é a tendência de utilização de armazenamento em um array para todas as camadas?
* Quais são meus 10 principais sistemas de armazenamento com maior utilização?
* Qual é a tendência de utilização de armazenamento dos pools de armazenamento?
* Quanta capacidade já está alocada?
* Qual capacidade está disponível para alocação?




==== Modelo de dados de utilização do sistema de arquivos

Este modelo de dados fornece visibilidade sobre a utilização da capacidade pelos hosts no nível do sistema de arquivos.  Os administradores podem determinar a capacidade alocada e usada por sistema de arquivos, determinar o tipo de sistema de arquivos e identificar estatísticas de tendências por tipo de sistema de arquivos.  Você pode responder às seguintes perguntas usando este modelo de dados:

* Qual é o tamanho do sistema de arquivos?
* Onde os dados são mantidos e como eles são acessados, por exemplo, localmente ou SAN?
* Quais são as tendências históricas para a capacidade do sistema de arquivos?  Então, com base nisso, o que podemos antecipar para as necessidades futuras?




==== Modelo de dados de capacidade de volume interno

Permite que você responda a perguntas sobre capacidade de volume interno usada, capacidade alocada e uso de capacidade ao longo do tempo:

* Quais volumes internos têm uma utilização maior que um limite predefinido?
* Quais volumes internos correm o risco de ficar sem capacidade com base em uma tendência?  8 Qual é a capacidade utilizada versus a capacidade alocada em nossos volumes internos?




==== Modelo de dados de capacidade portuária

Permite que você responda a perguntas sobre conectividade da porta do switch, status da porta e velocidade da porta ao longo do tempo.  Você pode responder a perguntas semelhantes às seguintes para ajudar a planejar a compra de novos switches: Como posso criar uma previsão de consumo de porta que preveja a disponibilidade de recursos (porta) (de acordo com o data center, o fornecedor do switch e a velocidade da porta)?

* Quais portas provavelmente ficarão sem capacidade, fornecendo velocidade de dados, data center, fornecedor e número de portas de host e armazenamento?
* Quais são as tendências de capacidade da porta do switch ao longo do tempo?
* Quais são as velocidades das portas?
* Que tipo de capacidade portuária é necessária e qual organização está prestes a ficar sem um determinado tipo de porta ou fornecedor?
* Qual é o momento ideal para comprar essa capacidade e disponibilizá-la?




==== Modelo de dados de capacidade Qtree

Permite que você monitore a utilização do qtree (com dados como capacidade utilizada versus capacidade alocada) ao longo do tempo.  Você pode visualizar as informações por diferentes dimensões — por exemplo, por entidade comercial, aplicativo, nível e nível de serviço.  Você pode responder às seguintes perguntas usando este modelo de dados:

* Qual é a capacidade utilizada para qtrees em comparação com os limites definidos por aplicativo ou entidade comercial?
* Quais são as tendências da nossa capacidade utilizada e livre para que possamos fazer o planejamento da capacidade?
* Quais entidades empresariais estão usando mais capacidade?
* Quais aplicativos consomem mais capacidade?




==== Modelo de dados de capacidade de VM

Permite que você relate seu ambiente virtual e seu uso de capacidade.  Este modelo de dados permite que você relate alterações no uso da capacidade ao longo do tempo para VMs e armazenamentos de dados.  O modelo de dados também fornece provisionamento fino e dados de chargeback de máquina virtual.

* Como posso determinar o chargeback de capacidade com base na capacidade provisionada para VMs e armazenamentos de dados?
* Qual capacidade não é usada pelas VMs e qual parte não utilizada está livre, órfã ou de outra natureza?
* O que precisamos comprar com base nas tendências de consumo?
* Quais são as economias de eficiência de armazenamento alcançadas ao usar tecnologias de provisionamento fino de armazenamento e desduplicação?


As capacidades no modelo de dados de capacidade da VM são obtidas de discos virtuais (VMDKs).  Isso significa que o tamanho provisionado de uma VM usando o modelo de dados de capacidade da VM é o tamanho de seus discos virtuais.  Isso é diferente da capacidade provisionada na exibição Máquinas Virtuais no Data Infrastructure Insights, que mostra o tamanho provisionado para a própria VM.



==== Modelo de dados de capacidade de volume

Permite que você analise todos os aspectos dos volumes em seu locatário e organize os dados por fornecedor, modelo, camada, nível de serviço e data center.

Você pode visualizar a capacidade relacionada a volumes órfãos, volumes não utilizados e volumes de proteção (usados para replicação).  Você também pode ver diferentes tecnologias de volume (iSCSI ou FC) e comparar volumes virtuais com volumes não virtuais para problemas de virtualização de array.

Você pode responder perguntas semelhantes às seguintes com este modelo de dados:

* Quais volumes têm uma utilização maior que um limite predefinido?
* Qual é a tendência em meu data center para capacidade de volume órfão?
* Quanta capacidade do meu data center é virtualizada ou provisionada finamente?
* Quanta capacidade do meu data center deve ser reservada para replicação?




=== Modelo de dados de estorno

Permite que você responda a perguntas sobre capacidade usada e capacidade alocada em recursos de armazenamento (volumes, volumes internos e qtrees).  Este modelo de dados fornece informações de responsabilidade e estorno de capacidade de armazenamento por hosts, aplicativos e entidades comerciais, e inclui dados atuais e históricos.  Os dados do relatório podem ser categorizados por nível de serviço e nível de armazenamento.

Você pode usar esse modelo de dados para gerar relatórios de chargeback, descobrindo a quantidade de capacidade usada por uma entidade comercial.  Este modelo de dados permite que você crie relatórios unificados de vários protocolos (incluindo NAS, SAN, FC e iSCSI).

* Para armazenamento sem volumes internos, os relatórios de estorno mostram o estorno por volumes.
* Para armazenamento com volumes internos:
+
** Se entidades comerciais forem atribuídas a volumes, os relatórios de estorno mostrarão o estorno por volumes.
** Se entidades comerciais não forem atribuídas a volumes, mas sim a qtrees, os relatórios de chargeback mostrarão o chargeback por qtrees.
** Se entidades comerciais não forem atribuídas a volumes e nem a qtrees, os relatórios de chargeback mostrarão o volume interno.
** A decisão de mostrar o chargeback por volume, qtree ou volume interno é feita para cada volume interno, portanto, é possível que diferentes volumes internos no mesmo pool de armazenamento mostrem o chargeback em níveis diferentes.




Os fatos de capacidade são eliminados após um intervalo de tempo padrão.  Para mais detalhes, consulte Processos de Data Warehouse.

Relatórios que usam o modelo de dados de Chargeback podem exibir valores diferentes dos relatórios que usam o modelo de dados de Capacidade de Armazenamento.

* Para matrizes de armazenamento que não são sistemas de armazenamento NetApp , os dados de ambos os modelos de dados são os mesmos.
* Para sistemas de armazenamento NetApp e Celerra, o modelo de dados Chargeback usa uma única camada (de volumes, volumes internos ou qtrees) para basear suas cobranças, enquanto o modelo de dados Storage Capacity usa várias camadas (de volumes e volumes internos) para basear suas cobranças.




=== Modelo de dados de inventário

Permite que você responda a perguntas sobre recursos de inventário, incluindo hosts, sistemas de armazenamento, switches, discos, fitas, qtrees, cotas, máquinas virtuais e servidores e dispositivos genéricos.  O modelo de dados de inventário inclui vários submercados que permitem visualizar informações sobre replicações, caminhos FC, caminhos iSCSI, caminhos NFS e violações.  O modelo de dados de inventário não inclui dados históricos.  Perguntas que você pode responder com esses dados

* Quais bens eu tenho e onde eles estão?
* Quem está usando os ativos?
* Que tipos de dispositivos eu tenho e quais são os componentes desses dispositivos?
* Quantos hosts por sistema operacional eu tenho e quantas portas existem nesses hosts?
* Quais matrizes de armazenamento por fornecedor existem em cada data center?
* Quantos switches por fornecedor eu tenho em cada data center?
* Quantos portos não são licenciados?
* Quais fitas de fornecedores estamos usando e quantas portas existem em cada fita? Todos os dispositivos genéricos estão identificados antes de começarmos a trabalhar nos relatórios?
* Quais são os caminhos entre hosts e volumes de armazenamento ou fitas?
* Quais são os caminhos entre dispositivos genéricos e volumes de armazenamento ou fitas?
* Quantas violações de cada tipo tenho por data center?
* Para cada volume replicado, quais são os volumes de origem e de destino?
* Há alguma incompatibilidade de firmware ou incompatibilidade de velocidade de porta entre os HBAs host Fibre Channel e os switches?




=== Modelo de dados de desempenho

Permite que você responda a perguntas sobre desempenho de volumes, volumes de aplicativos, volumes internos, switches, aplicativos, VMs, VMDKs, ESX versus VM, hosts e nós de aplicativos.  Muitos deles relatam dados _por hora_, dados _diários_ ou ambos.  Usando esse modelo de dados, você pode criar relatórios que respondem a vários tipos de perguntas de gerenciamento de desempenho:

* Quais volumes ou volumes internos não foram utilizados ou acessados durante um período específico?
* Podemos identificar alguma possível configuração incorreta de armazenamento para um aplicativo (não utilizado)?
* Qual era o padrão geral de comportamento de acesso para um aplicativo?
* Os volumes em camadas são atribuídos adequadamente para uma determinada aplicação?
* Poderíamos usar armazenamento mais barato para um aplicativo em execução no momento sem afetar seu desempenho?
* Quais são os aplicativos que estão produzindo mais acessos ao armazenamento configurado atualmente?


Ao usar as tabelas de desempenho do switch, você pode obter as seguintes informações:

* O tráfego do meu host através das portas conectadas é balanceado?
* Quais switches ou portas estão apresentando um alto número de erros?
* Quais são os switches mais utilizados com base no desempenho da porta?
* Quais são os switches subutilizados com base no desempenho da porta?
* Qual é a tendência de taxa de transferência do host com base no desempenho da porta?
* Qual é a utilização de desempenho nos últimos X dias para um host, sistema de armazenamento, fita ou switch especificado?
* Quais dispositivos estão produzindo tráfego em um switch específico (por exemplo, quais dispositivos são responsáveis pelo uso de um switch altamente utilizado)?
* Qual é a taxa de transferência de uma unidade de negócios específica em nosso ambiente?


Ao usar as tabelas de desempenho do disco, você pode obter as seguintes informações:

* Qual é a taxa de transferência de um pool de armazenamento especificado com base nos dados de desempenho do disco?
* Qual é o pool de armazenamento mais utilizado?
* Qual é a utilização média do disco para um armazenamento específico?
* Qual é a tendência de uso de um sistema de armazenamento ou pool de armazenamento com base em dados de desempenho de disco?
* Qual é a tendência de uso do disco para um pool de armazenamento específico?


Ao usar tabelas de desempenho de VM e VMDK, você pode obter as seguintes informações:

* Meu ambiente virtual está funcionando perfeitamente?
* Quais VMDKs estão relatando as maiores cargas de trabalho?
* Como posso usar o desempenho relatado de VMDs mapeados para diferentes armazenamentos de dados para tomar decisões sobre reclassificação?


O modelo de dados de desempenho inclui informações que ajudam a determinar a adequação de camadas, configurações incorretas de armazenamento para aplicativos e horários do último acesso de volumes e volumes internos.  Este modelo de dados fornece dados como tempos de resposta, IOPs, taxa de transferência, número de gravações pendentes e status acessado.



=== Modelo de dados de eficiência de armazenamento

Permite que você acompanhe a pontuação e o potencial de eficiência de armazenamento ao longo do tempo.  Este modelo de dados armazena medições não apenas da capacidade provisionada, mas também da quantidade usada ou consumida (a medição física).  Por exemplo, quando o provisionamento fino está habilitado, o Data Infrastructure Insights indica quanta capacidade é retirada do dispositivo.  Você também pode usar este modelo para determinar a eficiência quando a desduplicação estiver habilitada.  Você pode responder a várias perguntas usando o data mart de Eficiência de Armazenamento:

* Qual é a nossa economia em eficiência de armazenamento como resultado da implementação de tecnologias de provisionamento fino e desduplicação?
* Quais são as economias de armazenamento nos data centers?
* Com base nas tendências históricas de capacidade, quando precisamos comprar armazenamento adicional?
* Qual seria o ganho de capacidade se habilitássemos tecnologias como provisionamento fino e desduplicação?
* Em relação à capacidade de armazenamento, estou em risco agora?




=== Tabelas de fatos e dimensões do modelo de dados

Cada modelo de dados inclui tabelas de fatos e dimensões.

* Tabelas de fatos: contêm dados que são medidos, por exemplo, quantidade, capacidade bruta e utilizável.  Contém chaves estrangeiras para tabelas de dimensões.
* Tabelas de dimensões: contêm informações descritivas sobre fatos, por exemplo, data center e unidades de negócios.  Uma dimensão é uma estrutura, geralmente composta de hierarquias, que categoriza dados.  Atributos dimensionais ajudam a descrever os valores dimensionais.


Usando atributos de dimensão diferentes ou múltiplos (vistos como colunas nos relatórios), você constrói relatórios que acessam dados para cada dimensão descrita no modelo de dados.



=== Cores usadas em elementos do modelo de dados

As cores nos elementos do modelo de dados têm indicações diferentes.

* Ativos amarelos: representam medições.
* Ativos não amarelos: representam atributos.  Esses valores não são agregados.




=== Usando vários modelos de dados em um relatório

Normalmente, você usa um modelo de dados por relatório.  No entanto, você pode escrever um relatório que combine dados de vários modelos de dados.

Para escrever um relatório que combine dados de vários modelos de dados, escolha um dos modelos de dados para usar como base e, em seguida, escreva consultas SQL para acessar os dados dos data marts adicionais.  Você pode usar o recurso SQL Join para combinar os dados de diferentes consultas em uma única consulta que pode ser usada para escrever o relatório.

Por exemplo, digamos que você queira saber a capacidade atual de cada matriz de armazenamento e queira capturar anotações personalizadas nas matrizes.  Você pode criar o relatório usando o modelo de dados Capacidade de Armazenamento.  Você pode usar os elementos das tabelas de capacidade atual e dimensão e adicionar uma consulta SQL separada para acessar as informações de anotações no modelo de dados de inventário.  Por fim, você pode combinar os dados vinculando os dados de armazenamento de inventário à tabela Dimensão de armazenamento usando o nome do armazenamento e os critérios de junção.
