---
sidebar: sidebar 
permalink: security_information_and_region.html 
summary: O Data Infrastructure Insights segue as melhores práticas de segurança durante todo o ciclo de vida do lançamento. 
keywords: security, risk, protection 
---
= Informação e Região
:hardbreaks:
:allow-uri-read: 


[role="lead"]
A NetApp leva a segurança das informações dos clientes muito a sério.  Veja como e onde o Data Infrastructure Insights armazena suas informações.



== Quais informações o Data Infrastructure Insights armazena?

O Data Infrastructure Insights armazena as seguintes informações:

* Dados de desempenho
+
Dados de desempenho são dados de séries temporais que fornecem informações sobre o desempenho do dispositivo/fonte monitorado.  Isso inclui, por exemplo, o número de E/S entregues por um sistema de armazenamento, a taxa de transferência de uma porta FibreChannel, o número de páginas entregues por um servidor web, o tempo de resposta de um banco de dados e muito mais.

* Dados de inventário
+
Os dados de inventário consistem em metadados que descrevem o dispositivo/fonte monitorado e como ele está configurado.  Isso inclui, por exemplo, versões de hardware e software instaladas, discos e LUNs em um sistema de armazenamento, núcleos de CPU, RAM e discos de uma máquina virtual, os tablespaces de um banco de dados, o número e o tipo de portas em um switch SAN, nomes de diretório/arquivo (se a Segurança de Carga de Trabalho de Armazenamento estiver habilitada), etc.

* Dados de configuração
+
Isso resume os dados de configuração fornecidos pelo cliente usados para gerenciar o inventário e as operações do cliente, por exemplo, nomes de host ou endereços IP dos dispositivos monitorados, intervalos de pesquisa, valores de tempo limite, etc.

* Segredos
+
Os segredos consistem nas credenciais usadas pela Data Infrastructure Insights Acquisition Unit para acessar dispositivos e serviços do cliente.  Essas credenciais são criptografadas usando criptografia assimétrica forte, e as chaves privadas são armazenadas apenas nas Unidades de Aquisição e nunca saem do ambiente do cliente.  Mesmo os SREs privilegiados do Data Infrastructure Insights não conseguem acessar segredos do cliente em texto simples devido a esse design.

* Dados Funcionais
+
Esses são dados gerados como resultado do fornecimento do Serviço de Dados em Nuvem pela NetApp , que informa a NetApp no ​​desenvolvimento, implantação, operações, manutenção e proteção do Serviço de Dados em Nuvem.  Dados Funcionais não contêm Informações do Cliente ou Informações Pessoais.

* Dados de acesso do usuário
+
Informações de autenticação e acesso que permitem que o NetApp Console se comunique com sites regionais do Data Infrastructure Insights , incluindo dados relacionados à autorização do usuário.

* Dados do diretório do usuário de segurança da carga de trabalho de armazenamento
+
Nos casos em que a funcionalidade de segurança de carga de trabalho estiver habilitada E o cliente optar por habilitar o coletor de diretório de usuários, o sistema armazenará nomes de exibição de usuários, endereços de e-mail corporativos e outras informações coletadas do Active Directory.




NOTE: Os dados do diretório do usuário referem-se às informações do diretório do usuário coletadas pelo coletor de dados do diretório do usuário do Workload Security, não aos dados sobre os próprios usuários do Data Infrastructure Insights/Workload Security.

*Nenhum dado pessoal explícito* é coletado de recursos de infraestrutura e serviços.  As informações coletadas consistem apenas em métricas de desempenho, informações de configuração e metadados de infraestrutura, assim como muitos provedores de telefonia residencial, incluindo o suporte automático da NetApp e o ActiveIQ.  No entanto, dependendo das convenções de nomenclatura do cliente, os dados de compartilhamentos, volumes, VMs, qtrees, aplicativos etc. podem conter informações de identificação pessoal.

Se a Segurança de Carga de Trabalho estiver habilitada, o sistema também analisará nomes de arquivos e diretórios em compartilhamentos SMB ou outros, que podem conter informações de identificação pessoal.  Quando os clientes ativam o Workload Security User Directory Collector (que essencialmente mapeia os SIDs do Windows para nomes de usuário por meio do Active Directory), o nome de exibição, o endereço de e-mail corporativo e quaisquer atributos adicionais selecionados serão coletados e armazenados pelo Data Infrastructure Insights.

Além disso, os logs de acesso ao Data Infrastructure Insights são mantidos e contêm os endereços IP e de e-mail dos usuários usados ​​para efetuar login no serviço.



== Onde minhas informações são armazenadas?

O Data Infrastructure Insights armazena informações de acordo com a região em que seu ambiente é criado.

As seguintes informações são armazenadas na região do host:

* Telemetria e informações de ativos/objetos, incluindo contadores e métricas de desempenho
* Informações da Unidade de Aquisição
* Dados funcionais
* Auditar informações sobre atividades do usuário dentro do Data Infrastructure Insights
* Informações do Active Directory sobre segurança de carga de trabalho
* Informações de auditoria de segurança de carga de trabalho


As informações a seguir residem nos Estados Unidos, independentemente da região que hospeda seu ambiente do Data Infrastructure Insights :

* Informações do site do ambiente (às vezes chamado de "locatário"), como proprietário do site/conta.
* Informações que permitem que o NetApp Console se comunique com sites regionais do Data Infrastructure Insights , incluindo qualquer coisa relacionada à autorização do usuário.
* Informações relacionadas à relação entre o usuário do Data Infrastructure Insights e o locatário.




=== Regiões anfitriãs

As regiões anfitriãs incluem:

* EUA: us-east-1
* EMEA: eu-central-1
* APAC: ap-sudeste-2




== Mais informações

Você pode ler mais sobre privacidade e segurança da NetApp nos seguintes links:

* link:https://www.netapp.com/us/company/trust-center/index.aspx["Centro de Confiança"]
* link:https://www.netapp.com/us/company/trust-center/privacy/data-location-cross-border-transfers.aspx["Transferências de dados transfronteiriças"]
* link:https://www.netapp.com/us/company/trust-center/privacy/bcr-binding-corporate-rules.aspx["Regras corporativas vinculativas"]
* link:https://www.netapp.com/us/company/trust-center/transparency/third-party-data-requests.aspx["Respondendo a solicitações de dados de terceiros"]
* link:https://www.netapp.com/us/company/trust-center/privacy/privacy-principles-security-safeguards.aspx["Princípios de privacidade da NetApp"]

