---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: Configurando o coletor de dados do VNX. 
---
= Configurando o coletor de dados unificado do Dell EMC VNX
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Para configuração, o coletor de dados Dell EMC VNX Unified (SSH) requer o endereço IP da Control Station e um nome de usuário e senha somente leitura.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário deste coletor de dados.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco 


| Pasta de disco | Grupo de Discos 


| Sistema de arquivos | Volume interno 


| Armazenar | Armazenar 


| Processador de armazenamento | Nó de armazenamento 


| Pool de armazenamento, grupo RAID | Pool de armazenamento 


| LUN | Volume 


| Movedor de dados | Controlador 


| Sistema de arquivos montado em um movimentador de dados | Compartilhamento de arquivos 


| Exportações CIFS e NFS | Compartilhar 


| Volume do disco | LUN de backend 
|===


== Requisitos

Você precisa do seguinte para configurar o coletor de dados VNX (SSH):

* Endereço IP do VNX e credenciais para a Celerra Control Station.
* Nome de usuário e senha somente leitura.
* O coletor de dados é capaz de executar comandos NaviCLI/NaviSecCLI no array de backend utilizando os cabeçotes NAS do DART OS




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do VNX | Endereço IP ou nome de domínio totalmente qualificado da VNX Control Station 


| Nome de usuário | Nome de usuário para a estação de controle VNX 


| Senha | Senha para a estação de controle VNX 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 40 minutos. 


| Intervalo de pesquisa de desempenho (seg). | Intervalo entre pesquisas de desempenho. O padrão é 300 segundos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
