---
sidebar: sidebar 
permalink: task_dc_redhat_openshift_virtualization.html 
keywords: data collector, Red Hat OpenShift Virtualization 
summary: Configurando o coletor de dados do Red Hat OpenShift Virtualization. 
---
= Coletor de dados de virtualização Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O coletor DII Red Hat OpenShift Virtualization tentará descobrir as cargas de trabalho de computação OSV em execução em um ambiente OpenShift Virtualization - este coletor não descobrirá todos os pods OpenShift. Este é um coletor baseado em API REST HTTPS. Recomenda-se criar um coletor por cluster OSV.

A abordagem de autenticação para este coletor é um token de autenticação vinculado a uma conta de serviço. Para criar tanto a conta de usuário quanto o token:

....
oc create sa acq-readonly-cluster-user -n default
oc adm policy add-cluster-role-to-user cluster-reader -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-user-binding
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-monitor-user-binding
....
Execute esses 3 comandos e fique atento a quaisquer erros.

Quando os comandos forem concluídos:

 oc sa new-token acq-readonly-cluster-user
Isso criará um token vinculado ao seu usuário.

Por fim, você também pode querer que seu administrador do OSV execute:

 oc cluster-info
Isso retornará o nome do host/endereço IP para gerenciamento. Cada coletor DII OSV precisa ser configurado para apontar para o endereço IP/nome do host para gerenciamento do OSV.



== Terminologia

Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para o ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco Virtual 


| Hospedar | Hospedar 


| Máquina Virtual | Máquina Virtual 


| Domínio de armazenamento | Armazenamento de dados 


| Unidade Lógica | LUN 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Endereço IP do servidor Red Hat OpenShift Virtualization na porta 443 via API REST
* Nome de usuário e senha somente leitura
* RHEV Versão 3.0+




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do servidor RHEV | Endereço IP do sistema de armazenamento 


| Nome de usuário | Nome de usuário com privilégios de administrador 


| Senha para a conta privilegiada de administrador | Senha 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta de comunicação HTTPS | Porta usada para comunicação HTTPS com RHOV 


| Intervalo de pesquisa de inventário (min) | O padrão é 20 minutos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
