---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Configurando o coletor de dados Rubrik CDM. 
---
= Coletor de Dados Rubrik CDM
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados Rubrik para adquirir dados de inventário e desempenho dos dispositivos de armazenamento Rubrik.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados Rubrik.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Conjunto | Armazenamento, Pool de Armazenamento 


| Nó | Nó de armazenamento 


| Disco | Disco 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos desta fonte de dados.



== Requisitos

Os seguintes itens são necessários para configurar este coletor de dados:

* A Unidade de Aquisição de Data Infrastructure Insights iniciará conexões na porta TCP 443 para o cluster Rubrik.  Um coletor por cluster.
* Endereço IP do cluster Rubrik.
* Nome de usuário e senha para o cluster.
* Endereço IP ou nome do host do cluster Rubrik.
* Para autenticação básica, um nome de usuário e uma senha para o cluster.  Se preferir usar a autenticação baseada em conta de serviço, você precisará de uma conta de serviço, um segredo e uma ID da organização
* Requisito de porta: HTTPS 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| IP | Endereço IP do cluster Rubrik 


| Nome de usuário / Conta de serviço | Nome de usuário para o cluster 


| Senha / Segredo | Senha para o cluster 


| ID da organização para a conta de serviço | Isso precisa ser a string completa, como "Organização:::nnnnnn-nnnn....." 
|===


== Configuração avançada

[cols="2*"]
|===
| Intervalo de pesquisa de inventário (min) | O padrão é 60 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 300 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Recebi uma mensagem informando que mais de um armazenamento foi criado. | Verifique se o cluster está configurado corretamente e se o coletor está apontando para um único cluster. 


| A enquete falha com 400 [Solicitação inválida].... ManagedId inválido.... | Você preencheu o campo ID da organização com um valor, mas o cluster Rubrik NÃO acredita que seja um ID da organização válido, apesar da mensagem de erro do Rubrik se referir a ele como "ManagedId". 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
