---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Configurando o coletor de dados do ECS. 
---
= Configurando o coletor de dados EMC ECS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados adquire dados de inventário e desempenho dos sistemas de armazenamento EMC ECS.  Para configuração, o coletor de dados requer um endereço IP ou nome de host do cluster ECS e um nome de usuário e senha.


NOTE: O Dell EMC ECS é medido a uma taxa de TB brutos diferente da taxa de unidade gerenciada.  Cada 40 TB de capacidade ECS não formatada é cobrado como 1link:concept_subscribing_to_cloud_insights.html#pricing["Unidade Gerenciada (UM)"] .



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados do ECS.  Para cada tipo de ativo adquirido, é mostrada a terminologia mais comum usada para esse ativo.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Conjunto | Armazenar 


| Inquilino | Pool de armazenamento 


| Balde | Volume interno 


| Disco | Disco 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Um endereço IP ou nome de host do cluster ECS
* Um nome de usuário e uma senha para o sistema ECS
* Porta 4443 (HTTPS).  Requer conectividade de saída para a porta TCP 4443 no sistema ECS.




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Host ECS | Endereço IP ou nome de domínio totalmente qualificado do sistema ECS 


| Porta do host ECS | Porta usada para comunicação com o host ECS 


| ID do usuário ECS | ID do usuário para ECS 


| Senha | Senha usada para ECS 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 360 minutos. 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Erro: Falha na autenticação do usuário. | Certifique-se de que suas credenciais para este dispositivo estejam corretas. 
|===


=== Desempenho

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Erro: Não foram coletados dados suficientes. | * Verifique o registro de data e hora da coleta no arquivo de log e modifique o intervalo de pesquisa de acordo. * Aguarde mais tempo. 


| Erro: O intervalo de pesquisa de desempenho é muito grande. | Verifique o registro de data e hora da coleta no arquivo de log ${logfile} e modifique o intervalo de pesquisa de acordo 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
