---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: Um resumo. 
---
= Gerenciando coletores de dados configurados
:hardbreaks:
:allow-uri-read: 


[role="lead"]
A página Coletores de dados instalados fornece acesso aos coletores de dados que foram configurados para o Data Infrastructure Insights.  Você pode usar esta página para modificar coletores de dados existentes.

.Passos
. No menu Data Infrastructure Insights , clique em *Observabilidade > Coletores*
+
A tela Coletores de dados disponíveis é exibida.

. Clique em *Coletores de Dados Instalados*
+
Uma lista de todos os coletores de dados instalados é exibida.  A lista fornece o nome do coletor, o status, o endereço IP que o coletor está acessando e quando os dados foram adquiridos pela última vez do dispositivo.  As ações que podem ser executadas nesta tela incluem:

+
** Controle de votação
** Alterar credenciais do coletor de dados
** Coletores de dados clones






== Controlando a pesquisa do coletor de dados

Depois de fazer uma alteração em um coletor de dados, você pode querer que ele faça uma pesquisa imediatamente para verificar suas alterações ou pode querer adiar a coleta de dados em um coletor de dados por um, três ou cinco dias enquanto trabalha em um problema.

.Passos
. No menu Data Infrastructure Insights , clique em *Observabilidade > Coletores*
. Clique em *Coletores de Dados Instalados*
. Selecione a caixa de seleção à esquerda do coletor de dados que você deseja alterar
. Clique em *Ações em massa* e selecione a ação de enquete que deseja realizar.
+
Ações em massa podem ser executadas simultaneamente em vários coletores de dados.  Selecione os coletores de dados e escolha a ação a ser executada no menu *Ação em massa*.





== Editando informações do coletor de dados

Você pode editar as informações de configuração do coletor de dados existentes.

.Para editar um único coletor de dados:
. No menu Data Infrastructure Insights , clique em *Observabilidade > Coletores* para abrir a lista de Coletores de Dados instalados.
. No menu de opções à direita do coletor de dados que você deseja modificar, clique em *Editar*.
+
A caixa de diálogo Editar Coletor é aberta.

. Insira as alterações e clique em *Testar configuração* para testar a nova configuração ou clique em *Salvar* para salvar a configuração.


Você também pode editar vários coletores de dados:

. Marque a caixa de seleção à esquerda de cada coletor de dados que você deseja alterar.
. Clique no botão *Ações em massa* e escolha *Editar* para abrir a caixa de diálogo Editar coletor de dados.
. Modifique os campos conforme acima.
+

NOTE: Os coletores de dados selecionados devem ser do mesmo fornecedor e modelo e residir na mesma Unidade de Aquisição.

+
Ao editar vários coletores de dados, o campo Nome do Coletor de Dados mostra “Misto” e não pode ser editado.  Outros campos, como nome de usuário e senha, são exibidos como “Misto” e podem ser editados.  Os campos que compartilham o mesmo valor nos coletores de dados selecionados mostram os valores atuais e podem ser editados.

+
Ao editar vários coletores de dados, o botão *Testar configuração* não está disponível.





== Clonagem de coletores de dados

Usando o recurso de clonagem, você pode adicionar rapidamente uma fonte de dados que tenha as mesmas credenciais e atributos de outra fonte de dados.  A clonagem permite que você configure facilmente várias instâncias do mesmo tipo de dispositivo.

.Passos
. No menu Data Infrastructure Insights , clique em *Observabilidade > Coletores*.
. Clique em *Coletores de dados instalados*.
. Clique na caixa de seleção à esquerda do coletor de dados que você deseja copiar.
. No menu de opções à direita do coletor de dados selecionado, clique em *Clonar*.
+
A caixa de diálogo Clonar Coletor de Dados é exibida.

. Insira novas informações nos campos obrigatórios.
. Clique em *Salvar*.


.Depois que você terminar
A operação de clonagem copia todos os outros atributos e configurações para criar o novo coletor de dados.



== Executando ações em massa em coletores de dados

Você pode editar simultaneamente algumas informações para vários coletores de dados.  Este recurso permite que você inicie uma enquete, adie a enquete e retome a enquete em vários coletores de dados.  Além disso, você pode excluir vários coletores de dados.

.Passos
. No menu Data Infrastructure Insights , clique em *Observabilidade > Coletores*
. Clique em *Coletores de Dados Instalados*
. Clique na caixa de seleção à esquerda dos coletores de dados que você deseja modificar.
. No menu de opções à direita, clique na opção que deseja executar.


.Depois que você terminar
A operação selecionada é executada nos coletores de dados.  Quando você opta por excluir coletores de dados, uma caixa de diálogo é exibida solicitando que você confirme a ação.
