---
sidebar: sidebar 
permalink: task_dc_brocade_bna.html 
keywords: data collector, Brocade, BNA 
summary: Configurando o coletor Brocade BNA. 
---
= Coletor de dados do Brocade Network Advisor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados do Brocade Network Advisor para adquirir dados de inventário e desempenho de switches Brocade .



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados do Brocade Network Advisor.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Trocar | Trocar 


| Porta | Porta 


| Tecido Virtual, Tecido Físico | Tecido 


| Interruptor lógico | Interruptor lógico 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

Os seguintes itens são necessários para configurar este coletor de dados:

* A Unidade de Aquisição de Data Infrastructure Insights iniciará conexões com a porta TCP 443 no servidor BNA.  O servidor BNA deve estar executando a versão 14.2.1 ou superior.
* Endereço IP do servidor Brocade Network Advisor
* Nome de usuário e senha para uma conta de administrador
* Requisito de porta: HTTP/HTTPS 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| IP do servidor Brocade Network Advisor | Endereço IP do servidor Network Advisor 


| Nome de usuário | Nome de usuário para o switch 


| Nome de usuário | Nome de usuário do administrador 


| Senha | Senha do administrador 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Tipo de conexão | HTTPS (porta padrão 443) ou HTTP (porta padrão 80) 


| Substituir porta de conexão | Se estiver em branco, use a porta padrão no campo Tipo de conexão, caso contrário, insira a porta de conexão a ser usada 


| Senha | Senha para o switch 


| Intervalo de pesquisa de inventário (min) | O padrão é 40 


| Relatório Gateway de Acesso | Marque para incluir dispositivos no modo Access Gateway 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 1800 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Receba uma mensagem de que mais de um nó está conectado à porta do Access Gateway ou que o coletor de dados não consegue descobrir o dispositivo do Access Gateway. | Verifique se o dispositivo NPV está operando corretamente e se todos os WWNs conectados são esperados.  Não adquira o dispositivo NPV diretamente.  Em vez disso, a aquisição do switch de tecido central coletará os dados do dispositivo NPV. 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
