---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Configurando o coletor de dados Infinidat Infinidat InfinibBox. 
---
= Infinidat InfiniBox coletor de dados
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
O coletor de dados Infinidat InfiniBox (HTTP) é usado para coletar informações de inventário do sistema de armazenamento Infinidat InfiniBox.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados Infinidat InfiniBox. Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desse coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo do fornecedor/modelo | Termo do Insights de infraestrutura de dados 


| Pool de storage | Pool de storage 


| Nó | Controlador 


| Sistema de ficheiros | Volume interno 


| Sistema de ficheiros | Partilha de ficheiros 


| Exportações do sistema de arquivos | Partilhar 
|===


== Requisitos

A seguir estão os requisitos ao configurar este coletor de dados.

* Endereço IP ou FQDN do nó de gerenciamento InfiniBox
* ID de usuário e senha do administrador
* Porta 443 via API REST




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Host InfiniBox | Endereço IP ou nome de domínio totalmente qualificado do nó de gerenciamento InfiniBox 


| Nome de utilizador | Nome de usuário para InfiniBox Management Node 


| Palavra-passe | Senha para o nó de gerenciamento InfiniBox 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta TCP usada para se conetar ao InfiniBox Server. A predefinição é 443. 


| Intervalo Poll Stock | Intervalo entre sondagens de inventário. O padrão é 60 minutos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de dados podem ser encontradas link:concept_requesting_support.html["Suporte"]na página ou no link:reference_data_collector_support_matrix.html["Matriz de suporte do Data Collector"].
