---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= Definir opções na aba Preferências
:hardbreaks:
:allow-uri-read: 


[role="lead"]
A guia de preferências de resolução do dispositivo permite criar um cronograma de resolução automática, especificar fornecedores de armazenamento e fita para incluir ou excluir da identificação e definir opções de pesquisa de DNS.



== Cronograma de resolução automática

Um agendamento de resolução automática pode especificar quando a resolução automática do dispositivo é executada:

|===


| Opção | Descrição 


| Todo | Use esta opção para executar a resolução automática do dispositivo em intervalos de dias, horas ou minutos. 


| Diariamente | Use esta opção para executar a resolução automática do dispositivo diariamente em um horário específico. 


| Manualmente | Use esta opção para executar somente a resolução automática do dispositivo manualmente. 


| Em cada mudança de ambiente | Use esta opção para executar a resolução automática do dispositivo sempre que houver uma alteração no ambiente. 
|===
Se você especificar _Manualmente_, a resolução automática noturna do dispositivo será desabilitada.



== Opções de processamento de DNS

As opções de processamento de DNS permitem que você selecione os seguintes recursos:

* Quando o processamento do resultado da pesquisa de DNS estiver habilitado, você poderá adicionar uma lista de nomes de DNS para anexar aos dispositivos resolvidos.
* Você pode selecionar Resolução automática de IPs: para habilitar a resolução automática de host para iniciadores iSCSI e hosts que acessam compartilhamentos NFS usando pesquisa de DNS.  Se isso não for especificado, somente a resolução baseada em FC será executada.
* Você pode optar por permitir sublinhados em nomes de host e usar um alias "conectado a" em vez do alias de porta padrão nos resultados.




=== Incluindo ou excluindo fornecedores específicos de armazenamento e fitas

Você pode incluir ou excluir fornecedores específicos de armazenamento e fita para resolução automática.  Talvez você queira excluir fornecedores específicos se souber, por exemplo, que um host específico se tornará um host legado e deverá ser excluído do seu novo ambiente.  Você também pode adicionar novamente fornecedores que você excluiu anteriormente, mas não deseja mais que sejam excluídos.


NOTE: As regras de resolução de dispositivo para fita funcionam apenas para WWNs em que o Fornecedor desse WWN está definido como _Incluído apenas como fita_ nas preferências do Fornecedor.

Veja também:link:concept_device_resolution_regex_examples.html["Exemplos de expressões regulares"]
