---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: Configurar o coletor de dados NetApp SolidFire 
keywords: data collector, queries, create 
---
= Coletor de dados NetApp SolidFire All-Flash Array
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados NetApp SolidFire All-Flash Array oferece suporte à coleta de inventário e desempenho de configurações iSCSI e Fibre Channel SolidFire .

O coletor de dados SolidFire utiliza a API REST do SolidFire .  A unidade de aquisição onde o coletor de dados reside precisa ser capaz de iniciar conexões HTTPS com a porta TCP 443 no endereço IP de gerenciamento do cluster SolidFire .  O coletor de dados precisa de credenciais capazes de fazer consultas REST API no cluster SolidFire .



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados do NetApp SolidFire All-Flash Array.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Dirigir | Disco 


| Conjunto | Armazenar 


| Nó | Nó de armazenamento 


| Volume | Volume 


| Porta de canal de fibra | Porta 


| Grupo de acesso de volume, atribuição de LUN | Mapa de Volume 


| Sessão iSCSI | Máscara de Volume 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

A seguir estão os requisitos para configurar este coletor de dados:

* Gerenciamento de Endereço IP Virtual
* Nome de usuário e credenciais somente leitura
* Porta 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP Virtual de Gerenciamento (MVIP) | Gerenciamento de endereço IP virtual do SolidFire Cluster 


| Nome de usuário | Nome usado para efetuar login no cluster SolidFire 


| Senha | Senha usada para efetuar login no cluster SolidFire 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Tipo de conexão | Escolha o tipo de conexão 


| Porta de comunicação | Porta usada para a API NetApp 


| Intervalo de pesquisa de inventário (min) | O padrão é 20 minutos 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 300 segundos 
|===


== Solução de problemas

Quando o SolidFire relata um erro, ele é exibido no Data Infrastructure Insights da seguinte forma:

_Uma mensagem de erro foi recebida de um dispositivo SolidFire ao tentar recuperar dados.  A chamada foi <método> (<parameterString> ).  A mensagem de erro do dispositivo foi (consulte o manual do dispositivo): <mensagem>_

Onde:

* O <método> é um método HTTP, como GET ou PUT.
* <parameterString> é uma lista separada por vírgulas de parâmetros que foram incluídos na chamada REST.
* A <mensagem> é o que o dispositivo retornou como mensagem de erro.


Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
