---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Você pode copiar valores de uma tabela para a área de transferência para uso em outros aplicativos. 
keywords: query, queries, copy, values, clipboard 
---
= Copiando valores de tabela
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Você pode copiar valores em tabelas para a área de transferência para uso em caixas de pesquisa ou outros aplicativos.

.Sobre esta tarefa
Há dois métodos que você pode usar para copiar valores de tabelas ou resultados de consultas para a área de transferência.

.Passos
. Método 1: Destaque o texto desejado com o mouse, copie-o e cole-o nos campos de pesquisa ou outros aplicativos.
. Método 2: Para campos de valor único, passe o mouse sobre o campo e clique no ícone da área de transferência que aparece.  O valor é copiado para a área de transferência para uso em campos de pesquisa ou outros aplicativos.
+
Observe que somente valores que são links para ativos podem ser copiados usando este método.  Somente campos que incluem valores únicos (ou seja, não listas) têm o ícone de cópia.


