---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configurando o coletor de dados do Red Hat Virtualization. 
---
= Coletor de dados de virtualização Red Hat
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados do Red Hat Virtualization para coletar dados de inventário de cargas de trabalho virtualizadas do Linux e do Microsoft Windows.



== Terminologia

Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para o ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco Virtual 


| Hospedar | Hospedar 


| Máquina Virtual | Máquina Virtual 


| Domínio de armazenamento | Armazenamento de dados 


| Unidade Lógica | LUN 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Endereço IP do servidor RHEV na porta 443 via API REST
* Nome de usuário e senha somente leitura
* RHEV Versão 3.0+




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do servidor RHEV | Endereço IP do sistema de armazenamento 


| Nome de usuário | Nome de usuário com privilégios de administrador 


| Senha para a conta privilegiada de administrador | Senha 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta de comunicação HTTPS | Porta usada para comunicação HTTPS com RHEV 


| Intervalo de pesquisa de inventário (min) | O padrão é 20 minutos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
