---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf 
summary: Coletor de dados para Kubernetes 
---
= Coletor de dados: Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Data Infrastructure Insights usa esse coletor de dados para reunir métricas de pod, nó e contêiner do Kubernetes.



== Instalação

Para obter instruções de instalação do Kubernetes, consulte olink:task_config_telegraf_agent_k8s.html["Operador de monitoramento do Kubernetes"] página.



== Sobre Kube-state-metrics

O Kubernetes Monitoring Operator instala o kube-state-metrics automaticamente; não é necessária interação do usuário.



=== Contadores de métricas de estado do Kube

O NetApp Kubernetes Monitoring Operator extrai os contadores kube-state-metrics listados abaixo.  Mais detalhes sobre cada balcão podem ser encontrados em: https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics[] .

. Métricas do DaemonSet
. Métricas de Implantação
. Métricas de namespace
. Métricas de nós
. Métricas de Volume Persistente
. Métricas de reivindicação de volume persistente
. Métricas de Pod
. Métricas do ReplicaSet
. Métricas de serviço
. Métricas StatefulSet
. Métricas do AutoScaler de Pod Horizontal
. Métricas do Cronjob
. Métricas de trabalho
. Métricas de cota de recursos

