---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure 
summary: Configure coletores de dados do Workload Security para Cloud Volumes ONTAP e Amazon FSx for NetApp ONTAP para monitorar o acesso a arquivos, a atividade do usuário e detectar ameaças em toda a sua infraestrutura de armazenamento em nuvem. 
---
= Configurando o Cloud Volumes ONTAP e o Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Monitore o acesso a arquivos e usuários em toda a sua infraestrutura de armazenamento em nuvem configurando coletores de dados do Workload Security para Cloud Volumes ONTAP e Amazon FSx for NetApp ONTAP. Este guia fornece instruções passo a passo para implantar agentes na AWS e conectá-los às suas instâncias de armazenamento em nuvem.



== Configuração de armazenamento Cloud Volumes ONTAP

Consulte a documentação do OnCommand Cloud Volumes ONTAP para configurar uma instância AWS de nó único/HA para hospedar o Workload Security Agent:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[]

Após a conclusão da configuração, siga as etapas para configurar seu SVM:https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== Plataformas suportadas

* Cloud Volumes ONTAP, suportado por todos os provedores de serviços de nuvem disponíveis, sempre que disponível.  Por exemplo: Amazon, Azure, Google Cloud.
* ONTAP Amazon FSx




== Configuração da máquina do agente

A máquina do agente deve ser configurada nas respectivas sub-redes dos provedores de serviços de nuvem.  Leia mais sobre acesso à rede em [Requisitos do agente].

Abaixo estão as etapas para instalação do agente na AWS.  Etapas equivalentes, conforme aplicáveis ao provedor de serviços de nuvem, podem ser seguidas no Azure ou no Google Cloud para a instalação.

Na AWS, use as seguintes etapas para configurar a máquina a ser usada como um Agente de Segurança de Carga de Trabalho:

Use as seguintes etapas para configurar a máquina a ser usada como um Agente de Segurança de Carga de Trabalho:

.Passos
. Efetue login no console da AWS, navegue até a página EC2-Instances e selecione _Launch instance_.
. Selecione uma AMI RHEL ou CentOS com a versão apropriada, conforme mencionado nesta página:https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. Selecione a VPC e a sub-rede em que a instância do Cloud ONTAP reside.
. Selecione _t2.xlarge_ (4 vcpus e 16 GB de RAM) como recursos alocados.
+
.. Crie a instância do EC2.


. Instale os pacotes Linux necessários usando o gerenciador de pacotes YUM:
+
.. Instale _wget_ e _descompacte_ os pacotes nativos do Linux.






== Instalar o Agente de Segurança de Carga de Trabalho

. Efetue login como administrador ou proprietário da conta no seu ambiente do Data Infrastructure Insights .
. Navegue até Workload Security *Collectors* e clique na aba *Agents*.
. Clique em *+Agente* e especifique RHEL como a plataforma de destino.
. Copie o comando de instalação do agente.
. Cole o comando de instalação do agente na instância RHEL EC2 na qual você está conectado.  Isso instala o agente de segurança de carga de trabalho, fornecendo todos oslink:concept_cs_agent_requirements.html["Pré-requisitos do agente"] são atendidas.


Para obter etapas detalhadas, consulte este link: https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== Solução de problemas

Problemas conhecidos e suas soluções são descritos na tabela a seguir.

|===


| Problema | Resolução 


| O erro “Segurança da carga de trabalho: falha ao determinar o tipo ONTAP para o coletor de dados Amazon FxSN” é exibido pelo Coletor de dados.  O cliente não consegue adicionar o novo coletor de dados do Amazon FSxN ao Workload Security.  A conexão com o cluster FSxN na porta 443 do agente está expirando.  Os grupos de segurança do firewall e da AWS têm as regras necessárias habilitadas para permitir a comunicação.  Um agente já está implantado e também está na mesma conta da AWS.  Este mesmo agente é usado para conectar e monitorar os dispositivos NetApp restantes (e todos eles estão funcionando). | Resolva esse problema adicionando o segmento de rede LIF fsxadmin à regra de segurança do agente.  Permitir todas as portas caso você não tenha certeza sobre elas. 
|===