---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Configurando o coletor de dados Dell EMC Celerra. 
---
= Coletor de dados Dell EMC VNX File (antigo Celerra Unified Storage System)
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Este coletor de dados adquire informações de inventário do sistema de armazenamento de ficheiros VNX. Para configuração, este coletor de dados requer o endereço IP dos processadores de armazenamento e um nome de usuário e senha somente leitura.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados do arquivo VNX. Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desse coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo do fornecedor/modelo | Termo do Insights de infraestrutura de dados 


| Celerra Network Server/Celerra Storage Pool | Pool de storage 


| Sistema de ficheiros | Volume interno 


| Transferência de dados | Controlador 


| Sistema de arquivos montado em um controlador de dados | Partilha de ficheiros 


| Exportações de CIFS e NFS | Partilhar 


| Volume do disco | LUN de back-end 
|===
Nota: Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para este coletor de dados.



== Requisitos

Você precisa do seguinte para configurar este coletor de dados:

* O endereço IP do processador de armazenamento
* Nome de utilizador e palavra-passe só de leitura
* Porta SSH 22




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do ficheiro VNX | Endereço IP ou nome de domínio totalmente qualificado do dispositivo VNX File 


| Nome de utilizador | Nome utilizado para iniciar sessão no dispositivo ficheiro VNX 


| Palavra-passe | Palavra-passe utilizada para iniciar sessão no dispositivo ficheiro VNX 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de enquete de inventário (minutos) | Intervalo entre sondagens de inventário. O padrão é 20 minutos. 
|===


== Solução de problemas

Algumas coisas para tentar se você encontrar problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Tente isto: 


| Erro: Não é possível prosseguir com a atualização DART em andamento | Solução possível: Pausar o coletor de dados e aguardar que a atualização DART seja concluída antes de tentar outra solicitação de aquisição. 
|===
Informações adicionais podem ser encontradas na link:concept_requesting_support.html["Suporte"] página ou no link:reference_data_collector_support_matrix.html["Matriz de suporte do Data Collector"].
