---
sidebar: sidebar 
permalink: task_dc_huawei_oceanstor.html 
keywords: data collector, Huawei, OceanStor, Dorado 
summary: 'Configurando o coletor de dados Huawei OceanStor (REST/HTTPS).' 
---
= Coletor de dados Huawei OceanStor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados Huawei OceanStor (REST/HTTPS) para descobrir inventário e desempenho do armazenamento Huawei OceanStor e OceanStor Dorado.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário e desempenho do Huawei OceanStor.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Pool de armazenamento | Pool de armazenamento 


| Sistema de arquivos | Volume interno 


| Controlador | Nó de armazenamento 


| Porto FC (Mapeado) | Mapa de Volume 


| Iniciador FC Host (Mapeado) | Máscara de Volume 


| Compartilhamento NFS/CIFS | Compartilhar 


| Destino do link iSCSI | Nó de destino iSCSI 


| Iniciador de link iSCSI | Nó Iniciador iSCSI 


| Disco | Disco 


| LUN | Volume 
|===


== Requisitos

Os seguintes requisitos são necessários para configurar este coletor de dados:

* Endereço IP do dispositivo
* Credenciais para acessar o gerenciador de dispositivos OceanStor
* A porta 8088 deve estar disponível




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do host OceanStor | Endereço IP ou nome de domínio totalmente qualificado do OceanStor Device Manager 


| Nome de usuário | Nome usado para efetuar login no Gerenciador de dispositivos OceanStor 


| Senha | Senha usada para fazer login no OceanStor Device Manager 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta TCP usada para conectar ao OceanStor Device Manager.  O padrão é 8088. 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 


| Intervalo de pesquisa de desempenho (seg). | O padrão é 300 segundos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
