---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Configurando o coletor de dados DELL EMC PowerStore. 
---
= Coletor de dados Dell EMC PowerStore
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados do EMC PowerStore reúne informações de inventário do armazenamento do EMC PowerStore.  Para configuração, o coletor de dados requer o endereço IP dos processadores de armazenamento e um nome de usuário e senha somente leitura.

O coletor de dados do EMC PowerStore reúne os relacionamentos de replicação de volume para volume que o PowerStore coordena em outros arrays de armazenamento.  O Data Infrastructure Insights mostra uma matriz de armazenamento para cada cluster do PowerStore e coleta dados de inventário para nós e portas de armazenamento nesse cluster.  Nenhum dado de pool de armazenamento ou volume é coletado.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário deste coletor de dados.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| hospedar | hospedar 


| mapeamento_de_volume_do_host | mapeamento_de_volume_do_host 


| hardware (tem Drives no objeto "extra_details"): Drives | Disco 


| Eletrodoméstico | Pool de armazenamento 


| Conjunto | Matriz de armazenamento 


| Nó | Nó de armazenamento 


| fc_port | Porta 


| volume | Volume 


| Volume interno | sistema de arquivos 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

As seguintes informações são necessárias para configurar este coletor de dados:

* Endereço IP ou nome de domínio totalmente qualificado do processador de armazenamento
* Nome de usuário e senha somente leitura




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Gateway(s) PowerStore | Endereços IP ou nomes de domínio totalmente qualificados do armazenamento PowerStore 


| Nome de usuário | Nome de usuário para PowerStore 


| Senha | Senha usada para PowerStore 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta HTTPS | O padrão é 443 


| Intervalo de pesquisa de inventário (minutos) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 
|===
A coleta de desempenho do PowerStore do Cloud Insight utiliza dados de origem de granularidade de 5 minutos do PowerStore.  Dessa forma, o Data Infrastructure Insights pesquisa esses dados a cada cinco minutos, e isso não é configurável.



== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
