---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Configurando o coletor de dados Nutanix. 
---
= Coletor de dados Nutanix NX
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados Nutanix para descobrir dados de inventário e desempenho para sistemas de armazenamento Nutanix NX.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados Nutanix.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Pool de armazenamento | Pool de armazenamento 


| Recipiente Nutanix | Volume interno 


| Recipiente Nutanix | Compartilhamento de arquivos 


| Compartilhamento NFS | Compartilhar 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* O endereço IP dos serviços de dados externos para o cluster
* Nome de usuário e senha somente leitura, a menos que volume_groups estejam em uso, nesse caso, o nome de usuário e senha do administrador são necessários
* Requisito de porta: HTTPS 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP externo do Prism | O endereço IP dos serviços de dados externos para o cluster 


| Nome de usuário | Nome de usuário para a conta de administrador 


| Senha | Senha para a conta de administrador 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta TCP usada para conectar ao array Nutanix.  O padrão é 9440. 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 


| Intervalo de pesquisa de desempenho (seg) | Intervalo entre pesquisas de desempenho. O padrão é 300 segundos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
