---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Configurando o coletor de dados Infinidat InfiniBox. 
---
= Coletor de dados Infinidat InfiniBox
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados Infinidat InfiniBox (HTTP) é usado para coletar informações de inventário do sistema de armazenamento Infinidat InfiniBox.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados Infinidat InfiniBox.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Pool de armazenamento | Pool de armazenamento 


| Nó | Controlador 


| Sistema de arquivos | Volume interno 


| Sistema de arquivos | Compartilhamento de arquivos 


| Exportações do sistema de arquivos | Compartilhar 
|===


== Requisitos

A seguir estão os requisitos ao configurar este coletor de dados.

* Endereço IP ou FQDN do nó de gerenciamento do InfiniBox
* ID de usuário e senha do administrador
* Porta 443 via API REST




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Host InfiniBox | Endereço IP ou nome de domínio totalmente qualificado do nó de gerenciamento InfiniBox 


| Nome de usuário | Nome de usuário para o nó de gerenciamento InfiniBox 


| Senha | Senha para o nó de gerenciamento do InfiniBox 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta TCP usada para conectar ao servidor InfiniBox.  O padrão é 443. 


| Intervalo de pesquisa de inventário | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
