---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Workload Security, User, Login, account, cloud secure 
summary: Segurança de Carga de Trabalho As contas de usuário são gerenciadas pelo gerenciamento de usuários do Data Infrastructure Insights 
---
= Gerenciamento de usuários
:hardbreaks:
:allow-uri-read: 


[role="lead"]
As contas de usuário do Workload Security são gerenciadas pelo Data Infrastructure Insights.

O Data Infrastructure Insights fornece quatro níveis de conta de usuário: Proprietário da conta, Administrador, Usuário e Convidado.  Cada conta recebe níveis de permissão específicos.  Uma conta de usuário com privilégios de administrador pode criar ou modificar usuários e atribuir a cada usuário uma das seguintes funções de segurança de carga de trabalho:

|===


| Papel | Acesso de segurança de carga de trabalho 


| Administrador | Pode executar todas as funções de segurança de carga de trabalho, incluindo aquelas para alertas, análises forenses, coletores de dados, políticas de resposta automatizadas e APIs para segurança de carga de trabalho.  Um administrador também pode convidar outros usuários, mas só pode atribuir funções de segurança de carga de trabalho. 


| Usuário | Pode visualizar e gerenciar alertas e visualizar análises forenses.  A função do usuário pode alterar o status do alerta, adicionar uma nota, tirar instantâneos manualmente e restringir o acesso do usuário. 


| Convidado | Pode visualizar alertas e análises forenses.  A função de convidado não pode alterar o status do alerta, adicionar uma nota, tirar instantâneos manualmente ou restringir o acesso do usuário. 
|===
.Passos
. Faça login no Workload Security
. No menu, clique em *Admin > Gerenciamento de usuários*
+
Você será encaminhado para a página de Gerenciamento de Usuários do Data Infrastructure Insights.

. Selecione a função desejada para cada usuário.


Ao adicionar um novo usuário, basta selecionar a função desejada (geralmente Usuário ou Convidado).

Mais informações sobre contas e funções de usuário podem ser encontradas em Data Infrastructure Insightslink:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["Função do usuário"] documentação.
