---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: Crie regras de anotação para aplicar anotações automaticamente a vários ativos. 
keywords: annotate, annotation, rules 
---
= Criando regras de anotação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar regras de anotação para aplicar anotações automaticamente a vários ativos com base nos critérios que você definir.  O Data Infrastructure Insights atribui as anotações aos ativos com base nessas regras.  Anotações definidas manualmente em páginas de ativos individuais têm precedência sobre anotações baseadas em regras quando o Cloud Insight avalia as regras de anotação.

.Antes de começar
Você deve ter criado uma consulta para a regra de anotação.

.Passos
. No menu Data Infrastructure Insights, clique em *Gerenciar > Regras de anotação*.
. Clique em *+ Regra* para adicionar uma nova regra de anotação.
+
A caixa de diálogo Adicionar regra é exibida.

. Faça o seguinte:
+
.. Na caixa *Nome*, insira um nome exclusivo que descreva a regra.
+
O nome aparece na página Regras de Anotação.

.. Clique em *Consulta* e selecione a consulta que o Data Infrastructure Insights usa para identificar os ativos aos quais a anotação se aplica.
.. Clique em *Anotação* e selecione a anotação que deseja aplicar.
.. Clique em *Valor* e selecione um valor para a anotação.
+
Por exemplo, se você escolher Aniversário como anotação, especifique uma data para o valor.

.. Clique em *Salvar*
.. Clique em *Executar todas as regras* se quiser executar todas as regras imediatamente; caso contrário, as regras serão executadas em um intervalo agendado regularmente.
+

NOTE: Em um grande ambiente do Data Infrastructure Insights , você pode notar que a execução de regras de anotação parece demorar um pouco para ser concluída.  Isso ocorre porque o indexador é executado primeiro e deve ser concluído antes de executar as regras.  O indexador é o que dá ao Data Infrastructure Insights a capacidade de pesquisar ou filtrar objetos e contadores novos ou atualizados em seus dados.  O mecanismo de regras aguarda até que o indexador conclua sua atualização antes de aplicar as regras.







== Modificando regras de anotação

Você pode modificar uma regra de anotação para alterar o nome da regra, sua anotação, o valor da anotação ou a consulta associada à regra.

.Passos
. No menu Data Infrastructure Insights , clique em *Gerenciar > Regras de anotação*.
+
A página Regras de anotação exibe a lista de regras de anotação existentes.

. Localize a Regra de Anotação que você deseja modificar.
+
Você pode filtrar as regras de anotação inserindo um valor na caixa de filtro ou clicar em um número de página para navegar pelas regras de anotação por página.

. Clique no ícone de menu da regra que você deseja modificar.
. Clique em *Editar*
+
A caixa de diálogo Editar regra é exibida.

. Modifique o nome, a anotação, o valor ou a consulta da regra de anotação.




== Alterando a ordem das regras

As regras de anotação são processadas do topo para o fim da lista de regras.  Para alterar a ordem em que uma regra é processada, faça o seguinte:

.Passos
. Clique no ícone de menu da regra que você deseja mover.
. Clique em *Mover para cima* ou *Mover para baixo* conforme necessário até que a regra apareça no local desejado.


Observe que, ao executar várias regras que atualizam a mesma anotação em um ativo, a primeira regra (executada de cima para baixo) aplica a anotação e atualiza o ativo; depois, a segunda regra se aplica, mas não altera nenhuma anotação que já tenha sido definida pela regra anterior.



== Excluindo regras de anotação

Talvez você queira excluir regras de anotação que não são mais usadas.

.Passos
. No menu Data Infrastructure Insights , clique em *Gerenciar > Regras de anotação*.
+
A página Regras de anotação exibe a lista de regras de anotação existentes.

. Localize a Regra de Anotação que você deseja excluir.
+
Você pode filtrar as regras de anotação inserindo um valor na caixa de filtro ou clicar em um número de página para navegar pelas regras de anotação por página.

. Clique no ícone de menu da regra que você deseja excluir.
. Clique em *Excluir*
+
Uma mensagem de confirmação é exibida, perguntando se você deseja excluir a regra.

. Clique em *OK*

