---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: Configurando o coletor de dados HDS. 
---
= Coletor de dados Hitachi HCP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados oferece suporte à Hitachi Content Platform (HCP) usando a API de gerenciamento do HCP.


NOTE: A Hitachi Content Platform é medida a uma taxa de TB brutos diferente da taxa de unidade gerenciada.  Cada 40 TB de capacidade HCP não formatada é cobrado como 1link:concept_subscribing_to_cloud_insights.html#pricing["Unidade Gerenciada (UM)"] .



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados Hitachi HCP.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Cluster de HCP | Armazenar 


| Inquilino | Pool de armazenamento 


|  | Espaço de nomes 


| Volume interno | Nó 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos de inventário

Você deve ter o seguinte para coletar dados de inventário:

* Endereço IP do servidor HCP
* Nome de usuário e senha somente leitura para o software HCP e privilégios de pares




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Anfitrião HCP | Endereço IP ou nome de domínio totalmente qualificado do host HCP 


| Porto HCP | O padrão é 9090 


| ID do usuário do HCP | Nome de usuário para o host HCP. 


| Senha do HCP | Senha usada para o host HCP. 


| Tipo de autenticação HCP | Escolha HCP_LOCAL ou ACTIVE_DIRECTORY 
|===


== Configuração avançada

|===


| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário.  O padrão é 60. 


| Intervalo de pesquisa de desempenho (seg) | Intervalo entre pesquisas de desempenho.  O padrão é 900. 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
