---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configurando o coletor de dados do DELL EMC RecoverPoint. 
---
= Coletor de dados Dell EMC RecoverPoint
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O principal caso de uso do coletor de dados EMC RecoverPoint é descobrir relacionamentos de replicação de volume para volume que o dispositivo de armazenamento RecoverPoint facilita.  Este coletor também descobrirá o próprio dispositivo Recoverpoint.  Observe que a Dell/EMC vende uma solução de backup VMware para VMs — "RecoverPoint for VMs" — que não é suportada por este coletor

Para configuração, o coletor de dados requer o endereço IP dos processadores de armazenamento e um nome de usuário e senha somente leitura.

O coletor de dados EMC RecoverPoint reúne os relacionamentos de replicação de volume para volume que o RecoverPoint coordena em outros arrays de armazenamento.  O Data Infrastructure Insights mostra uma matriz de armazenamento para cada cluster do RecoverPoint e coleta dados de inventário para nós e portas de armazenamento nesse cluster.  Nenhum dado de pool de armazenamento ou volume é coletado.



== Requisitos

As seguintes informações são necessárias para configurar este coletor de dados:

* Endereço IP ou nome de domínio totalmente qualificado do processador de armazenamento
* Nome de usuário e senha somente leitura
* Acesso à API REST via porta 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço do RecoverPoint | Endereço IP ou nome de domínio totalmente qualificado do cluster RecoverPoint 


| Nome de usuário | Nome de usuário para o cluster RecoverPoint 


| Senha | Senha usada para o cluster RecoverPoint 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta TCP usada para conectar ao cluster Recoverpoint 


| Intervalo de pesquisa de inventário (minutos) | Intervalo entre pesquisas de inventário. O padrão é 20 minutos. 


| Clusters Excluídos | Lista separada por vírgulas de IDs ou nomes de cluster a serem excluídos durante a pesquisa. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
