---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Configurando o coletor de dados do DELL EMC Data Domain. 
---
= Coletor de dados DELL EMC Data Domain
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados reúne informações de inventário e desempenho dos sistemas de armazenamento de desduplicação DELL EMC Data Domain.  Para configurar este coletor de dados, há instruções de configuração específicas e recomendações de uso que você deve seguir.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados do Data Domain.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco 


| Variedade | Armazenar 


| FC Porto | Porta 


| Sistema de arquivos | Volume interno 


| Contingente | Contingente 


| Compartilhamento NFS e CIFS | Compartilhamento de arquivos 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

Você precisa das seguintes informações para configurar este coletor de dados:

* Endereço IP do dispositivo Data Domain
* Nome de usuário e senha somente leitura para o armazenamento do Data Domain
* Porta SSH 22




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP | O endereço IP ou nome de domínio totalmente qualificado do array de armazenamento do Data Domain 


| Nome de usuário | O nome de usuário para o array de armazenamento do Data Domain 


| Senha | A senha para o array de armazenamento do Data Domain 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário.  O padrão é 20. 


| Porta SSH | Porta de serviço SSH 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
