---
sidebar: sidebar 
permalink: task_dc_emc_vnxe.html 
keywords: data collector, VNXe, EMC 
summary: Configurando o coletor de dados VNXe. 
---
= Configurar o coletor de dados EMC VNXe
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
O coletor de dados Dell EMC VNXe fornece suporte de inventário para matrizes de armazenamento unificadas VNXe. O Data Infrastructure Insights atualmente oferece suporte aos protocolos iSCSI e nas.



== Requisitos

* O coletor de dados VNXe é baseado na CLI; você deve instalar o Unisphere para VNXe CLI (uemcli.exe) na unidade de aquisição onde reside o coletor de dados VNXe.
* O uemcli.exe utiliza HTTPS como protocolo de transporte, pelo que a unidade de aquisição terá de ser capaz de iniciar ligações HTTPS com o VNXe.
* Endereço IP ou nome de domínio totalmente qualificado do dispositivo VNXe
* Você deve ter pelo menos um usuário somente leitura para uso pelo coletor de dados.
* Endereço IP do servidor facilitador de soluções de gerenciamento.
* HTTPS na porta 443 é necessário
* O coletor de dados EMC VNXe fornece suporte nas e iSCSI para inventário; volumes de canal de fibra serão descobertos, mas o Data Infrastructure Insights não relata portas de mapeamento, mascaramento ou armazenamento FC.




== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados VNXe. Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desse coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo do fornecedor/modelo | Termo do Insights de infraestrutura de dados 


| Disco | Disco 


| Storage array | Armazenamento 


| Processador | Nó de storage 


| Pool de storage | Pool de storage 


| Informações gerais do bloco iSCSI, VMware VMFS | Partilhar 


| Sistema remoto de replicação | Sincronização 


| Nó iSCSI | Nó de destino iSCSI 


| Iniciador iSCSI | Iniciador iSCSI Target 
|===
Nota: Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para esta fonte de dados.



== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Armazenamento VNXe | Endereço IP ou nome de domínio totalmente qualificado do dispositivo VNXe 


| Nome de utilizador | Nome de utilizador para o dispositivo VNXe 


| Palavra-passe | Palavra-passe para o dispositivo VNXe 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de enquete de inventário (min) | Intervalo entre sondagens de inventário. O padrão é 40 minutos 


| Porta CLI | Porta usada para a CLI VNXe 


| Intervalo de pesquisa de desempenho (seg) | A predefinição é 300. 
|===


== Solução de problemas

Algumas coisas para tentar se você encontrar problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Tente isto: 


| "Falha ao executar utilitário externo" com mensagens de erro "Falha ao encontrar o executável do Unisphere uemcli" | * Verifique o endereço IP, nome de usuário e senha corretos * Confirme se a Unisphere CLI está instalada na Unidade de aquisição do Data Infrastructure Insights * Confirme se o diretório de instalação da Unisphere CLI está correto na configuração da fonte de dados * Confirme se o IP do VNXe está correto na configuração da fonte de dados. Na Unidade de aquisição do Data Infrastructure Insights, abra um CMD e mude para o diretório de instalação configurado: Tente fazer uma conexão com o dispositivo VNXe digitando: Uemcli -d <Your IP> -u <Your ID> /sys/general show 
|===
Informações adicionais podem ser encontradas na link:concept_requesting_support.html["Suporte"] página ou no link:reference_data_collector_support_matrix.html["Matriz de suporte do Data Collector"].
