---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: Acompanhe dados usando anotações. 
---
= Definindo anotações
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ao personalizar o Data Infrastructure Insights para rastrear dados para suas necessidades corporativas, você pode definir notas especializadas, chamadas anotações, e atribuí-las aos seus ativos.

Você pode atribuir anotações a ativos com informações como fim de vida útil do ativo, data center, localização do edifício, nível de armazenamento ou nível de serviço de volume.

Usar anotações para ajudar a monitorar seu ambiente inclui as seguintes tarefas de alto nível:

* Criar ou editar definições para todos os tipos de anotação.
* Exibindo páginas de ativos e associando cada ativo a uma ou mais anotações.
+
Por exemplo, se um ativo estiver sendo arrendado e o arrendamento expirar dentro de dois meses, você pode querer aplicar uma anotação de fim de vida útil ao ativo.  Isso ajuda a evitar que outras pessoas usem esse ativo por um longo período.

* Criação de regras para aplicar anotações automaticamente a vários ativos do mesmo tipo.
* Filtre ativos por suas anotações.




== Tipos de anotação padrão

O Data Infrastructure Insights fornece alguns tipos de anotação padrão.  Essas anotações podem ser usadas para filtrar ou agrupar dados.

Você pode associar ativos a tipos de anotação padrão, como os seguintes:

* Ciclo de vida do ativo, como aniversário, expiração ou fim da vida útil
* Informações de localização sobre um dispositivo, como data center, edifício ou andar
* Classificação de ativos, como por qualidade (níveis), por dispositivos conectados (nível de switch) ou por nível de serviço
* Status, como quente (alta utilização)


A tabela a seguir lista os tipos de anotação fornecidos Data Infrastructure Insights.

[cols="30,53, 16"]
|===


| Tipos de anotação | Descrição | Tipo 


| Pseudônimo | Nome amigável para um recurso | Texto 


| Grupo de Recursos de Computação | Atribuição de grupo usada pelo coletor de dados dos sistemas de arquivos do host e da VM | Lista 


| Centro de Dados | Localização física | Lista 


| Quente | Dispositivos com uso intenso e regular ou no limite da capacidade | Booleano 


| Observação | Comentários associados a um recurso | Teste 


| Nível de serviço | Um conjunto de níveis de serviço suportados que você pode atribuir aos recursos.  Fornece uma lista de opções ordenadas para volumes internos, qtree e volumes.  Edite os níveis de serviço para definir políticas de desempenho para diferentes níveis. | Lista 


| Pôr do sol | Limite definido após o qual nenhuma nova alocação pode ser feita para esse dispositivo.  Útil para migrações planejadas e outras alterações de rede pendentes. | Data 


| Nível de troca | Opções predefinidas para configurar categorias para switches.  Normalmente, essas designações permanecem durante toda a vida útil do dispositivo, embora você possa editá-las.  Disponível somente para interruptores. | Lista 


| Nível | Pode ser usado para definir diferentes níveis de serviço dentro do seu ambiente.  Os níveis podem definir o tipo de nível, como a velocidade necessária (por exemplo, ouro ou prata).  Este recurso está disponível somente em volumes internos, qtrees, matrizes de armazenamento, pools de armazenamento e volumes. | Lista 


| Gravidade da violação | Classificação (por exemplo, maior) de uma violação (por exemplo, portas de host ausentes ou redundância ausente), em uma hierarquia da maior para a menor importância. | Lista 
|===

NOTE: Alias, Data Center, Hot, Service Level, Sunset, Switch Level, Tier e Violation Severity são anotações no nível do sistema, que você não pode excluir ou renomear; você pode alterar apenas os valores atribuídos a eles.



== Criando anotações personalizadas

Usando anotações, você pode adicionar dados comerciais personalizados específicos aos ativos que correspondem às suas necessidades comerciais.  Embora o Data Infrastructure Insights forneça um conjunto de anotações padrão, você pode querer visualizar dados de outras maneiras.  Os dados em anotações personalizadas complementam os dados do dispositivo já coletados, como fabricante do armazenamento, volumes numéricos e estatísticas de desempenho.  Os dados que você adiciona usando anotações não são descobertos pelo Data Infrastructure Insights.

.Passos
. No menu Data Infrastructure Insights , clique em *Gerenciar > Anotações*.
+
A página Anotações exibe a lista de anotações.

. Clique em *+Adicionar*
. Insira um *Nome* e uma *Descrição* da anotação.
+
Você pode inserir até 255 caracteres nesses campos.

. Clique em *Tipo* e selecione uma das seguintes opções que representa o tipo de dados permitidos nesta anotação:


.Tipos de anotação
* Booleano: Cria uma lista suspensa com as opções sim e não. Por exemplo, a anotação "Anexado Diretamente" é booleana.
* Data: Isso cria um campo que contém uma data. Por exemplo, se a anotação for uma data, selecione isso.
* Lista: Cria um dos seguintes:
+
** Uma lista suspensa fixa
+
Quando outros atribuem esse tipo de anotação em um dispositivo, eles não podem adicionar mais valores à lista.

** Uma lista suspensa flexível
+
Se você selecionar a opção Adicionar novos valores dinamicamente ao criar esta lista, quando outros estiverem atribuindo este tipo de anotação em um dispositivo, eles poderão adicionar mais valores à lista.



* Número: Cria um campo onde o usuário que atribui a anotação pode inserir um número.  Por exemplo, se o tipo de anotação for "Andar", o usuário poderá selecionar o Tipo de Valor "número" e inserir o número do andar.
* Texto: Cria um campo que permite texto de formato livre.  Por exemplo, você pode inserir "Idioma" como o tipo de anotação, selecionar "Texto" como o tipo de valor e inserir um idioma como valor.



NOTE: Depois de definir o tipo e salvar as alterações, você não poderá alterar o tipo da anotação.  Se precisar alterar o tipo, você terá que excluir a anotação e criar uma nova.

. Se você selecionar Lista como o tipo de anotação, faça o seguinte:
+
.. Selecione *Adicionar novos valores dinamicamente* se quiser adicionar mais valores à anotação quando estiver em uma página de ativos, o que cria uma lista flexível.
+
Por exemplo, suponha que você esteja em uma página de ativos e o ativo tenha a anotação Cidade com os valores Detroit, Tampa e Boston.  Se você selecionou a opção *Adicionar novos valores dinamicamente*, você pode adicionar valores adicionais a cidades como São Francisco e Chicago diretamente na página de ativos, em vez de ter que ir até a página Anotações para adicioná-los.  Se você não escolher esta opção, não poderá adicionar novos valores de anotação ao aplicá-la; isso criará uma lista fixa.

.. Insira um valor e uma descrição nos campos *Valor* e *Descrição*.
.. Clique em *+Adicionar+* para adicionar valores adicionais.
.. Clique no ícone Lixeira para excluir um valor.


. Clique em *Salvar*
+
Suas anotações aparecem na lista na página Anotações.



.Uma nota sobre anotações booleanas
Ao filtrar uma anotação booleana, você poderá ver os seguintes valores para filtrar:

* *Qualquer*: Isso retornará _todos_ os resultados, incluindo resultados definidos como "Sim", "Não" ou não definidos.
* *Sim*: Retorna somente resultados "Sim". Observe que DII mostra "Sim" como uma marca de seleção na maioria das tabelas. Os valores podem ser definidos como "Verdadeiro", "Ligado", etc.; o DII trata todos eles como "Sim".
* *Não*: Retorna somente resultados "Não". Observe que DII mostra "Não" como um "X" na maioria das tabelas. Os valores podem ser definidos como "Falso", "Desligado", etc.; o DII trata todos eles como "Não".
* *Nenhum*: Retorna somente resultados onde a anotação não foi definida. Também chamados de valores "nulos".


.Depois que você terminar
Na interface do usuário, a anotação fica disponível imediatamente para uso.
