---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: Coletor de dados IBM TotalStorage DS4000 
---
= Coletor de dados IBM TotalStorage DS4000
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados adquire informações de inventário e desempenho do sistema de armazenamento IBM DS4000.  Há duas configurações possíveis (firmware 6.x e firmware 7.x+), e ambas têm os mesmos valores.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados IBM DS4000.  Para cada tipo de ativo adquirido, é mostrada a terminologia mais comum usada para esse ativo.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco 


| Grupo de Volume | Grupo de Discos 


| Matriz de armazenamento | Armazenar 


| Controlador | Nó de armazenamento 


| Grupo de Volume | Pool de armazenamento 


| Volume | Volume 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Endereço IP de cada matriz DS5 ou FAStT
* Validação de acesso por ping no endereço IP de ambos os controladores no array
* Requisitos de porta: 2463




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Lista separada por vírgulas de IPs do Array SANtricity Controller | Endereços IP e/ou nomes de domínio totalmente qualificados para os controladores de matriz 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 30 minutos 


| Intervalo de pesquisa de desempenho de até 3600 segundos | O padrão é 300 segundos 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
