---
sidebar: sidebar 
permalink: task_dc_proxmox_ve.html 
keywords: data collector, Proxmox Virtual Environment, PVE 
summary: Configurando o coletor de dados do Proxmox Virtual Environment. 
---
= Coletor de dados do Proxmox Virtual Environment
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O coletor de Ambiente Virtual Proxmox DII coletará dados de inventário e desempenho para máquinas virtuais baseadas em PVE (não contêineres LXC) e hosts/hipervisores. Este é um coletor baseado em API REST HTTPS que precisa se comunicar com a API REST fornecida pelo serviço/daemon pveproxy que escuta na porta TCP 8006.

Este coletor de dados utiliza autenticação de usuário + token. Você precisará criar uma conta de serviço em cada cluster Proxmox, atribuir as permissões apropriadas ao usuário e, em seguida, gerar um token de API com esses mesmos direitos. Observe que o token de um determinado usuário do Proxmox NÃO necessariamente possui os mesmos direitos/permissões que o usuário. O DII geralmente precisa de direitos globais de Auditoria/Monitoramento. Se você estiver criando uma conta de serviço pela interface do Proxmox, para PathPermision comece em "/", defina Propagar como "Sim" e desbloqueie, no mínimo, Auditoria de Datastore, Auditoria de Mapeamento, Auditoria de Pool, Auditoria SDN, Auditoria de Sistema, Auditoria de VM e Monitoramento de VM. Com o usuário criado, você pode então criar um token de acesso para ele. Considere fortemente criar o token com expiração 0 para garantir que ele nunca expire.



[[terminology]]
== Terminologia

Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para o ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="50,50"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco Virtual 


| Hospedar | Hospedar 


| Máquina Virtual | Máquina Virtual 


| Armazenar | Armazenamento de dados 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



[[configuration]]
== Configuração

[cols="50,50"]
|===
| Campo | Descrição 


| Nome do host ou endereço IP | Nome do host endereço IP do sistema de storage 


| ID do token da API | Token de API necessário para acesso 


| Segredo do token da API | Segredo para o token acima 
|===


[[advanced-configuration]]
== Configuração avançada

[cols="50,50"]
|===
| Campo | Descrição 


| Porta de comunicação HTTPS | Porta usada para comunicação HTTPS (padrão 8006) 


| Intervalo de pesquisa de inventário (min) | O padrão é 20 minutos. 
|===


[[troubleshooting]]
== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
