---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Configurando o coletor de dados XtremeIO. 
---
= Coletor de dados Dell EMC XtremeIO
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados EMC XtremIO adquire dados de inventário e desempenho do sistema de armazenamento EMC XtremIO.



== Requisitos

Para configurar o coletor de dados EMC XtremIO (HTTP), você deve ter:

* Endereço do host do XtremIO Management Server (XMS)
* Uma conta com privilégios de administrador
* Acesso à porta 443 (HTTPS)




== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados EMC XtremIO.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas desta fonte de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco (SSD) | Disco 


| Conjunto | Armazenar 


| Controlador | Nó de armazenamento 


| Volume | Volume 


| Mapa LUN | Mapa de Volume 


| Iniciador FC de destino | Máscara de Volume 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos desta fonte de dados.



== Requisitos

* Endereço IP do host do XtremIO Management Server (XMS)
* Nome de usuário e senha do administrador para o XtremIO




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Host XMS | Endereço IP ou nome de domínio totalmente qualificado do XtremIO Management Server 


| Nome de usuário | Nome de usuário para o XtremIO Management Server 


| Senha | Senha para o servidor de gerenciamento XtremIO 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta TCP usada para conectar ao XTremIO Management Server.  O padrão é 443. 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 


| Intervalo de pesquisa de desempenho (seg) | Intervalo entre pesquisas de desempenho. O padrão é 300 segundos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
