---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap, e-series, santricity 
summary: Configurando o coletor de dados NetApp E-Series. 
---
= Coletor de dados da API NetApp E-Series Legacy Santricity
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados da NetApp E-Series Legacy Santricity API reúne dados de inventário e desempenho.  O coletor suporta firmware 7.x+ usando as mesmas configurações e relatando os mesmos dados.



== Terminologia

O Cloud Insight adquire as seguintes informações de inventário do coletor de dados NetApp E-Series.  Para cada tipo de ativo adquirido, é mostrada a terminologia mais comum usada para esse ativo.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco 


| Grupo de Volume | Grupo de Discos 


| Matriz de armazenamento | Armazenar 


| Controlador | Nó de armazenamento 


| Grupo de Volume | Pool de armazenamento 


| Volume | Volume 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Terminologia da Série E (Página de destino)

Os termos a seguir se aplicam a objetos ou referências que você pode encontrar nas páginas de destino de ativos do NetApp E-Series.  Muitos desses termos também se aplicam a outros coletores de dados.



=== Armazenar

* Modelo – nome do modelo do dispositivo.
* Fornecedor – o mesmo nome do fornecedor que você veria se estivesse configurando uma nova fonte de dados
* Número de série – O número de série do array.  Em sistemas de armazenamento de arquitetura de cluster, como o NetApp Clustered Data Ontap, esse número de série pode ser menos útil do que os números de série individuais dos “Nós de Armazenamento”
* IP – geralmente será o(s) IP(s) ou nome(s) do(s) host(s) conforme configurado na fonte de dados
* Versão do microcódigo – firmware
* Capacidade bruta – soma de base 2 de todos os discos físicos no sistema, independentemente de sua função
* Latência – uma representação do que as cargas de trabalho do host estão enfrentando, tanto em leituras quanto em gravações.  O ideal seria que o Data Infrastructure Insights obtivesse esse valor diretamente, mas isso nem sempre acontece.  Em vez de a matriz oferecer isso, o Data Infrastructure Insights geralmente executa um cálculo ponderado por IOPs derivado das estatísticas dos volumes individuais.
* Taxa de transferência – taxa de transferência total do host do array.  Idealmente obtido diretamente do array, se indisponível, o Data Infrastructure Insights está somando a taxa de transferência dos volumes para derivar esse valor
* Gerenciamento – pode conter um hiperlink para a interface de gerenciamento do dispositivo.  Criado programaticamente pela fonte de dados do Data Infrastructure Insights como parte do relatório de inventário  




=== Pool de armazenamento

* Armazenamento – em qual matriz de armazenamento esse pool reside. Obrigatório
* Tipo – um valor descritivo de uma lista de possibilidades enumeradas.  O mais comum será “Thin Provisioning” ou “RAID Group”
* Nó – se a arquitetura deste conjunto de armazenamento for tal que os pools pertençam a um nó de armazenamento específico, seu nome será visto aqui como um hiperlink para sua própria página de destino
* Utiliza Flash Pool – valor Sim/Não
* Redundância – nível RAID ou esquema de proteção.  E-Series relata “RAID 7” para pools DDP
* Capacidade – os valores aqui são a capacidade lógica utilizada, a capacidade utilizável e a capacidade lógica total, além da porcentagem utilizada entre elas.  Esses valores incluem a capacidade de “preservação” da Série E, resultando em números e em uma porcentagem maior do que a interface do usuário da Série E pode mostrar.
* Capacidade superalocada – Se, por meio de tecnologias de eficiência, você tiver alocado uma soma total de capacidades de volume ou volume interno maior que a capacidade lógica do pool de armazenamento, o valor percentual aqui será maior que 0%.
* Snapshot – capacidades de snapshot usadas e totais, se a arquitetura do seu pool de armazenamento dedicar parte de sua capacidade a áreas de segmentos exclusivamente para snapshots
* Utilização – um valor percentual que mostra a maior porcentagem de ocupação de disco de qualquer disco que contribui com capacidade para este pool de armazenamento.  A utilização do disco não tem necessariamente uma forte correlação com o desempenho do array – a utilização pode ser alta devido a reconstruções de disco, atividades de desduplicação, etc. na ausência de cargas de trabalho controladas pelo host.  Além disso, muitas implementações de replicação de matrizes podem direcionar a utilização do disco sem serem exibidas como carga de trabalho de volume.
* IOPS – a soma de IOPS de todos os discos que contribuem com capacidade para este pool de armazenamento.  Se os IOPs de disco não estiverem disponíveis em uma determinada plataforma, esse valor será obtido da soma dos IOPs de volume para todos os volumes neste pool de armazenamento.
* Taxa de transferência – a soma da taxa de transferência de todos os discos que contribuem com capacidade para esse pool de armazenamento.  Se a taxa de transferência do disco não estiver disponível em uma determinada plataforma, esse valor será obtido da soma do volume para todos os volumes neste pool de armazenamento.




=== Nó de armazenamento

* Armazenamento – de qual matriz de armazenamento esse nó faz parte. Obrigatório
* Parceiro HA – em plataformas onde um nó falhará em um e somente um outro nó, geralmente será visto aqui
* Estado – saúde do nó.  Disponível somente quando o array estiver saudável o suficiente para ser inventariado por uma fonte de dados
* Modelo – nome do modelo do nó
* Versão – nome da versão do dispositivo.
* Número de série – O número de série do nó
* Memória – memória base 2, se disponível
* Utilização – Geralmente, um número de utilização da CPU ou, no caso do NetApp Ontap, um índice de estresse do controlador.  A utilização não está disponível atualmente para NetApp E-Series
* IOPS – um número que representa os IOPs controlados pelo host neste controlador.  Idealmente obtido diretamente do array, se não estiver disponível, será calculado somando todos os IOPs para volumes que pertencem exclusivamente a este nó.
* Latência – um número que representa a latência típica do host ou o tempo de resposta neste controlador.  Idealmente obtido diretamente do array, se não estiver disponível, será calculado executando um cálculo ponderado de IOPs a partir de volumes que pertencem exclusivamente a este nó.
* Taxa de transferência – um número que representa a taxa de transferência acionada pelo host neste controlador.  Idealmente obtido diretamente do array, se indisponível, será calculado somando toda a taxa de transferência de volumes que pertencem exclusivamente a este nó.
* Processadores – contagem de CPU




== Requisitos

* O endereço IP de cada controlador no array
* Requisito de porta 2463




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Lista separada por vírgulas de IPs do Array SANtricity Controller | Endereços IP e/ou nomes de domínio totalmente qualificados para os controladores de matriz 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 30 minutos 


| Intervalo de pesquisa de desempenho de até 3600 segundos | O padrão é 300 segundos 
|===


== Solução de problemas

Informações adicionais sobre este coletor de dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
