---
sidebar: sidebar 
permalink: task_view_queries.html 
summary: Visualizando consultas que foram criadas 
keywords: query, queries, viewing 
---
= Visualizando consultas
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Você pode visualizar suas consultas para monitorar seus ativos e alterar como suas consultas exibem os dados relacionados aos seus ativos.

.Passos
. Efetue login no seu locatário do Data Infrastructure Insights .
. Clique em *Consultas* e selecione *Mostrar todas as consultas*.  Você pode alterar a forma como as consultas são exibidas executando qualquer um dos seguintes procedimentos:
. Você pode inserir texto na caixa de filtro para pesquisar e exibir consultas específicas.
. Você pode alterar a ordem de classificação das colunas na tabela de consultas para crescente (seta para cima) ou decrescente (seta para baixo) clicando na seta no cabeçalho da coluna.
. Para redimensionar uma coluna, passe o mouse sobre o cabeçalho da coluna até que uma barra azul apareça.  Coloque o mouse sobre a barra e arraste-o para a direita ou esquerda.
. Para mover uma coluna, clique no cabeçalho da coluna e arraste-o para a direita ou esquerda.


Ao percorrer os resultados da consulta, esteja ciente de que os resultados podem mudar, pois o Data Infrastructure Insights pesquisa automaticamente seus coletores de dados.  Isso pode fazer com que alguns itens fiquem faltando ou apareçam fora de ordem, dependendo de como eles são classificados.
