---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Configurando o coletor de dados REST do Dell EMC Unisphere. 
---
= Configurando o coletor de dados REST do Dell EMC Unisphere
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados adquire dados de inventário e desempenho do Dell EMC Unisphere para sistemas de gerenciamento PowerMax/Vmax 3.

Observe que a Dell/EMC não introduziu estatísticas por volume até o Unisphere 10.0 - este coletor de dados é compatível com 9.2.0+, mas não poderá coletar estatísticas de volume, pois elas não existem.

Uma instância do Unisphere para Vmax/PowerMax pode estar gerenciando um ou mais arrays de armazenamento Symmetrix Vmax 3 ou superior. Esse coletor tentará, por padrão, descobrir todos eles que são "locais" para essa instância do Unisphere.  Se uma instância do Unisphere detectar matrizes "remotas" (ou seja, aquelas conectadas via replicação SRDF), elas serão ignoradas e, para descobri-las, você deve criar um coletor Unisphere adicional no Data Infrastructure Insights apontado para qualquer instância do Unisphere naquele site que as veja como locais.

Para configuração, o coletor de dados requer um endereço IP/FQDN do servidor Unisphere, conectividade TCP com a porta 8443 e um nome de usuário e senha.



== Requisitos

* Um endereço IP/Nome de domínio totalmente qualificado do servidor Unisphere
* Nome de usuário e senha
* Porta 8443.




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do servidor Unisphere | Endereço IP ou nome de domínio totalmente qualificado do servidor Unisphere 


| Porta Unisphere | O padrão é 8443 


| Nome de usuário | Nome de usuário para servidor Unisphere 


| Senha | Senha usada para o servidor Unisphere 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 40 minutos. 


| Intervalo de pesquisa de desempenho (seg) | Intervalo entre pesquisas de desempenho. 


| Escolha 'Excluir' ou 'Incluir' para especificar uma lista | Especifique se deseja incluir ou excluir VMs 


| Lista de dispositivos de filtro de inventário | Lista de VMs a serem filtradas (separadas por vírgula ou ponto e vírgula se a vírgula for usada no valor) para filtragem 


| Intervalo de pesquisa de desempenho do Unisphere (seg) | O padrão é 300 segundos 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Erro: Falha na autenticação do usuário. | Certifique-se de que suas credenciais para este dispositivo estejam corretas. 


| Status recente do inventário: Dados inesperados recuperados - Matriz relatou volume 0 | Geralmente indica um problema de autorização (não de autenticação).  Certifique-se de que suas credenciais estejam corretas e que o nome de usuário tenha o poder de listar todos os volumes e ver seus atributos. 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
