---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Inscrevendo-se no Data Infrastructure Insights e criando seu locatário. 
keywords: onboarding, new user 
---
= Integração de Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de começar a trabalhar com o Data Infrastructure Insights, você deve se inscrever no portal * NetApp Console*.  Se você já tiver um login no NetApp Console , poderá iniciar um teste gratuito do Data Infrastructure Insights com algumas etapas rápidas.



== Criando sua conta do NetApp Console

Para começar a usar os serviços de nuvem da NetApp, acesselink:https://console.netapp.com/["* NetApp Console*"^] e clique em *Começar*.

* Se você ainda não se inscreveu, selecione *Inscrever-se*
* Insira um endereço de e-mail comercial válido e escolha uma senha.
* Digite o nome da sua empresa e seu nome completo.
* Aceite os termos e condições e selecione *Continuar*.
* O console orientará você sobre como começar.




=== E se eu já tiver um login do NetApp Console ?

Depois de ter uma conta do NetApp Console , basta escolher *Fazer login* nolink:https://console.netapp.com/["* NetApp Console*"^] página do portal.

Digite seu endereço de e-mail e senha.  Você será levado para a página de ofertas de nuvem da NetApp.

Navegue até *Análise e Controle > Observabilidade* para saber mais sobre o Data Infrastructure Insights e/ou solicitar uma demonstração.



== Iniciando seu teste gratuito do Data Infrastructure Insights

Se esta for a sua primeira vez acessando o Data Infrastructure Insights, leia sobre tudo o que o Data Infrastructure Insights tem a oferecer e, quando estiver pronto para começar, clique em *Solicitar avaliação* e preencha suas informações.

Como parte da configuração do seu tenant de avaliação, você escolherá a região na qual seu tenant será hospedado e se deseja que ele esteja na AWS ou no Azure.

Após a conclusão da criação do seu locatário, use suas credenciais do Console para efetuar login e iniciar seu teste gratuito de 30 dias do Data Infrastructure Insights.  Durante este teste, você pode explorar os recursos que o Data Infrastructure Insights tem a oferecer.

Durante o teste gratuito, você podelink:concept_subscribing_to_cloud_insights.html["comece sua assinatura"] para o Data Infrastructure Insights a qualquer momento.  Ao assinar, você pode usar os recursos do Data Infrastructure Insights com base na sua assinatura atual.



== Sign in e vá

Depois que seu locatário for criado, a qualquer momento você pode simplesmente fazer login no NetApp Console Portal e navegar até olink:https://services.cloud.netapp.com["Serviços em Nuvem"] página e selecione *Ir para Data Infrastructure Insights*.

Você também pode abrir um navegador diretamente no URL do locatário do Data Infrastructure Insights , por exemplo:

 \https://<tenant-prefix>.c01.cloudinsights.netapp.com/
O URL também será incluído no e-mail de convite de cada usuário para facilitar o acesso e a marcação.  Se o usuário ainda não estiver conectado ao Console, ele será solicitado a fazer login.


NOTE: Novos usuários ainda precisam se inscrever para ter acesso ao Console antes de poderem acessar o URL do locatário.

Na primeira vez que você fizer login em um novo locatário, você será guiado pela configuraçãolink:task_getting_started_with_cloud_insights.html["*começa a coletar dados*"] .



== Saindo

Para sair do Data Infrastructure Insights, clique no seu *Nome de usuário* e selecione *Sair*.  Você será levado de volta para a tela de login do Console.


NOTE: Sair do Data Infrastructure Insights desconecta você do Console.  Você também será desconectado de outros serviços do NetApp Cloud que usam o login do Console.



=== Tempo limite de inatividade

Por padrão, o Console desconectará o usuário se não houver atividade por seis horas (360 minutos).  Independentemente da atividade, os usuários serão desconectados após sete dias.
