---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Configurando o coletor de dados CDM da Rubrik. 
---
= Coletor de dados CDM da Rubrik
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados da Rubrik para adquirir dados de inventário e desempenho de dispositivos de storage da Rubrik.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados da Rubrik. Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desse coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo do fornecedor/modelo | Termo do Insights de infraestrutura de dados 


| Cluster | Armazenamento, pool de armazenamento 


| Nó | Nó de storage 


| Disco | Disco 
|===
Nota: Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para esta fonte de dados.



== Requisitos

Para configurar este coletor de dados, são necessários os seguintes itens:

* A Unidade de aquisição do Data Infrastructure Insights iniciará conexões com a porta TCP 443 para o cluster Rubrik. Um coletor por cluster.
* Endereço IP do cluster da Rubrik.
* Nome de utilizador e palavra-passe para o cluster.
* Endereço IP ou nome do host do cluster Rubrik.
* Para Autenticação básica, um nome de usuário e uma senha para o cluster. Se você preferir usar a autenticação baseada em conta de Serviço, precisará de uma conta de Serviço, segredo e um ID de Organização
* Requisito de porta: HTTPS 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| IP | Endereço IP do cluster Rubrik 


| Nome de utilizador | Nome de utilizador para o cluster 


| Palavra-passe | Palavra-passe para o cluster 
|===


== Configuração avançada

[cols="2*"]
|===
| Intervalo de pesquisa de inventário (min) | A predefinição é 60 


| Intervalo de enquete de desempenho (seg) | A predefinição é 300 
|===


== Solução de problemas

Algumas coisas para tentar se você encontrar problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Tente isto: 


| Recebi uma mensagem informando que mais de um armazenamento foi criado. | Verifique se o cluster está configurado corretamente e se o coletor está apontando para um único cluster. 


| Recebi um aviso de que a API de disco retornou mais dados | Consulte o suporte para obter dados adicionais. 
|===
Informações adicionais podem ser encontradas na link:concept_requesting_support.html["Suporte"] página ou no link:reference_data_collector_support_matrix.html["Matriz de suporte do Data Collector"].
