---
sidebar: sidebar 
permalink: task_dc_amazon_ec2.html 
keywords: data collector, EC2, 
summary: Configurando o coletor de dados do Amazon EC2. 
---
= Configurando o coletor de dados do Amazon EC2
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados do Amazon EC2 para adquirir dados de inventário e desempenho de instâncias do EC2.



== Requisitos

Para coletar dados de dispositivos Amazon EC2, você precisa ter as seguintes informações:

* Você deve ter um dos seguintes:
+
** A *Função do IAM* para sua conta de nuvem Amazon EC2, se estiver usando a Autenticação de Função do IAM.  A função do IAM só se aplica se sua unidade de aquisição estiver instalada em uma instância da AWS.
** O ID da *Chave de Acesso do IAM* e a Chave de Acesso Secreta para sua conta de nuvem Amazon EC2, se estiver usando a autenticação da Chave de Acesso do IAM.


* Você deve ter o privilégio "listar organização"
* Porta 443 HTTPS
* Instâncias do EC2 podem ser relatadas como uma Máquina Virtual ou (menos naturalmente) um Host.  Os volumes do EBS podem ser relatados como um VirtualDisk usado pela VM, bem como um DataStore que fornece a capacidade para o VirtualDisk.


As chaves de acesso consistem em um ID de chave de acesso (por exemplo, AKIAIOSFODNN7EXAMPLE) e uma chave de acesso secreta (por exemplo, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY).  Você usa chaves de acesso para assinar solicitações programáticas feitas ao EC2 se usar os SDKs do Amazon EC2, REST ou operações da API de consulta.  Essas chaves são fornecidas com seu contrato da Amazon.



== Configuração

Insira os dados nos campos do coletor de dados de acordo com a tabela abaixo:

[cols="2*"]
|===
| Campo | Descrição 


| Região da AWS | Escolha a região da AWS 


| Função IAM | Para uso somente quando adquirido em uma AU na AWS.  Veja abaixo mais informações sobre<<iam-role,Função IAM>> . 


| ID da chave de acesso do AWS IAM | Insira o ID da chave de acesso do AWS IAM.  Obrigatório se você não usar a função IAM. 


| Chave de acesso secreta do AWS IAM | Digite a chave de acesso secreta do AWS IAM.  Obrigatório se você não usar a função IAM. 


| Entendo que a AWS me cobra por solicitações de API | Marque esta opção para verificar se você entendeu que a AWS cobra por solicitações de API feitas pela pesquisa do Data Infrastructure Insights . 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Incluir regiões extras | Especifique regiões adicionais para incluir na votação. 


| Função de contas cruzadas | Função para acessar recursos em diferentes contas da AWS. 


| Intervalo de pesquisa de inventário (min) | O padrão é 60 


| Selecione 'Excluir' ou 'Incluir' para aplicar ao filtro VMs por tags | Especifique se deseja incluir ou excluir VMs por tags ao coletar dados.  Se "Incluir" for selecionado, o campo Chave da tag não poderá ficar vazio. 


| Chaves e valores de tags para filtrar VMs | Clique em *+ Filtrar tag* para escolher quais VMs (e discos associados) incluir/excluir, filtrando por chaves e valores que correspondem às chaves e valores das tags na VM.  A chave da tag é obrigatória, o valor da tag é opcional.  Quando o valor da tag estiver vazio, a VM será filtrada, desde que corresponda à chave da tag. 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 1800 


| Namespace de métricas do agente CloudWatch | Namespace no EC2/EBS do qual coletar dados.  Observe que, se os nomes das métricas padrão neste namespace forem alterados, o Data Infrastructure Insights poderá não conseguir coletar os dados renomeados.  É recomendável deixar os nomes de métricas padrão. 
|===


== Chave de acesso IAM

As chaves de acesso são credenciais de longo prazo para um usuário do IAM ou o usuário raiz da conta da AWS.  As chaves de acesso são usadas para assinar solicitações programáticas para a AWS CLI ou a AWS API (diretamente ou usando o AWS SDK).

As chaves de acesso consistem em duas partes: um ID de chave de acesso e uma chave de acesso secreta.  Ao usar a autenticação _Chave de acesso do IAM_ (em oposição à autenticação _Função do IAM_), você deve usar o ID da chave de acesso e a chave de acesso secreta juntos para autenticação de solicitações.  Para obter mais informações, consulte a documentação da Amazon emlink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["Chaves de acesso"] .



== Função IAM

Ao usar a autenticação _IAM Role_ (em oposição à autenticação IAM Access Key), você deve garantir que a função criada ou especificada tenha as permissões apropriadas necessárias para acessar seus recursos.

Por exemplo, se você criar uma função do IAM chamada _InstanceEc2ReadOnly_, deverá configurar a política para conceder permissão de acesso somente leitura à lista do EC2 para todos os recursos do EC2 para essa função do IAM.  Além disso, você deve conceder acesso ao STS (Security Token Service) para que essa função possa assumir funções entre contas.

Depois de criar uma função do IAM, você pode anexá-la ao criar uma nova instância do EC2 ou qualquer instância existente do EC2.

Depois de anexar a função do IAM _InstanceEc2ReadOnly_ a uma instância do EC2, você poderá recuperar a credencial temporária por meio de metadados da instância pelo nome da função do IAM e usá-la para acessar recursos da AWS por qualquer aplicativo em execução nessa instância do EC2.

Para mais informações, consulte a documentação da Amazon emlink:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["Funções do IAM"] .

Observação: a função do IAM pode ser usada somente quando a Unidade de Aquisição estiver em execução em uma instância da AWS.



== Mapeando tags da Amazon para anotações do Data Infrastructure Insights

O coletor de dados do Amazon EC2 inclui uma opção que permite preencher anotações do Data Infrastructure Insights com tags configuradas no EC2.  As anotações devem ser nomeadas exatamente como as tags EC2.  O Data Infrastructure Insights sempre preencherá anotações de mesmo tipo de texto e fará o "melhor esforço" para preencher anotações de outros tipos (número, booleano, etc.).  Se sua anotação for de um tipo diferente e o coletor de dados não conseguir preenchê-la, pode ser necessário remover a anotação e recriá-la como um tipo de texto.

Observe que a AWS diferencia maiúsculas de minúsculas, enquanto o Data Infrastructure Insights não diferencia maiúsculas de minúsculas.  Portanto, se você criar uma anotação chamada "OWNER" no Data Infrastructure Insights e tags chamadas "OWNER", "Owner" e "owner" no EC2, todas as variações de "owner" do EC2 serão mapeadas para a anotação "OWNER" do Cloud Insight.



== Incluir regiões extras

Na seção *Configuração avançada* do AWS Data Collector, você pode definir o campo *Incluir regiões extras* para incluir regiões adicionais, separadas por vírgula ou ponto e vírgula.  Por padrão, este campo é definido como *_us-.*_*, que coleta dados em todas as regiões da AWS dos EUA.  Para coletar em _todas_ as regiões, defina este campo como *_.*_*.  Se o campo *Incluir regiões extras* estiver vazio, o coletor de dados coletará os ativos especificados no campo *Região da AWS*, conforme especificado na seção *Configuração*.



== Coletando de contas filhas da AWS

O Data Infrastructure Insights oferece suporte à coleta de contas filhas para a AWS em um único coletor de dados da AWS.  A configuração desta coleção é realizada no ambiente AWS:

* Você deve configurar cada conta filha para ter uma função da AWS que permita que o ID da conta principal acesse os detalhes do EC2 da conta filha.
* Cada conta infantil deve ter o nome da função configurado como a mesma sequência de caracteres.
* Insira esta sequência de caracteres de nome de função na seção *Configuração avançada* do Data Infrastructure Insights AWS Data Collector, no campo *Função entre contas*.
* A conta onde o coletor está instalado precisa ter privilégios de _administrador de acesso delegado_.  Veja olink:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["Documentação da AWS"] para mais informações.


Prática recomendada: É altamente recomendável atribuir a política predefinida _AmazonEC2ReadOnlyAccess_ da AWS à conta principal do EC2.  Além disso, o usuário configurado na fonte de dados deve ter pelo menos a política predefinida _AWSOrganizationsReadOnlyAccess_ atribuída para consultar a AWS.

Consulte o seguinte para obter informações sobre como configurar seu ambiente para permitir que o Data Infrastructure Insights colete dados de contas filhas da AWS:

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["Tutorial: Delegar acesso entre contas da AWS usando funções do IAM"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["Configuração da AWS: fornecendo acesso a um usuário do IAM em outra conta da AWS de sua propriedade"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Criando uma função para delegar permissões a um usuário do IAM"]



== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
