---
sidebar: sidebar 
permalink: task_dc_pure_flasharray.html 
keywords: data collector, Pure Storage, pure 
summary: Configurando o coletor de dados do Pure Storage. 
---
= Coletor de dados Pure Storage FlashArray
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados Pure Storage FlashArray para coletar dados de inventário e desempenho.



== Terminologia

Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para o ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Unidade (SSD) | Disco 


| Variedade | Armazenar 


| Controlador | Nó de armazenamento 


| Volume | Volume 


| Mapa LUN | Mapa de Volume 


| Iniciador, Alvo | Máscara de Volume 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Endereço IP do sistema de armazenamento
* Nome de usuário e senha para a conta de administrador do sistema de armazenamento Pure.
* Requisito de porta: HTTP/HTTPS 80/443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do host FlashArray | Endereço IP do sistema de armazenamento 


| Nome de usuário | Nome de usuário com privilégios de administrador 


| Senha para a conta privilegiada de administrador | Senha 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Tipo de conexão | Escolha HTTP ou HTTPS.  Também exibe a porta padrão. 


| Substituir porta TCP | Se estiver em branco, use a porta padrão no campo Tipo de conexão, caso contrário, insira a porta de conexão a ser usada 


| Intervalo de pesquisa de inventário (min) | O padrão é 60 minutos 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 300 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| “Credenciais de login inválidas” com mensagens de erro “A política não permite” ou “Você não está autorizado” | Validar conta de usuário e senha Pure via interface http Pure 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
