---
sidebar: sidebar 
permalink: task_research_failed_collector.html 
keywords: data collector, changes, failures 
summary: Erros do coletor de dados 
---
= Pesquisando um coletor de dados com falha
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Se um coletor de dados tiver uma mensagem de falha e um Impacto Alto ou Médio, você precisará pesquisar esse problema usando a página de resumo do coletor de dados com suas informações vinculadas.

Use as etapas a seguir para determinar a causa de coletores de dados com falha.  Mensagens de falha do coletor de dados são exibidas no menu *Admin* e na página *Coletores de dados instalados*.

.Passos
. Clique em *Admin* > *Coletores de dados* > *Coletores de dados instalados*.
. Clique no Nome vinculado do coletor de dados com falha para abrir a página Resumo.
. Na página Resumo, verifique a área Comentários para ler quaisquer notas que possam ter sido deixadas por outro engenheiro que também possa estar investigando esta falha.
. Anote todas as mensagens de desempenho.
. Mova o ponteiro do mouse sobre os segmentos do gráfico da Linha do Tempo do Evento para exibir informações adicionais.
. Selecione uma mensagem de erro para um dispositivo exibida abaixo da Linha do tempo do evento e clique no ícone Detalhes do erro exibido à direita da mensagem.
+
Os detalhes do erro incluem o texto da mensagem de erro, as causas mais prováveis, as informações em uso e sugestões do que pode ser tentado para corrigir o problema.

. Na área Dispositivos relatados por este coletor de dados, você pode filtrar a lista para exibir apenas dispositivos de interesse e pode clicar no *Nome* vinculado de um dispositivo para exibir a página de ativos desse dispositivo.
. Ao retornar à página de resumo do coletor de dados, verifique a área *Mostrar alterações recentes* na parte inferior da página para ver se alterações recentes podem ter causado o problema.

