---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'Configurando o coletor de dados HDS NAS (HNAS).' 
---
= Configurando o coletor de dados do NAS Hitachi Vantara
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados Hitachi Vantara NAS é um coletor de dados de inventário e configuração que oferece suporte à descoberta de clusters HDS NAS.  O Data Infrastructure Insights oferece suporte à descoberta de compartilhamentos NFS e CIFS, sistemas de arquivos (volumes internos) e intervalos (pools de armazenamento).



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados HNAS.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Nível | Grupo de Discos 


| Conjunto | Armazenar 


| Nó | Nó de armazenamento 


| Extensão | Pool de armazenamento 


| Unidade do sistema | Lun de backend 


| Sistema de arquivos | Volume interno 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Endereço IP do dispositivo
* Porta 22, protocolo SSH
* Nome de usuário e senha - nível de privilégio: Supervisor
* Observação: este coletor de dados é baseado em SSH, portanto, a UA que o hospeda deve ser capaz de iniciar sessões SSH para TCP 22 no próprio HNAS ou na Unidade de Gerenciamento de Sistemas (SMU) à qual o cluster está conectado.




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Anfitrião HNAS | Endereço IP ou nome de domínio totalmente qualificado do Host de Gerenciamento HNAS 


| Nome de usuário | Nome de usuário para HNAS CLI 


| Senha | Senha usada para HNAS CLI 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 30 minutos. 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| “Erro de conexão” com mensagens de erro “Erro ao configurar o canal do shell” ou “Erro ao abrir o canal do shell” | Provavelmente causado por problemas de conectividade de rede ou SSH configurado incorretamente.  Confirme a conexão com o cliente SSH alternativo 


| "Tempo limite" ou "Erro ao recuperar dados" com mensagens de erro "Comando: XXX expirou." | * Tente o comando com um cliente SSH alternativo * Aumente o tempo limite 


| "Erro de conexão" ou "Credenciais de login inválidas" com mensagens de erro "Não foi possível se comunicar com o dispositivo": | * Verifique o endereço IP * Verifique o nome de usuário e a senha * Confirme a conexão com o cliente SSH alternativo 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
