---
sidebar: sidebar 
permalink: task_dc_lenovo.html 
keywords: data collector,Lenovo, HX Series 
summary: Configurando o coletor de dados Lenovo. 
---
= Coletor de dados Lenovo
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados da Lenovo para descobrir dados de inventário e desempenho para sistemas de armazenamento Lenovo HX.

Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Endereço IP externo do Prism
* Nome de usuário e senha do administrador
* Requisito de porta TCP: 9440




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP externo do Prism | O endereço IP dos serviços de dados externos para o cluster 


| Nome de usuário | Nome de usuário para a conta de administrador 


| Senha | Senha para a conta de administrador 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta TCP usada para conectar ao array.  O padrão é 9440. 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 


| Intervalo de pesquisa de desempenho (seg) | Intervalo entre pesquisas de desempenho. O padrão é 300 segundos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
