---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers, Cloud Secure 
summary: Implante agentes de segurança de carga de trabalho e coletores de dados para monitorar a atividade do usuário e detectar ameaças à segurança. 
---
= Introdução à segurança da carga de trabalho
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Workload Security ajuda você a monitorar a atividade do usuário e detectar possíveis ameaças à segurança em seu ambiente de armazenamento.  Antes de iniciar o monitoramento, é necessário configurar agentes, coletores de dados e serviços de diretório para estabelecer a base para um monitoramento de segurança abrangente.

O sistema de segurança de carga de trabalho usa um agente para coletar dados de acesso de sistemas de armazenamento e informações de usuários de servidores de serviços de diretório.

Você precisa configurar o seguinte antes de começar a coletar dados:

[cols="2*"]
|===


| Tarefa | Informações relacionadas 


| Configurar um agente  a| 
link:concept_cs_agent_requirements.html["Requisitos do agente"]

link:task_cs_add_agent.html["Adicionar agente"]



| Configurar um conector de diretório de usuário | link:task_config_user_dir_connect.html["Adicionar conector de diretório de usuário"] 


| Configurar coletores de dados | Clique em *Segurança de carga de trabalho > Coletores* Clique no coletor de dados que deseja configurar. Consulte a seção "Referência do Fornecedor do Coletor de Dados" na documentação para obter informações sobre o coletor. 


| Criar contas de usuários | link:concept_user_roles.html["Gerenciar contas de usuário"] 
|===
O Workload Security também pode ser integrado a outras ferramentas.  Por exemplo,link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["veja este guia"] sobre integração com o Splunk.
