---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: Coletor de dados de ONTAP 
---
= Coletor de dados do software de gerenciamento de dados NetApp ONTAP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados adquire dados de inventário e desempenho de sistemas de armazenamento que executam o ONTAP usando chamadas de API somente leitura de uma conta ONTAP .  Este coletor de dados também cria um registro no registro do aplicativo de cluster para acelerar o suporte.



== Terminologia

O Data Infrastructure Insights adquire dados de inventário e desempenho do coletor de dados ONTAP .  Para cada tipo de ativo adquirido, é mostrada a terminologia mais comum usada para o ativo.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco 


| Grupo de ataque | Grupo de Discos 


| Conjunto | Armazenar 


| Nó | Nó de armazenamento 


| Agregar | Pool de armazenamento 


| LUN | Volume 


| Volume | Volume interno 
|===


== Terminologia de gerenciamento de dados ONTAP

Os termos a seguir se aplicam a objetos ou referências que você pode encontrar nas páginas de destino de ativos de armazenamento do ONTAP Data Management.  Muitos desses termos também se aplicam a outros coletores de dados.



=== Armazenar

* Modelo – Uma lista delimitada por vírgulas de nomes exclusivos e discretos de modelos de nós dentro deste cluster.  Se todos os nós nos clusters forem do mesmo tipo de modelo, apenas um nome de modelo aparecerá.
* Fornecedor – o mesmo nome de fornecedor que você veria se estivesse configurando uma nova fonte de dados.
* Número de série – O número de série do array.  Em sistemas de armazenamento de arquitetura de cluster, como o ONTAP Data Management, esse número de série pode ser menos útil do que os números de série individuais dos “Nós de Armazenamento”.
* IP – geralmente será o(s) IP(s) ou nome(s) de host conforme configurado na fonte de dados.
* Versão do microcódigo – firmware.
* Capacidade bruta – soma de base 2 de todos os discos físicos no sistema, independentemente de sua função.
* Latência – uma representação do que as cargas de trabalho do host estão enfrentando, tanto em leituras quanto em gravações.  O ideal seria que o Data Infrastructure Insights obtivesse esse valor diretamente, mas isso nem sempre acontece.  Em vez de a matriz oferecer isso, o Data Infrastructure Insights geralmente executa um cálculo ponderado por IOPs derivado das estatísticas dos volumes internos individuais.
* Taxa de transferência – agregada de volumes internos.  Gerenciamento – pode conter um hiperlink para a interface de gerenciamento do dispositivo.  Criado programaticamente pela fonte de dados do Data Infrastructure Insights como parte do relatório de inventário.




=== Pool de armazenamento

* Armazenamento – em qual matriz de armazenamento esse pool reside.  Obrigatório.
* Tipo – um valor descritivo de uma lista de possibilidades enumeradas.  O mais comum será “Agregado” ou “Grupo RAID”.
* Nó – se a arquitetura deste conjunto de armazenamento for tal que os pools pertençam a um nó de armazenamento específico, seu nome será visto aqui como um hiperlink para sua própria página de destino.
* Utiliza Flash Pool – Valor Sim/Não – este pool baseado em SATA/SAS tem SSDs usados para aceleração de cache?
* Redundância – nível RAID ou esquema de proteção.  RAID_DP é paridade dupla, RAID_TP é paridade tripla.
* Capacidade – os valores aqui são a capacidade lógica utilizada, a capacidade utilizável e a capacidade lógica total, além da porcentagem utilizada entre elas.
* Capacidade superalocada – Se, ao usar tecnologias de eficiência, você tiver alocado uma soma total de capacidades de volume ou volume interno maior que a capacidade lógica do pool de armazenamento, o valor percentual aqui será maior que 0%.
* Snapshot – capacidades de snapshot usadas e totais, se a arquitetura do seu pool de armazenamento dedicar parte de sua capacidade a áreas de segmentos exclusivamente para snapshots.  ONTAP em configurações MetroCluster provavelmente exibirá isso, enquanto outras configurações ONTAP são menos propensas a isso.
* Utilização – um valor percentual que mostra a maior porcentagem de ocupação de disco de qualquer disco que contribui com capacidade para este pool de armazenamento.  A utilização do disco não tem necessariamente uma forte correlação com o desempenho do array – a utilização pode ser alta devido a reconstruções de disco, atividades de desduplicação, etc. na ausência de cargas de trabalho controladas pelo host.  Além disso, muitas implementações de replicação de matrizes podem direcionar a utilização do disco sem serem exibidas como volume interno ou carga de trabalho de volume.
* IOPS – a soma de IOPS de todos os discos que contribuem com capacidade para este pool de armazenamento.  Taxa de transferência – a soma da taxa de transferência de todos os discos que contribuem com capacidade para esse pool de armazenamento.




=== Nó de armazenamento

* Armazenamento – de qual matriz de armazenamento esse nó faz parte.  Obrigatório.
* Parceiro HA – em plataformas onde um nó fará failover para apenas um outro nó, geralmente será visto aqui.
* Estado – saúde do nó.  Disponível somente quando o array estiver saudável o suficiente para ser inventariado por uma fonte de dados.
* Modelo – nome do modelo do nó.
* Versão – nome da versão do dispositivo.
* Número de série – O número de série do nó.
* Memória – memória base 2, se disponível.
* Utilização – No ONTAP, este é um índice de estresse do controlador de um algoritmo proprietário.  Em cada pesquisa de desempenho, um número entre 0 e 100% será relatado, que é o maior entre a contenção de disco WAFL ou a utilização média da CPU.  Se você observar valores sustentados > 50%, isso é indicativo de subdimensionamento – possivelmente um controlador/nó não grande o suficiente ou discos giratórios insuficientes para absorver a carga de trabalho de gravação.
* IOPS – Derivado diretamente de chamadas ONTAP ZAPI no objeto de nó.
* Latência – Derivada diretamente de chamadas ONTAP ZAPI no objeto de nó.
* Taxa de transferência – Derivado diretamente de chamadas ONTAP ZAPI no objeto de nó.
* Processadores – contagem de CPU.




== Requisitos

A seguir estão os requisitos para configurar e usar este coletor de dados:

* Você deve ter acesso a uma conta de administrador configurada para chamadas de API somente leitura.
* Os detalhes da conta incluem nome de usuário e senha.
* Requisitos de porta: 80 ou 443
* Permissões da conta:
+
** Nome da função somente leitura para o aplicativo ontapi no Vserver padrão
** Você pode precisar de permissões de gravação opcionais adicionais.  Veja a Nota sobre permissões abaixo.


* Requisitos da licença ONTAP :
+
** Licença FCP e volumes mapeados/mascarados necessários para descoberta de canal de fibra






=== Requisitos de permissão para coletar métricas do switch ONTAP

O Data Infrastructure Insights tem a capacidade de coletar dados de switch de cluster ONTAP como uma opção no coletor<<advanced-configuration,Configuração avançada>> configurações.  Além de habilitar isso no coletor Data Infrastructure Insights , você também deve *configurar o próprio sistema ONTAP * para fornecerlink:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["informações de troca"] , e garantir a correta<<a-note-about-permissions,permissões>> são definidos para permitir que os dados do switch sejam enviados ao Data Infrastructure Insights.



== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| IP de gerenciamento da NetApp | Endereço IP ou nome de domínio totalmente qualificado do cluster NetApp 


| Nome de usuário | Nome de usuário para cluster NetApp 


| Senha | Senha para cluster NetApp 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Tipo de conexão | Escolha HTTP (porta padrão 80) ou HTTPS (porta padrão 443).  O padrão é HTTPS 


| Substituir porta de comunicação | Especifique uma porta diferente se não quiser usar a porta padrão 


| Intervalo de pesquisa de inventário (min) | O padrão é 60 minutos. 


| Para TLS para HTTPS | Permitir somente TLS como protocolo ao usar HTTPS 


| Pesquisar Netgroups Automaticamente | Habilitar pesquisas automáticas de netgroup para regras de política de exportação 


| Expansão do Netgroup | Estratégia de expansão do Netgroup.  Escolha _file_ ou _shell_.  O padrão é _shell_. 


| Tempo limite de leitura HTTP em segundos | O padrão é 30 


| Respostas de força como UTF-8 | Força o código do coletor de dados a interpretar as respostas da CLI como sendo em UTF-8 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 900 segundos. 


| Coleta Avançada de Dados de Contagem | Habilitar integração ONTAP .  Selecione esta opção para incluir dados do contador avançado ONTAP nas pesquisas.  Escolha os contadores desejados na lista. 


| Métricas de troca de cluster | Permitir que o Data Infrastructure Insights colete dados de switch de cluster.  Observe que, além de habilitar isso no lado do Data Infrastructure Insights , você também deve configurar o sistema ONTAP para fornecerlink:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["informações de troca"] , e garantir a correta<<a-note-about-permissions,permissões>> são definidos para permitir que os dados do switch sejam enviados ao Data Infrastructure Insights.  Veja "Uma nota sobre permissões" abaixo. 
|===


== Métricas de potência ONTAP

Vários modelos ONTAP fornecem métricas de energia para o Data Infrastructure Insights que podem ser usadas para monitoramento ou alertas.


NOTE: Essas listas não são abrangentes e estão sujeitas a alterações.  Em geral, se um modelo estiver na mesma família de um da lista, o suporte deverá ser o mesmo, mas não há garantia de que isso aconteça.  Se você não tiver certeza se seu modelo suporta métricas de energia, entre em contato com o suporte do ONTAP .

Modelos suportados:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

Modelos não suportados:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== Uma nota sobre permissões

Como vários painéis ONTAP do Data Infrastructure Insights dependem de contadores ONTAP avançados, você deve habilitar *Coleta avançada de dados de contadores* na seção Configuração avançada do coletor de dados.

Você também deve garantir que a permissão de gravação na API ONTAP esteja habilitada.  Isso normalmente requer uma conta no nível do cluster com as permissões necessárias.

Para criar uma conta local para o Data Infrastructure Insights no nível do cluster, faça login no ONTAP com o nome de usuário/senha do Administrador de gerenciamento do cluster e execute os seguintes comandos no servidor ONTAP :

. Antes de começar, você deve estar conectado ao ONTAP com uma conta de _Administrador_ e os _comandos de nível de diagnóstico_ devem estar habilitados.
. Crie uma função somente leitura usando os seguintes comandos.
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
....
. Crie o usuário somente leitura usando o seguinte comando.  Depois de executar o comando create, você será solicitado a digitar uma senha para este usuário.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


Se a conta AD/LDAP for usada, o comando deve ser

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
Se você estiver coletando dados de switch de cluster:

....
security login rest-role create -role ci_readonly_rest -api /api/network/ethernet -access readonly
security login create -user-or-group-name ci_user -application http -authmethod password -role ci_readonly_rest
....
A função e o login do usuário resultantes serão semelhantes aos seguintes.  Sua produção real pode variar:

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1:security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....

NOTE: Se o controle de acesso ONTAP não estiver definido corretamente, as chamadas REST do Data Infrastructure Insights poderão falhar, resultando em lacunas nos dados do dispositivo.  Por exemplo, se você o tiver habilitado no coletor do Data Infrastructure Insights, mas não tiver configurado as permissões no ONTAP, a aquisição falhará.  Além disso, se a função estiver definida anteriormente no ONTAP e você estiver adicionando os recursos da API Rest, certifique-se de que _http_ seja adicionado à função.



== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Receber resposta HTTP 401 ou código de erro ZAPI 13003 e ZAPI retorna “Privilégios insuficientes” ou “não autorizado para este comando” | Verifique o nome de usuário e a senha, além dos privilégios/permissões do usuário. 


| A versão do cluster é < 8.1 | A versão mínima suportada do cluster é 8.1.  Atualize para a versão mínima suportada. 


| ZAPI retorna "a função do cluster não é cluster_mgmt LIF" | A AU precisa se comunicar com o IP de gerenciamento do cluster.  Verifique o IP e altere para um IP diferente, se necessário 


| Erro: “Os filtros de modo 7 não são suportados” | Isso pode acontecer se você usar este coletor de dados para descobrir o filtro de modo 7.  Altere o IP para apontar para o cluster cdot. 


| O comando ZAPI falha após nova tentativa | AU tem problema de comunicação com o cluster.  Verifique a rede, o número da porta e o endereço IP.  O usuário também deve tentar executar um comando da linha de comando da máquina AU. 


| AU falhou ao conectar ao ZAPI via HTTP | Verifique se a porta ZAPI aceita texto simples.  Se o AU tentar enviar texto simples para um soquete SSL, a comunicação falhará. 


| Falha na comunicação com SSLException | AU está tentando enviar SSL para uma porta de texto simples em um arquivador.  Verifique se a porta ZAPI aceita SSL ou use uma porta diferente. 


| Erros de conexão adicionais: a resposta ZAPI tem o código de erro 13001, “o banco de dados não está aberto”. O código de erro ZAPI é 60 e a resposta contém “a API não terminou no prazo”. A resposta ZAPI contém “initialize_session() retornou um ambiente NULL”. O código de erro ZAPI é 14007 e a resposta contém “o nó não está íntegro”. | Verifique a rede, o número da porta e o endereço IP.  O usuário também deve tentar executar um comando da linha de comando da máquina AU. 
|===


=== Desempenho

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Erro “Falha ao coletar desempenho do ZAPI” | Isso geralmente ocorre porque o perf stat não está em execução.  Tente o seguinte comando em cada nó: > _system node systemshell -node * -command “spmctl -h cmd –stop; spmctl -h cmd –exec”_ 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
