---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Configurando o coletor de dados do Oracle ZFS. 
---
= Coletor de dados do Oracle ZFS Storage Appliance
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados do Oracle ZFS Storage Appliance para coletar dados de inventário e desempenho.



== Terminologia

O Data Infrastructure Insights adquire informações de inventário com o coletor de dados Oracle ZFS.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco (SSD) | Disco 


| Conjunto | Armazenar 


| Controlador | Nó de armazenamento 


| LUN | Volume 


| Mapa LUN | Mapa de Volume 


| Iniciador, Alvo | Máscara de Volume 


| Compartilhar | Volume interno 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos desta fonte de dados.



== Requisitos

* Nomes de host para o ZFS Controller-1 e o ZFS Controller-2
* Nome de usuário e senha do administrador
* Requisito de porta: 215 HTTP/HTTPS




== Métricas de desempenho necessárias

Os dispositivos Oracle ZFS oferecem aos administradores de armazenamento grande flexibilidade para capturar estatísticas de desempenho.  O Data Infrastructure Insights espera que você tenha _cada_ controlador em um par de alta disponibilidade configurado para capturar as seguintes métricas:

* smb2.ops[compartilhar]
* nfs3.ops[compartilhar]
* nfs4.ops[compartilhar]
* nfs4-1.ops[compartilhar]


A falha em fazer com que o controlador capture qualquer um ou todos esses dados provavelmente fará com que o Data Infrastructure Insights não tenha, ou subnotifique, a carga de trabalho nos "Volumes Internos".



== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Nome do host do controlador ZFS-1 | Nome do host para o controlador de armazenamento 1 


| Nome do host do controlador ZFS-2 | Nome do host para o controlador de armazenamento 2 


| Nome de usuário | Nome de usuário para a conta de usuário do administrador do sistema de armazenamento 


| Senha | Senha para a conta de usuário administrador 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Tipo de conexão | HTTPS ou HTTP, também exibe a porta padrão 


| Substituir porta de conexão | Se estiver em branco, use a porta padrão no campo Tipo de conexão, caso contrário, insira a porta de conexão a ser usada 


| Intervalo de pesquisa de inventário | O padrão é 60 segundos 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 300. 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2a, 2a"]
|===
| Problema: | Experimente isto: 


 a| 
"Credenciais de login inválidas"
 a| 
validar conta de usuário e senha do ZFS



 a| 
"Falha na solicitação com status 404 \https://.....:215/api/access/v1"
 a| 
Seu array ZFS pode ser muito antigo para ter suporte à API REST.  O AK 2013.1.3.0 foi o primeiro lançamento do sistema operacional ZFS compatível com REST API, e nem todos os dispositivos ZFS podem ser atualizados para ele.



 a| 
"Erro de configuração" com mensagem de erro “Serviço REST desabilitado”
 a| 
Verifique se o serviço REST está habilitado neste dispositivo.



 a| 
“Erro de configuração” com mensagem de erro “Usuário não autorizado para comando”
 a| 
Esse erro provavelmente ocorre porque certas funções (por exemplo, 'advanced_analytics') não estão incluídas para o usuário configurado.

Aplicar o escopo do Analytics ao usuário com função somente leitura pode remover o erro. Siga estes passos:

. No sistema ZFs, na tela Configuração -> Usuários, mova o mouse sobre a função e clique duas vezes para permitir a edição
. Selecione "Análise" no menu suspenso Escopo.  Uma lista das propriedades possíveis é exibida.
. Clique na caixa de seleção mais acima e ela selecionará todas as três propriedades.
. Clique no botão Adicionar no lado direito.
. Clique no botão Aplicar no canto superior direito da janela pop-up.  A janela pop-up será fechada.


|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
