---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: Configurando o coletor de dados DELL EMC ScaleIO/PowerFlex. 
---
= Coletor de dados DELL EMC ScaleIO / PowerFlex
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados ScaleIO/PowerFlex coleta informações de inventário do armazenamento ScaleIO e PowerFlex.  Para configuração, este coletor de dados requer o endereço do gateway ScaleIO/PowerFlex e um nome de usuário e senha de administrador.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados ScaleIO/PowerFlex.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Cluster MDM (Gerenciador de Metadados) | Armazenar 


| SDS (Servidor de Dados ScaleIO/PowerFlex) | Nó de armazenamento 


| Pool de armazenamento | Pool de armazenamento 


| Volume | Volume 


| Dispositivo | Disco 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Acesso somente leitura à conta de usuário Admin
* Requisito de porta: HTTPS Porta 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Gateway(s) ScaleIO/PowerFlex | Endereços IP ou FQDNs de gateways ScaleIO/PowerFlex, separados por vírgula (,) ou ponto e vírgula (;) 


| Nome de usuário | Nome de usuário administrador usado para efetuar login no dispositivo ScaleIO/PowerFlex 


| Senha | Senha usada para efetuar login no dispositivo ScaleIO/PowerFlex 
|===


== Configuração avançada

Clique na caixa de seleção Inventário para habilitar a coleta de inventário.

[cols="2*"]
|===
| Campo | Descrição 


| Porta HTTPS | 443 


| Intervalo de pesquisa de inventário (min) | O padrão é 60. 


| Tempo limite de conexão (seg) | O padrão é 60. 
|===


== Solução de problemas

Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
