---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: Anotações de Entidades Comerciais podem ser usadas para monitorar e relatar ativos na hierarquia de sua empresa 
---
= Anotações de Entidades Comerciais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Crie e gerencie entidades comerciais para seu ambiente corporativo usando o tipo de anotação *Entidade Comercial*.



== Criando uma Entidade Empresarial

Para criar uma entidade empresarial, faça o seguinte:

. Clique em *Gerenciar > Anotações* e clique no link _Entidade Comercial_.
+
A lista de entidades comerciais definidas atualmente é exibida.

. Clique em *+ Entidade Comercial*.
. Insira valores para os campos *Locatário*, *Linha de negócios*, *Unidade de negócios* e *Projeto*.
+
Você pode deixar qualquer campo vazio se ele não se aplicar à sua entidade comercial.

. Se você já inseriu um valor para um campo, pode selecionar esse valor no menu suspenso.  Não é necessário digitar novamente.



NOTE: Os valores selecionados devem compor uma entidade empresarial total exclusiva.  Por exemplo, se você já tiver uma entidade comercial com os valores _A / B / C / D_ nessa ordem, não poderá criar outra entidade comercial com esses valores nessa ordem.  No entanto, você pode criar uma entidade comercial com esses valores em uma ordem diferente.



== Aplicando uma Entidade Comercial a um Objeto

A maneira mais fácil de aplicar uma entidade comercial a um objeto ou objetos é por meio de uma consulta.

. Clique em *Consultas > +Nova Consulta* e selecione o tipo de objeto desejado.  Você pode aplicar filtros para refinar ainda mais os resultados.
. Clique na caixa de seleção para selecionar o(s) objeto(s) aos quais você deseja aplicar a entidade comercial.
. Clique em *Ações em massa* e selecione *Adicionar anotação*.
. Escolha a anotação _Entidade Comercial_ e selecione o valor da entidade comercial desejada na lista.
. Clique em *Salvar* para aplicar a entidade comercial ao(s) objeto(s).


Você também pode aplicar uma entidade comercial a um objeto individual navegando até a página inicial de ativos do objeto e clicando em *+Anotação) na seção Dados do usuário.

Você também pode configurar umlink:task_create_annotation_rules.html["Regra de Anotação"] para aplicar entidades comerciais a objetos.


NOTE: Um objeto pode ter apenas uma entidade comercial associada a ele.



== Removendo uma Entidade Comercial de um objeto

Para remover uma entidade comercial de um ou mais objetos, consulte e selecione o(s) objeto(s), clique em *Ações em massa* e selecione _Remover anotação_.  Selecione a anotação Entidade Comercial e clique em *Excluir*.
