---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: Configurando o coletor de dados do HDS Ops Center. 
---
= Coletor de dados do Hitachi Ops Center
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados usa o conjunto integrado de aplicativos do Hitachi Ops Center para acessar dados de inventário e desempenho de vários dispositivos de armazenamento.  Para descoberta de inventário e capacidade, sua instalação do Ops Center deve incluir os componentes "Serviços comuns" e "Administrador".  Para coleta de desempenho, você também deve ter o "Analyzer" implantado.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário deste coletor de dados.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Sistemas de Armazenamento | Armazenar 


| Volume | Volume 


| Grupos de Paridade | Pool de armazenamento (RAID), grupos de discos 


| Disco | Disco 


| Pool de armazenamento | Pool de armazenamento (fino, SNAP) 


| Grupos de Paridade Externa | Pool de armazenamento (backend), grupos de discos 


| Porta | Nó de armazenamento → Nó controlador → Porta 


| Grupos de anfitriões | Mapeamento e mascaramento de volume 


| Pares de Volume | Sincronização de armazenamento 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos de inventário

Você deve ter o seguinte para coletar dados de inventário:

* Endereço IP ou nome do host do servidor do Ops Center que hospeda o componente "Serviços Comuns"
* Conta de usuário root/sysadmin e senha que existem em todos os servidores que hospedam componentes do Ops Center.  O HDS não implementou o suporte à API REST para uso por usuários LDAP/SSO até o Ops Center 10.8+




== Requisitos de desempenho

Os seguintes requisitos devem ser atendidos para coletar dados de desempenho:

O módulo "Analyzer" do HDS Ops Center deve ser instalado. Os arrays de armazenamento devem alimentar o módulo "Analyzer" do Ops Center.



== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do Hitachi Ops Center | Endereço IP ou nome de domínio totalmente qualificado do servidor do Ops Center que hospeda o componente "Serviços Comuns" 


| Nome de usuário | Nome de usuário para o servidor do Ops Center. 


| Senha | Senha usada para o servidor do Ops Center. 
|===


== Configuração avançada

|===


| Campo | Descrição 


| Tipo de conexão | HTTPS (porta 443) é o padrão 


| Substituir porta TCP | Especifique a porta a ser usada se não for a padrão 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário.  O padrão é 40. 


| Escolha 'Excluir' ou 'Incluir' para especificar uma lista | Especifique se deseja incluir ou excluir a lista de matrizes abaixo ao coletar dados. 


| Lista de dispositivos de filtro | Lista separada por vírgulas de números de série de dispositivos para incluir ou excluir 


| Intervalo de pesquisa de desempenho (seg) | Intervalo entre pesquisas de desempenho.  O padrão é 300. 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
