---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: Use uma consulta para atribuir vários aplicativos ou anotações a objetos ou remover vários aplicativos ou anotações de objetos. 
keywords: query, queries, application, annotation, multiple 
---
= Atribuir vários aplicativos ou remover vários aplicativos de ativos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Você pode atribuir várioslink:task_create_application.html["aplicações"] para ou remover vários aplicativos de ativos usando uma consulta em vez de ter que atribuí-los ou removê-los manualmente.


NOTE: Você pode usar estas etapas para adicionar ou removerlink:task_defining_annotations.html["anotações"] da mesma forma.

.Antes de começar
Você já deve ter criado uma consulta que encontre todos os ativos que você deseja editar.

.Passos
. Clique em *Explorar* e selecione *Consultas Métricas*.
+
A página Consultas é exibida.

. Clique no nome da consulta que encontra os ativos.
+
A lista de ativos associados à consulta é exibida.

. Selecione os ativos desejados na lista ou clique na caixa de seleção superior para selecionar Todos.
+
O menu suspenso Ações em massa é exibido.

. Para adicionar um aplicativo aos ativos selecionados, clique em Ações em massa e selecione *Adicionar aplicativo*.
. Selecione um ou mais aplicativos.
+
Você pode selecionar vários aplicativos para hosts, volumes internos, qtrees e máquinas virtuais; no entanto, você pode selecionar apenas um aplicativo para um volume ou compartilhamento.

. Clique em *Salvar*.
. Para remover um aplicativo atribuído aos ativos, clique em Ações em massa e selecione *Remover aplicativo*.
. Selecione o aplicativo ou aplicativos que você deseja remover.
. Clique em *Excluir*.


Quaisquer novos aplicativos que você atribuir substituirão quaisquer aplicativos no ativo que foram derivados de outro ativo.  Por exemplo, os volumes herdam aplicativos de hosts e, quando novos aplicativos são atribuídos a um volume, o novo aplicativo tem precedência sobre o aplicativo derivado.

Depois de clicar em _Salvar_ em uma adição em massa ou em _Remover_ em uma ação de exclusão em massa, o Data Infrastructure Insights informa que a ação levará algum tempo.  Você pode ignorar esta mensagem; a ação continuará em segundo plano.


NOTE: Para ambientes com grandes quantidades de ativos relacionados, a herança de atribuições de aplicativos para esses ativos pode levar vários minutos.  Se você tiver muitos bens relacionados, reserve mais tempo para que a herança ocorra.
