---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Configurando o coletor de dados DELL EMC Celerra. 
---
= Coletor de dados de arquivo DELL EMC VNX (antigo Celerra Unified Storage System)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor de dados adquire informações de inventário do VNX File Storage System.  Para configuração, este coletor de dados requer o endereço IP dos processadores de armazenamento e um nome de usuário e senha somente leitura.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados do arquivo VNX.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Servidor de rede Celerra/Pool de armazenamento Celerra | Pool de armazenamento 


| Sistema de arquivos | Volume interno 


| Movedor de dados | Controlador 


| Sistema de arquivos montado em um movimentador de dados | Compartilhamento de arquivos 


| Exportações CIFS e NFS | Compartilhar 


| Volume do disco | LUN de backend 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

Você precisa do seguinte para configurar este coletor de dados:

* O endereço IP do processador de armazenamento
* Nome de usuário e senha somente leitura
* Porta SSH 22




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do arquivo VNX | Endereço IP ou nome de domínio totalmente qualificado do dispositivo de arquivo VNX 


| Nome de usuário | Nome usado para efetuar login no dispositivo de arquivo VNX 


| Senha | Senha usada para efetuar login no dispositivo de arquivo VNX 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (minutos) | Intervalo entre pesquisas de inventário. O padrão é 20 minutos. 
|===


== Solução de problemas

Algumas coisas que você pode tentar se tiver problemas com este coletor de dados:



=== Inventário

[cols="2*"]
|===
| Problema: | Experimente isto: 


| Erro: Não é possível prosseguir enquanto a atualização do DART está em andamento | Solução possível: pause o coletor de dados e aguarde a conclusão da atualização do DART antes de tentar outra solicitação de aquisição. 
|===
Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
