---
sidebar: sidebar 
permalink: task_dc_cohesity_smartfiles.html 
keywords: data collector, cohesity 
summary: Configurando o coletor de dados Cohesity SmartFiles. 
---
= Coletor de dados Cohesity SmartFiles
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Este coletor baseado em API REST adquirirá um cluster Cohesity, descobrindo as “Visualizações” (como Volumes Internos do Data Infrastructure Insights ), os vários nós, além de coletar métricas de desempenho.



== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| IP do Cluster de Coesão | Endereço IP do cluster Cohesity 


| Nome de usuário | Nome de usuário para o cluster Cohesity 


| Senha | Senha usada para o cluster Cohesity 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta usada para comunicação TCP com o cluster Cohesity 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 


| Intervalo de pesquisa de desempenho (min) | Intervalo entre pesquisas de desempenho. O padrão é 900 segundos. 
|===


== Solução de problemas

Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
