---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Configuração do coletor de dados do cônsul 
---
= Coletor de Dados do Cônsul
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa esse coletor de dados para coletar métricas do Consul.



== Instalação

. Em *Observabilidade > Coletores*, clique em *+Coletor de Dados*.  Escolha Cônsul.
+
Se você não configurou um Agente para coleta, você será solicitado alink:task_config_telegraf_agent.html["instalar um agente"] no seu inquilino.

+
Se você já tiver um agente configurado, selecione o Sistema Operacional ou Plataforma apropriada e clique em *Continuar*.

. Siga as instruções na tela Configuração do Cônsul para configurar o coletor de dados.  As instruções variam dependendo do tipo de sistema operacional ou plataforma que você está usando para coletar dados.




== Configurar

Informações podem ser encontradas emlink:https://www.consul.io/docs/index.html["Documentação do Cônsul"] .



== Objetos e Contadores para cônsul

Os seguintes objetos e seus contadores são coletados:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objeto: | Identificadores: | Atributos: | Pontos de dados: 


| Cônsul | Nó de serviço de verificação de ID de namespace | IP do nó SO do nó UUID do nó Nome do nó Nome do serviço Verificar nome ID do serviço Status | Aviso de ultrapassagem crítica 
|===


== Solução de problemas

Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página.
