---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'Configurando o coletor de dados HP Enterprise Alletra 6000 (antigo Nimble).' 
---
= Coletor de dados HPE Alletra 6000
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados HP Enterprise Alletra 6000 (anteriormente Nimble) oferece suporte a dados de inventário e desempenho para matrizes de armazenamento Alletra 6000.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário deste coletor.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Variedade | Armazenar 


| Disco | Disco 


| Volume | Volume 


| Piscina | Pool de armazenamento 


| Iniciador | Alias do host de armazenamento 


| Controlador | Nó de armazenamento 


| Interface Fibre Channel | Controlador 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

Você deve ter o seguinte para coletar dados de inventário e configuração do array de armazenamento:

* O array deve ser instalado e configurado e acessível pelo cliente por meio de seu nome de domínio totalmente qualificado (FQDN) ou endereço IP de gerenciamento do array.
* O array deve estar executando o NimbleOS 2.3.x ou posterior.
* Você deve ter um nome de usuário e uma senha válidos para o array com pelo menos a função de nível "Operador".  A função "Convidado" não tem acesso suficiente para entender as configurações do iniciador.
* A porta 5392 deve estar aberta no array.


Você deve ter o seguinte para coletar dados de desempenho do array de armazenamento:

* O array deve estar executando o NimbleOS 4.0.0 ou posterior
* O array deve ter volumes configurados.  A única API de desempenho que o NimbleOS tem é para volumes, e quaisquer estatísticas que os relatórios do Data Infrastructure Insights são derivados das estatísticas sobre volumes




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP de gerenciamento de matriz | Nome de domínio totalmente qualificado (FQDN) ou endereço IP de gerenciamento de matriz. 


| Nome de usuário | Nome de usuário para o array 


| Senha | Senha para o array 
|===


== Configuração avançada

|===


| Campo | Descrição 


| Porta | Porta usada pela API REST do Nimble.  O padrão é 5392. 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 
|===
Observação: o intervalo de pesquisa de desempenho padrão é de 300 segundos e não pode ser alterado.  Este é o único intervalo suportado pelo HPE Alletra 6000.
