---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Configurando o coletor de dados IBM Cleversafe. 
---
= Coletor de dados IBM Cleversafe
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa esse coletor de dados para descobrir dados de inventário e desempenho para sistemas de armazenamento IBM Cleversafe.


NOTE: O IBM Cleversafe é medido a uma taxa de TB brutos diferente da taxa de unidade gerenciada.  Cada 40 TB de capacidade não formatada do IBM Cleversafe é cobrado como 1link:concept_subscribing_to_cloud_insights.html#pricing["Unidade Gerenciada (UM)"] .



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados IBM Cleversafe.  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Pool de armazenamento | Pool de armazenamento 


| Recipiente | Volume interno 


| Recipiente | Compartilhamento de arquivos 


| Compartilhamento NFS | Compartilhar 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* O endereço IP dos serviços de dados externos para o cluster
* Nome de usuário e senha do administrador
* Porta 9440




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| IP do gerenciador ou nome do host | Endereço IP ou nome do host do nó de gerenciamento 


| Nome de usuário | Nome de usuário para a conta de usuário com função de superusuário ou administrador do sistema 


| Senha | Senha para a conta de usuário com função de superusuário ou administrador do sistema 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. 


| Tempo limite de conexão HTTP (seg) | Tempo limite de HTTP em segundos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
