---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Configurando o coletor de dados do Azure NetApp Files . 
---
= Configurando o coletor de dados do Azure NetApp Files
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados do Azure NetApp Files para adquirir dados de inventário e desempenho.



== Requisitos

Você precisa das seguintes informações para configurar este coletor de dados.

* Requisito de porta: 443 HTTPS
* IP REST de gerenciamento do Azure (management.azure.com)
* ID do cliente principal do serviço do Azure (conta de usuário)
* Chave de autenticação principal do serviço do Azure (senha do usuário)
* Você precisa configurar uma conta do Azure para descoberta do Data Infrastructure Insights .
+
Depois que a conta estiver configurada corretamente e você registrar o aplicativo no Azure, você terá as credenciais necessárias para descobrir a instância do Azure com o Data Infrastructure Insights.  O link a seguir descreve como configurar a conta para descoberta:



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== Configuração

Insira os dados nos campos do coletor de dados de acordo com a tabela abaixo:

[cols="2*"]
|===
| Campo | Descrição 


| ID do cliente principal do serviço do Azure | ID de login no Azure 


| ID do locatário do Azure | ID do locatário do Azure 


| Chave de Autenticação Principal do Serviço do Azure | Chave de autenticação de login 


| Entendo que a Microsoft me cobra por solicitações de API | Marque esta opção para verificar se você entendeu que a Microsoft cobra por solicitações de API feitas pela pesquisa do Insight. 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 60 
|===


== Solução de problemas

* As credenciais usadas pelo seu coletor de dados ANF devem ter acesso a quaisquer assinaturas do Azure que contenham volumes ANF.
* Se o acesso do Leitor causar falha na coleta de desempenho, tente conceder acesso de colaborador em um nível de grupo de recursos.


Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
