---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Configurando o coletor de dados Nutanix. 
---
= Coletor de dados Nutanix NX
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados Nutanix para descobrir dados de inventário e desempenho para sistemas de armazenamento Nutanix NX.



== Terminologia

A Data Infrastructure Insights adquire as seguintes informações de inventário do coletor de dados Nutanix. Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada. Ao visualizar ou solucionar problemas desse coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo do fornecedor/modelo | Termo do Insights de infraestrutura de dados 


| Pool de storage | Pool de storage 


| Recipiente Nutanix | Volume interno 


| Recipiente Nutanix | Partilha de ficheiros 


| Compartilhamento NFS | Partilhar 
|===
Nota: Estes são apenas mapeamentos de terminologia comuns e podem não representar todos os casos para este coletor de dados.



== Requisitos

* O endereço IP dos serviços de dados externos para o cluster
* Nome de usuário e senha somente leitura, a menos que grupos_de volume estejam em uso, nesse caso, nome de usuário e senha de administrador são necessários
* Requisito de porta: HTTPS 443




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP externo do prisma | O endereço IP dos serviços de dados externos para o cluster 


| Nome de utilizador | Nome de usuário para a conta de administrador 


| Palavra-passe | Palavra-passe para a conta de administrador 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta de TCP | Porta TCP usada para se conetar ao array Nutanix. A predefinição é 9440. 


| Intervalo de pesquisa de inventário (min) | Intervalo entre sondagens de inventário. O padrão é 60 minutos. 


| Intervalo de pesquisa de desempenho (seg) | Intervalo entre sondagens de desempenho. O padrão é 300 segundos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de dados podem ser encontradas link:concept_requesting_support.html["Suporte"]na página ou no link:reference_data_collector_support_matrix.html["Matriz de suporte do Data Collector"].
