---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Copie os valores da tabela para a área de transferência usando a seleção de texto ou a cópia com um clique para transferência eficiente de dados para campos de pesquisa e aplicativos externos. 
keywords: query, queries, copy, values, clipboard 
---
= Copiando valores de tabela
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Otimize seu fluxo de trabalho copiando valores de tabelas diretamente para a área de transferência para uso em pesquisas ou aplicativos externos. Escolha entre a seleção manual de texto ou a prática cópia com um clique para campos de valor único com links de ativos.

.Sobre esta tarefa
Há dois métodos que você pode usar para copiar valores de tabelas ou resultados de consultas para a área de transferência.

.Passos
. Método 1: Destaque o texto desejado com o mouse, copie-o e cole-o nos campos de pesquisa ou outros aplicativos.
. Método 2: Para campos de valor único, passe o mouse sobre o campo e clique no ícone da área de transferência que aparece.  O valor é copiado para a área de transferência para uso em campos de pesquisa ou outros aplicativos.
+
Observe que somente valores que são links para ativos podem ser copiados usando este método.  Somente campos que incluem valores únicos (ou seja, não listas) têm o ícone de cópia.


