---
sidebar: sidebar 
permalink: task_dc_ms_azure.html 
keywords: data collector, azure, 
summary: Configurando o coletor de dados de computação do Azure. 
---
= Configurando o coletor de dados de computação do Azure
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa o coletor de dados de computação do Azure para adquirir dados de inventário e desempenho de instâncias de computação do Azure.



== Requisitos

Você precisa das seguintes informações para configurar este coletor de dados.

* Requisito de porta: 443 HTTPS
* URI de redirecionamento do Azure OAuth 2.0 (login.microsoftonline.com)
* IP REST de gerenciamento do Azure (management.azure.com)
* IP do Gerenciador de Recursos do Azure (management.core.windows.net)
* ID do aplicativo principal do serviço do Azure (cliente) (função de leitor necessária)
* Chave de autenticação principal do serviço do Azure (senha do usuário)
* Você precisa configurar uma conta do Azure para descoberta do Data Infrastructure Insights .
+
Depois que a conta estiver configurada corretamente e você registrar o aplicativo no Azure, você terá as credenciais necessárias para descobrir a instância do Azure com o Data Infrastructure Insights.  O link a seguir descreve como configurar a conta para descoberta.https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]





== Configuração

Insira os dados nos campos do coletor de dados de acordo com a tabela abaixo:

[cols="2*"]
|===
| Campo | Descrição 


| ID do aplicativo principal do serviço do Azure (cliente) (função de leitor necessária) | ID de login no Azure.  Requer acesso à função de leitor. 


| ID do locatário do Azure | ID do locatário da Microsoft 


| Chave de Autenticação Principal do Serviço do Azure | Chave de autenticação de login 


| Entendo que a Microsoft me cobra por solicitações de API | Marque esta opção para verificar se você entendeu que a Microsoft cobra por solicitações de API feitas pela pesquisa do Insight. 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 60 


| Selecione 'Excluir' ou 'Incluir' para aplicar ao filtro VMs por tags | Especifique se deseja incluir ou excluir VMs por tags ao coletar dados.  Se "Incluir" for selecionado, o campo Chave da tag não poderá ficar vazio. 


| Chaves e valores de tags para filtrar VMs | Clique em *+ Filtrar tag* para escolher quais VMs (e discos associados) incluir/excluir, filtrando por chaves e valores que correspondem às chaves e valores das tags na VM.  A chave da tag é obrigatória, o valor da tag é opcional.  Quando o valor da tag estiver vazio, a VM será filtrada, desde que corresponda à chave da tag. 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 300 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
