---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: A Resolução do dispositivo ajuda você a monitorar com precisão o desempenho e o inventário em seu ambiente. 
---
= Regras de resolução de dispositivos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Crie regras de resolução de dispositivos para identificar hosts, armazenamento e fitas que não são identificados automaticamente atualmente pelo Data Infrastructure Insights.  As regras que você cria identificam os dispositivos atualmente em seu ambiente e também identificam dispositivos semelhantes à medida que são adicionados ao seu ambiente.



== Criando regras de resolução de dispositivos

Ao criar regras, você começa identificando a fonte de informações contra a qual a regra é executada, o método usado para extrair informações e se a pesquisa de DNS é aplicada aos resultados da regra.

[cols="2*"]
|===


| Fonte usada para identificar o dispositivo | * Aliases SRM para hosts * Alias de armazenamento contendo um nome de host ou fita incorporado * Alias de switch contendo um nome de host ou fita incorporado * Nomes de zona contendo um nome de host incorporado 


| Método usado para extrair o nome do dispositivo da fonte | * Como está (extrai um nome de um SRM) * Delimitadores * Expressões regulares 


| Pesquisa de DNS | Especifica se você usa DNS para verificar o nome do host 
|===
Você cria regras na aba Regras de Resolução Automática.  As etapas a seguir descrevem o processo de criação de regras.

.Procedimento
. Clique em *Gerenciar > Resolução do dispositivo*
. Na aba *Regras de resolução automática*, clique em *+ Regra de host* ou *+ Regra de fita*.
+
A tela *Regra de Resolução* é exibida.

+

NOTE: Clique no link _Exibir critérios de correspondência_ para obter ajuda e exemplos de como criar expressões regulares.

. Na lista *Tipo*, selecione o dispositivo que você deseja identificar.
+
Você pode selecionar _Host_ ou _Tape_.

. Na lista *Fonte*, selecione a fonte que você deseja usar para identificar o host.
+
Dependendo da fonte escolhida, o Data Infrastructure Insights exibe a seguinte resposta:

+
.. *Zonas* lista as zonas e WWN que precisam ser identificadas pelo Data Infrastructure Insights.
.. *SRM* lista os aliases não identificados que precisam ser identificados pelo Data Infrastructure Insights
.. *Alias ​​de armazenamento* lista aliases de armazenamento e WWN que precisam ser identificados pelo Data Infrastructure Insights
.. *Switch alias* lista os aliases de switch que precisam ser identificados pelo Data Infrastructure Insights


. Na lista *Método*, selecione o método que você deseja empregar para identificar o host.
+
|===


| Fonte | Método 


| SRM | Como está, delimitadores, expressões regulares 


| Alias de armazenamento | Delimitadores, Expressões regulares 


| Alternar alias | Delimitadores, Expressões regulares 


| Zonas | Delimitadores, Expressões regulares 
|===
+
** Regras que usam delimitadores exigem delimitadores e o comprimento mínimo do nome do host.  O comprimento mínimo do nome do host é o número de caracteres que o Data Infrastructure Insights deve usar para identificar um host.  O Data Infrastructure Insights realiza pesquisas de DNS somente para nomes de host que sejam desse tamanho ou mais longos.
+
Para regras que usam delimitadores, a sequência de entrada é tokenizada pelo delimitador e uma lista de candidatos a nomes de host é criada fazendo várias combinações do token adjacente.  A lista é então classificada, da maior para a menor.  Por exemplo, para uma sequência de entrada de _vipsnq03_hba3_emc3_12ep0_, a lista resultaria no seguinte:

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3
*** hba3


** Regras que usam expressões regulares exigem uma expressão regular, o formato e a seleção de diferenciação entre maiúsculas e minúsculas.


. Clique em *Executar AR* para executar todas as regras ou clique na seta para baixo no botão para executar a regra que você criou (e quaisquer outras regras que tenham sido criadas desde a última execução completa do AR).
+
Os resultados da execução da regra são exibidos na guia *Identificação do FC*.





== Iniciando uma atualização automática da resolução do dispositivo

Uma atualização de resolução de dispositivo confirma alterações manuais que foram adicionadas desde a última execução completa de resolução automática de dispositivo.  A execução de uma atualização pode ser usada para confirmar e executar somente as novas entradas manuais feitas na configuração de resolução do dispositivo.  Nenhuma execução de resolução completa do dispositivo é realizada.

.Procedimento
. Efetue login na interface da web do Data Infrastructure Insights .
. Clique em *Gerenciar > Resolução do dispositivo*
. Na tela *Resolução do dispositivo*, clique na seta para baixo no botão *Executar RA*.
. Clique em *Atualizar* para iniciar a atualização.




== Identificação manual assistida por regras

Este recurso é usado para casos especiais em que você deseja executar uma regra específica ou uma lista de regras (com ou sem uma reordenação única) para resolver hosts, armazenamento e dispositivos de fita desconhecidos.

.Antes de começar
Você tem vários dispositivos que não foram identificados e também tem várias regras que identificaram com sucesso outros dispositivos.


NOTE: Se a sua fonte contiver apenas parte do nome de um host ou dispositivo, use uma regra de expressão regular e formate-a para adicionar o texto ausente.

.Procedimento
. Efetue login na interface da web do Data Infrastructure Insights .
. Clique em *Gerenciar > Resolução do dispositivo*
. Clique na aba *Identificação do Fibre Channel*.
+
O sistema exibe os dispositivos junto com seu status de resolução.

. Selecione vários dispositivos não identificados.
. Clique em *Ações em massa* e selecione *Definir resolução do host* ou *Definir resolução da fita*.
+
O sistema exibe a tela Identificar, que contém uma lista de todas as regras que identificaram dispositivos com sucesso.

. Altere a ordem das regras para uma ordem que atenda às suas necessidades.
+
A ordem das regras é alterada na tela Identificar, mas não é alterada globalmente.

. Selecione o método que atende às suas necessidades.


O Data Infrastructure Insights executa o processo de resolução do host na ordem em que os métodos aparecem, começando pelos que estão no topo.

Quando regras aplicáveis são encontradas, os nomes das regras são mostrados na coluna de regras e identificados como manuais.

Relacionado:link:task_device_resolution_fibre_channel.html["Resolução do dispositivo Fibre Channel"] link:task_device_resolution_ip.html["Resolução do dispositivo IP"] link:task_device_resolution_preferences.html["Configurando preferências de resolução do dispositivo"]
