---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Você define aplicativos que você aplica aos ativos do seu locatário, conforme necessário. 
keywords: application, create application, 
---
= Criando aplicativos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Para rastrear dados associados a aplicativos específicos em execução no seu locatário, você pode definir os aplicativos no Data Infrastructure Insights.

.Sobre esta tarefa
O Data Infrastructure Insights permite que você rastreie dados de ativos associados a aplicativos para coisas como relatórios de uso ou custo.

.Passos
. No menu Data Infrastructure Insights , clique em *Observabilidade > Enriquecer > Aplicativos*.  Selecione
+
A caixa de diálogo Adicionar aplicativo é exibida.

. Digite um nome exclusivo para o aplicativo.
. Selecione uma prioridade para o aplicativo.
. Clique em *Salvar*.


Após definir um aplicativo, ele pode ser atribuído aos ativos.



== Atribuição de aplicativos a ativos

Este procedimento atribui o aplicativo a um host como exemplo.  Você pode atribuir host, máquina virtual, volume ou volumes internos a um aplicativo.

.Passos
. Localize o ativo ao qual você deseja atribuir o aplicativo:
. Clique em *Consultas > +Nova Consulta* e pesquise por Host.
. Clique na caixa de seleção à esquerda do Host que você deseja associar ao aplicativo.
. Clique em *Ações em massa > Adicionar aplicativo*.
. Selecione o aplicativo ao qual você está atribuindo o ativo.


Quaisquer novos aplicativos que você atribuir substituirão quaisquer aplicativos no ativo que foram derivados de outro ativo.  Por exemplo, os volumes herdam aplicativos de hosts e, quando novos aplicativos são atribuídos a um volume, o novo aplicativo tem precedência sobre o aplicativo derivado.


NOTE: Para ambientes com grandes quantidades de ativos relacionados, a herança de atribuições de aplicativos para esses ativos pode levar vários minutos.  Se você tiver muitos bens relacionados, reserve mais tempo para que a herança ocorra.

.Depois que você terminar
Depois de atribuir o host ao aplicativo, você pode atribuir os ativos restantes ao aplicativo.  Para acessar a página inicial do aplicativo, clique em *Gerenciar > Aplicativo* e selecione o aplicativo que você criou.
