---
sidebar: sidebar 
permalink: task_configure_data_collectors.html 
keywords: acquisition, AU, data collector, collector, notification, notify, 
summary: Instruções gerais do coletor de dados 
---
= Configurando coletores de dados
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Você configura Coletores de Dados no seu ambiente do Data Infrastructure Insights para coletar dados de dispositivos no data center.

.Antes de começar
* Você deve ter configurado uma Unidade de Aquisição antes de começar a coletar dados.
* Você precisa de credenciais para os dispositivos dos quais está coletando dados.
* Endereços de rede de dispositivos, informações de conta e senhas são necessários para todos os dispositivos dos quais você está coletando dados.


.Passos
. No menu Data Infrastructure Insights , clique em *Observabilidade > Coletores*
+
O sistema exibe os Coletores de Dados disponíveis organizados por fornecedor.

. Clique em *+ Coletor* e selecione o coletor de dados a ser configurado.
+
Na caixa de diálogo, você pode configurar o coletor de dados e adicionar uma Unidade de Aquisição.

. Digite um nome para o coletor de dados.
. Clique em *Configuração avançada* para adicionar campos de configuração adicionais.  (Nem todos os coletores de dados exigem configuração avançada.)
. Clique em *Testar configuração* para verificar se o coletor de dados está configurado corretamente.
. Clique em *Adicionar coletor* para salvar a configuração e adicionar o coletor de dados ao seu locatário do Data Infrastructure Insights .


Pode levar até dois períodos de pesquisa antes que os dados do serviço sejam exibidos nos painéis ou estejam disponíveis para consulta.

* 1ª pesquisa de inventário: imediatamente
* 1ª pesquisa de dados de desempenho para estabelecer uma linha de base: imediatamente após a pesquisa de inventário
* 2ª pesquisa de desempenho: dentro de 15 segundos após a conclusão da 1ª pesquisa de desempenho


A pesquisa prossegue de acordo com os intervalos de pesquisa de desempenho e inventário configurados.
