---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configurar o coletor de dados NetApp StorageGRID 
keywords: data collector, queries, create, storagegrid 
---
= Coletor de dados NetApp StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O coletor de dados NetApp StorageGRID oferece suporte à coleta de inventário e desempenho das configurações do StorageGRID .

[NOTE]
====
Para fornecer medição consistente em relação aos direitos DII em todos os sistemas StorageGRID , independentemente da topologia e configuração do hardware subjacente, o Data Infrastructure Insights usa a capacidade total disponível (storagegrid_storage_utilization_total_space_bytes), em vez da capacidade RAW com base no layout do disco físico.

Para clientes que usam o modelo de licenciamento baseado em capacidade, o StorageGRID é medido como armazenamento de “objeto”.

Para clientes que usam o modelo de licenciamento legado (MU), o StorageGRID é medido como armazenamento secundário, a uma taxa de 40 TiB para 1 MU.

====


== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do coletor NetApp StorageGRID .  Para cada tipo de ativo adquirido, é mostrada a terminologia mais comum usada para esse ativo.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| StorageGRID | Armazenar 


| Nó | Nó 


| Inquilino | Pool de armazenamento 


| Balde | Volume interno 
|===


== Requisitos

A seguir estão os requisitos para configurar esta fonte de dados:

* Endereço IP do host StorageGRID
* Um nome de usuário e uma senha para um usuário que teve as funções de Consulta de Métrica e Acesso de Locatário atribuídas
* Porta 443 (ou 8443 se configurado)




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do host StorageGRID | Endereço IP de gerenciamento do StorageGRID (Grid Manager) 


| Nome de usuário | Nome usado para fazer login no StorageGRID (Grid Manager) 


| Senha | Senha usada para fazer login no StorageGRID (Grid Manager) 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 60 minutos 


| Intervalo de pesquisa de desempenho (seg) | O padrão é 900 segundos 
|===


== Logon único (SSO)

Olink:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"] As versões de firmware têm versões de API correspondentes; a API 3.0 e versões mais recentes oferecem suporte ao login de logon único (SSO).

|===


| Versão do firmware | Versão API | Suporte para logon único (SSO) 


| 11,1 | 2 | Não 


| 11,2 | 3,0 | Sim 


| 11,5 | 3,3 | Sim 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
