---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Configurando o coletor de dados do Microsoft Hyper-V. 
---
= Coletor de dados do Microsoft Hyper-V
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O coletor de dados do Microsoft Hyper-V adquire dados de inventário e desempenho do ambiente de computação do servidor virtualizado.  Este coletor de dados pode descobrir um host Hyper-V autônomo ou um cluster inteiro - crie um coletor por host autônomo ou cluster.



== Terminologia

O Data Infrastructure Insights adquire as seguintes informações de inventário do Microsoft Hyper-V (WMI).  Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para esse ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco Rígido Virtual | Disco Virtual 


| Hospedar | Hospedar 


| Máquina Virtual | Máquina Virtual 


| Volumes compartilhados em cluster (CSV), volume de partição | Armazenamento de dados 


| Dispositivo SCSI de Internet, LUN SCSI de múltiplos caminhos | LUN 


| Porta Fibre Channel | Porta 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

Os seguintes itens são necessários para configurar este coletor de dados:

* O Hyper-V requer a porta 5985 aberta para coleta de dados e acesso/gerenciamento remoto.
* Endereço IP ou FQDN do cluster ou hipervisor autônomo.  Usar o nome do host ou IP do cluster flutuante é provavelmente a abordagem mais confiável em vez de apontar o coletor para apenas um nó específico em um cluster.
* Conta de usuário de nível administrativo que funciona em todos os hipervisores do cluster.
* O WinRM precisa estar habilitado e escutando em todos os hipervisores
* Requisitos de porta: Porta 135 via WMI e portas TCP dinâmicas atribuídas de 1024 a 65535 para Windows 2003 e versões anteriores e de 49152 a 65535 para Windows 2008.
* A resolução de DNS deve ser bem-sucedida, mesmo que o coletor de dados esteja apontado apenas para um endereço IP
* Cada hipervisor Hyper-V deve ter a “Medição de Recursos” ativada para cada VM, em cada host.  Isso permite que cada hipervisor tenha mais dados disponíveis para o Data Infrastructure Insights em cada convidado.  Se isso não for definido, menos métricas de desempenho serão adquiridas para cada convidado.  Mais informações sobre medição de recursos podem ser encontradas na documentação da Microsoft:
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Visão geral da medição de recursos do Hyper-V"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["Habilitar-VMResourceMetering"]




NOTE: O coletor de dados do Hyper-V requer uma Unidade de Aquisição do Windows.



== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do cluster ou FQDN do cluster flutuante | O endereço IP ou nome de domínio totalmente qualificado para o cluster ou um hipervisor autônomo e não agrupado 


| Nome de usuário | Nome de usuário administrador para o hipervisor 


| Senha | Senha para o hipervisor 


| Sufixo de domínio DNS | O sufixo do nome do host que se combina com o nome do host simples para renderizar o FQDN de um hipervisor 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Intervalo de pesquisa de inventário (min) | O padrão é 20 minutos. 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
