---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: Identificar dispositivos inativos permite que você escolha excluí-los ou alocá-los a uma função ativa. 
---
= Identificação de dispositivos inativos
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Identificar os ativos que você tem e quem os está usando é fundamental para "dimensionar corretamente" e liberar uma infraestrutura não utilizada. Você pode facilmente realocar ou desativar recursos subutilizados e evitar compras desnecessárias.

Use as etapas a seguir para identificar ativos inativos.

.Passos
* Navegue até *observabilidade > explorar -> Nova consulta métrica*.
* Selecione _Storage_ na lista suspensa.
* Clique na engrenagem e adicione _isActive_ como uma coluna.
+
As linhas que mostram uma verificação estão ativas. "X" indica dispositivos inativos.



Para remover dispositivos inativos, basta selecionar os dispositivos a serem removidos e, na lista suspensa *ações em massa*, selecione _Excluir dispositivos inativos_.
