---
sidebar: sidebar 
permalink: task_dc_dell_xc_series.html 
keywords: data collector, Dell, EMC, xc 
summary: Configurando o coletor de dados Dell EMC Série XC. 
---
= Coletor de dados Dell EMC Série XC
:hardbreaks:
:allow-uri-read: 


[role="lead"]
O Data Infrastructure Insights usa esse coletor de dados para descobrir informações de inventário e desempenho para os arrays de armazenamento Dell EMC Série XC.



== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP externo do Prism | Endereço IP do servidor XC 


| Nome de usuário | Nome de usuário para o servidor XC 


| Senha | Senha usada para o servidor XC 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta TCP | Porta usada para comunicação TCP com o servidor XC 


| Intervalo de pesquisa de inventário (min) | Intervalo entre pesquisas de inventário. O padrão é 60 minutos. 


| Intervalo de pesquisa de desempenho (min) | Intervalo entre pesquisas de desempenho. O padrão é 300 segundos. 
|===


== Solução de problemas

Informações adicionais podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
