---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configurando o coletor de dados do Red Hat Virtualization. 
---
= Coletor de dados de virtualização Red Hat
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O coletor de dados DII para Red Hat Virtualization também oferece suporte ao projeto de código aberto oVirt e ao Oracle Linux Virtualization Manager. Este coletor de dados se comunica via API REST com a interface HTTPS na estação de gerenciamento.



== Terminologia

Para cada tipo de ativo adquirido pelo Data Infrastructure Insights, a terminologia mais comum usada para o ativo é mostrada.  Ao visualizar ou solucionar problemas neste coletor de dados, tenha em mente a seguinte terminologia:

[cols="2*"]
|===
| Termo de Fornecedor/Modelo | Termo de Data Infrastructure Insights 


| Disco | Disco Virtual 


| Hospedar | Hospedar 


| Máquina Virtual | Máquina Virtual 


| Domínio de armazenamento | Armazenamento de dados 


| Unidade Lógica | LUN 
|===
Observação: esses são apenas mapeamentos de terminologia comum e podem não representar todos os casos deste coletor de dados.



== Requisitos

* Endereço IP/nome do host do servidor RHV/oVirt/OLVM na porta 443 via API REST
* Nome de usuário e senha somente leitura
* RHV Versão 3.0+/Ovirt 4.0+/OLVM 4.0+




== Configuração

[cols="2*"]
|===
| Campo | Descrição 


| Endereço IP do servidor RHV/Ovirt/OLVM | Endereço IP da estação de gerenciamento 


| Nome de usuário | Nome de usuário 


| Senha | Senha 
|===


== Configuração avançada

[cols="2*"]
|===
| Campo | Descrição 


| Porta de comunicação HTTPS | Porta usada para comunicação HTTPS com RHEV 


| Intervalo de pesquisa de inventário (min) | O padrão é 20 minutos. 


| Desempenho da VM | Habilitar coleta de desempenho 


| Intervalo de medição de desempenho (seg) | O padrão é 900 
|===


== Solução de problemas

Informações adicionais sobre este Coletor de Dados podem ser encontradas emlink:concept_requesting_support.html["Apoiar"] página ou nolink:reference_data_collector_support_matrix.html["Matriz de Suporte ao Coletor de Dados"] .
