---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Modificando ou excluindo uma consulta 
keywords: query, queries, modify, edit, delete, remove 
---
= Modificando ou excluindo uma consulta
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Você pode alterar os critérios associados a uma consulta quando quiser alterar os critérios de pesquisa dos ativos que está consultando.



== Modificando uma consulta

.Passos
. Clique em *Explorar* e selecione *Todas as consultas de métricas*.
+
A página Consultas é exibida.

. Clique no nome da consulta
. Para adicionar um critério à consulta, clique no ícone Colunas e selecione uma métrica ou atributo da lista.


Depois de fazer todas as alterações necessárias, faça um dos seguintes:

* Clique no botão *Salvar* para salvar a consulta com o nome que foi usado inicialmente.
* Clique no menu suspenso ao lado do botão *Salvar* e selecione *Salvar como* para salvar a consulta com outro nome.  Isso não substitui a consulta original.
* Clique no menu suspenso ao lado do botão *Salvar* e selecione *Renomear* para alterar o nome da consulta que você usou inicialmente.  Isso substitui a consulta original.
* Clique no menu suspenso ao lado do botão *Salvar* e selecione *Descartar alterações* para reverter a consulta para as últimas alterações salvas.




== Excluindo uma consulta

Para excluir uma consulta, clique em *Consultas* e selecione *Mostrar todas as consultas* e faça um dos seguintes:

. Clique no menu de "três pontos" à direita da consulta e clique em *Excluir*.
. Clique no nome da consulta e selecione *Excluir* no menu suspenso *Salvar*.

